# This viminfo file was generated by Vim 8.1.
# You may edit it if you are careful!

# Viminfo version
|1,4

# Value of 'encoding' when this file was written
*encoding=utf-8


# hlsearch on (H) or off (h):
~h
# Last Search Pattern:
~MSle0~/registers

# Last Substitute Search Pattern:
~MSle0&.

# Last Substitute String:
$

# Command Line History (newest to oldest):
:tabf main.py
|2,0,1621147266,,"tabf main.py"
:tabnew mod.h
|2,0,1621147266,,"tabnew mod.h"
:s/\<j\>/k/g
|2,0,1621147266,,"s/\\<j\\>/k/g"
:vsplit main.c
|2,0,1621147266,,"vsplit main.c"
:%s/hello/goodbye/g
|2,0,1621147266,,"%s/hello/goodbye/g"
:vsplit intro.txt
|2,0,1621147266,,"vsplit intro.txt"
:s/\<b\>/cd/g
|2,0,1621147266,,"s/\\<b\\>/cd/g"
:s/a/ab/g
|2,0,1621147266,,"s/a/ab/g"
:s/\<cd\>/b/g
|2,0,1621147266,,"s/\\<cd\\>/b/g"
:s/\<ab\>/a/g
|2,0,1621147266,,"s/\\<ab\\>/a/g"
:! cp ~/.cinfo.vim ~/.cppinfo.vim
|2,0,1621147266,,"! cp ~/.cinfo.vim ~/.cppinfo.vim"
:%s/;/,/gc
|2,0,1621147266,,"%s/;/,/gc"
:%d
|2,0,1621147266,,"%d"
:wv! ~/.hinfo.vim
|2,0,1621147266,,"wv! ~/.hinfo.vim"
:s/hey/Hey/g
|2,0,1621147266,,"s/hey/Hey/g"
:wv ~/.pyinfo.vim
|2,0,1621147266,,"wv ~/.pyinfo.vim"
:!gcc % && ./a.out
|2,0,1621147266,,"!gcc % && ./a.out"
:!gcc main.c
|2,0,1621147266,,"!gcc main.c"
:!make % && ./a.out
|2,0,1621147266,,"!make % && ./a.out"
:!g++ % && ./a.out
|2,0,1621147266,,"!g++ % && ./a.out"
:wa
|2,0,1621147266,,"wa"
:rv! ~/.pyinfo.vim
|2,0,1621147266,,"rv! ~/.pyinfo.vim"
:tab solve.py
|2,0,1621147266,,"tab solve.py"
:tabf solver.py
|2,0,1621147266,,"tabf solver.py"
:tabf solve.py
|2,0,1621147266,,"tabf solve.py"
:help beffer
|2,0,1621147266,,"help beffer"
:help BufnewFile
|2,0,1621147266,,"help BufnewFile"
:help buffer
|2,0,1621147266,,"help buffer"
:help tabf
|2,0,1621147266,,"help tabf"
:tabf ~./
|2,0,1621147266,,"tabf ~./"
:! cp ~/.cinfo.vim ~/.hinfo.vim
|2,0,1621147266,,"! cp ~/.cinfo.vim ~/.hinfo.vim"
:tabf module.h
|2,0,1621147266,,"tabf module.h"
:t
|2,0,1621147266,,"t"
:reg 
|2,0,1621147266,,"reg "
:e
|2,0,1621147266,,"e"
:wv!
|2,0,1621147266,,"wv!"
:tabf ~/.cinfo.vim
|2,0,1621147266,,"tabf ~/.cinfo.vim"
:q
|2,0,1621147266,,"q"
:w
|2,0,1621147266,,"w"
:scripnames
|2,0,1621147266,,"scripnames"
:%y*
|2,0,1621147266,,"%y*"
:checkhealth
|2,0,1621147266,,"checkhealth"
:Helptags
|2,0,1621147266,,"Helptags"
:tabnew first_vim.py
|2,0,1621147266,,"tabnew first_vim.py"
:version
|2,0,1621147266,,"version"
:set wrap
|2,0,1621147266,,"set wrap"
:set breakindent
|2,0,1621147266,,"set breakindent"
:set formatoptions=l
|2,0,1621147266,,"set formatoptions=l"
:set lbr
|2,0,1621147266,,"set lbr"
:foldmethod=syntax
|2,0,1621147266,,"foldmethod=syntax"
:set foldmethod=syntax
|2,0,1621147266,,"set foldmethod=syntax"
:help folding
|2,0,1621147266,,"help folding"
:w !python
|2,0,1621147266,,"w !python"
:w !python3
|2,0,1621147266,,"w !python3"
:tabnew subscriber_member_function2.cpp
|2,0,1621147266,,"tabnew subscriber_member_function2.cpp"
:tabf ../
|2,0,1621147266,,"tabf ../"
:tabf ../CMakeLists.txt
|2,0,1621147266,,"tabf ../CMakeLists.txt"
:h find
|2,0,1621147266,,"h find"
:h expandtab
|2,0,1621147266,,"h expandtab"
:set expandtab 2
|2,0,1621147266,,"set expandtab 2"
:set expandtab=2
|2,0,1621147266,,"set expandtab=2"
:vim ~/.vimrc
|2,0,1621147266,,"vim ~/.vimrc"
:set shiftwidth=4
|2,0,1621147266,,"set shiftwidth=4"
:h tabstop
|2,0,1621147266,,"h tabstop"
:h shiftwidth()
|2,0,1621147266,,"h shiftwidth()"
:h shiftwidth
|2,0,1621147266,,"h shiftwidth"
:findf ~/.vimrc
|2,0,1621147266,,"findf ~/.vimrc"
:tabf CMakeLists.txt
|2,0,1621147266,,"tabf CMakeLists.txt"
:tabf ..
|2,0,1621147266,,"tabf .."
:tabnew src/publish_address_book.cpp
|2,0,1621147266,,"tabnew src/publish_address_book.cpp"
:tabf package.xml
|2,0,1621147266,,"tabf package.xml"
:tabf msg/AddressBook.msg
|2,0,1621147266,,"tabf msg/AddressBook.msg"
:tabf src/publish_address_book.cpp
|2,0,1621147266,,"tabf src/publish_address_book.cpp"
:s/MAX/MIN/g
|2,0,1621147266,,"s/MAX/MIN/g"
:set tabstop=4
|2,0,1621147266,,"set tabstop=4"
:set tabstop=2
|2,0,1621147266,,"set tabstop=2"
:set shiftwidth=2
|2,0,1621147266,,"set shiftwidth=2"
:tabf ../*4/*.cpp
|2,0,1621147266,,"tabf ../*4/*.cpp"
:%s/R/
|2,0,1621147266,,"%s/R/"
:%s/R/v/gc
|2,0,1621147266,,"%s/R/v/gc"
:set paste
|2,0,1621147266,,"set paste"
:set nopaste
|2,0,1621147266,,"set nopaste"
:s/v/root/g
|2,0,1621147266,,"s/v/root/g"
:s/v/T->root/g
|2,0,1621147266,,"s/v/T->root/g"
:tabf ../4_set_range_sum/set_range_sum.cpp
|2,0,1621147266,,"tabf ../4_set_range_sum/set_range_sum.cpp"
:%s/vector<list/list<list/gc
|2,0,1621147266,,"%s/vector<list/list<list/gc"
:wqwa
|2,0,1621147266,,"wqwa"
:Wq
|2,0,1621147266,,"Wq"
:s/std::pair<long long, int>/ipair/gc
|2,0,1621147266,,"s/std::pair<long long, int>/ipair/gc"
:scriptnames
|2,0,1621147266,,"scriptnames"
:wq!
|2,0,1621147266,,"wq!"
:w!
|2,0,1621147266,,"w!"
:tabf /usr/share/vim/vimrc
|2,0,1621147266,,"tabf /usr/share/vim/vimrc"
:h next
|2,0,1621147266,,"h next"
:mksession sess.vim
|2,0,1621147266,,"mksession sess.vim"
:tabf ./sess.vim
|2,0,1621147266,,"tabf ./sess.vim"
:Vtabnew hello.cpp
|2,0,1621147266,,"Vtabnew hello.cpp"
:split file2
|2,0,1621147266,,"split file2"
:hsplit hello.cpp
|2,0,1621147266,,"hsplit hello.cpp"
:vsplit yo.cpp
|2,0,1621147266,,"vsplit yo.cpp"
:!man cout
|2,0,1621147266,,"!man cout"
:!man std::cout 
|2,0,1621147266,,"!man std::cout "
:!man vim
|2,0,1621147266,,"!man vim"
:tabf ~/.vim/
|2,0,1621147266,,"tabf ~/.vim/"
:tabf /etc/vim/vimrc
|2,0,1621147266,,"tabf /etc/vim/vimrc"
:tabf make
|2,0,1621147266,,"tabf make"
:make test2
|2,0,1621147266,,"make test2"
:make test3
|2,0,1621147266,,"make test3"
:mkae
|2,0,1621147266,,"mkae"
:%s/c/
|2,0,1621147266,,"%s/c/"
:source
|2,0,1621147266,,"source"
:make test
|2,0,1621147266,,"make test"
:male
|2,0,1621147266,,"male"
:mae
|2,0,1621147266,,"mae"
:ake
|2,0,1621147266,,"ake"
:s/i/x/gc
|2,0,1621147266,,"s/i/x/gc"
:tabnew 3.in
|2,0,1621147266,,"tabnew 3.in"
:make 3
|2,0,1621147266,,"make 3"
:tabnew 4.in
|2,0,1621147266,,"tabnew 4.in"
:make 4
|2,0,1621147266,,"make 4"
:tabnew 5.in
|2,0,1621147266,,"tabnew 5.in"
:make 5
|2,0,1621147266,,"make 5"
:source S
|2,0,1621147266,,"source S"
:tabnew 1.in Makefile -p
|2,0,1621147266,,"tabnew 1.in Makefile -p"
:make1
|2,0,1621147266,,"make1"
:tabf Session.vim
|2,0,1621147266,,"tabf Session.vim"
:ls
|2,0,1621147266,,"ls"
:cd ..
|2,0,1621147266,,"cd .."
:time
|2,0,1621147266,,"time"
:type -a time
|2,0,1621147266,,"type -a time"
:mksession prim.vim
|2,0,1621147266,,"mksession prim.vim"
:tabf 1.in 2.in
|2,0,1621147266,,"tabf 1.in 2.in"
:source prim.vim
|2,0,1621147266,,"source prim.vim"
:make all
|2,0,1621147266,,"make all"
:%s/\\/ /gc
|2,0,1621147266,,"%s/\\\\/ /gc"
:make prim
|2,0,1621147266,,"make prim"
:amke
|2,0,1621147266,,"amke"
:%s/bfs/dfs/gc
|2,0,1621147266,,"%s/bfs/dfs/gc"
:! HardwareSimulator And.tst
|2,0,1621147266,,"! HardwareSimulator And.tst"
:tabf Not.hdl
|2,0,1621147266,,"tabf Not.hdl"
:! HardwareSimulator Or.tst
|2,0,1621147266,,"! HardwareSimulator Or.tst"
:! HardwareSimulator Xor.tst
|2,0,1621147266,,"! HardwareSimulator Xor.tst"
:s/s/sel/g
|2,0,1621147266,,"s/s/sel/g"
:! HardwareSimulator Mux.tst
|2,0,1621147266,,"! HardwareSimulator Mux.tst"
:s/sel/in/g
|2,0,1621147266,,"s/sel/in/g"
:! HardwareSimulator DMux.tst
|2,0,1621147266,,"! HardwareSimulator DMux.tst"
:! HardwareSimulator Not16.tst
|2,0,1621147266,,"! HardwareSimulator Not16.tst"
:!HardwareSimulator And.tst
|2,0,1621147266,,"!HardwareSimulator And.tst"
:!HardwareSimulator Or16.tst
|2,0,1621147266,,"!HardwareSimulator Or16.tst"
:!HardwareSimulator And16.tst
|2,0,1621147266,,"!HardwareSimulator And16.tst"
:tabf Mux.hdl
|2,0,1621147266,,"tabf Mux.hdl"
:!HardwareSimulator Mux16.tst
|2,0,1621147266,,"!HardwareSimulator Mux16.tst"
:tabf Or.hdl
|2,0,1621147266,,"tabf Or.hdl"
:find
|2,0,1621147266,,"find"
:! HardwareSimulator Mux16.tst
|2,0,1621147266,,"! HardwareSimulator Mux16.tst"
:tabf Mux16.hdl
|2,0,1621147266,,"tabf Mux16.hdl"
:tabf Mux4Way16.cmp
|2,0,1621147266,,"tabf Mux4Way16.cmp"
:tabf Mux4Way16.out
|2,0,1621147266,,"tabf Mux4Way16.out"
:! HardwareSimulator Mux4Way16.tst
|2,0,1621147266,,"! HardwareSimulator Mux4Way16.tst"
:! HardwareSimulator Mux8Way16.tst
|2,0,1621147266,,"! HardwareSimulator Mux8Way16.tst"
:! HardwareSimulator DMux4Way.tst
|2,0,1621147266,,"! HardwareSimulator DMux4Way.tst"
:tabf Mux8Way16.hdl
|2,0,1621147266,,"tabf Mux8Way16.hdl"
:tabnew Xor16.hdl
|2,0,1621147266,,"tabnew Xor16.hdl"
:%s/And/Xor/gc
|2,0,1621147266,,"%s/And/Xor/gc"
:! HardwareSimulator DMux8Way.tst
|2,0,1621147266,,"! HardwareSimulator DMux8Way.tst"
:s/x/y/g
|2,0,1621147266,,"s/x/y/g"
:s/zx/f/g
|2,0,1621147266,,"s/zx/f/g"
:tabf Add16.hdl
|2,0,1621147266,,"tabf Add16.hdl"
:! HardwareSimulator Add16.hdl
|2,0,1621147266,,"! HardwareSimulator Add16.hdl"
:! HardwareSimulator Add16.tst
|2,0,1621147266,,"! HardwareSimulator Add16.tst"
:! HardwareSimulator Or8Way.hdl
|2,0,1621147266,,"! HardwareSimulator Or8Way.hdl"
:! HardwareSimulator Or8Way.tst
|2,0,1621147266,,"! HardwareSimulator Or8Way.tst"
:! HardwareSimulator ALU.tst
|2,0,1621147266,,"! HardwareSimulator ALU.tst"
:edit main.cpp
|2,0,1621147266,,"edit main.cpp"
:make 1
|2,0,1621147266,,"make 1"
:source Makefile
|2,0,1621147266,,"source Makefile"
:make 1.ini
|2,0,1621147266,,"make 1.ini"
:%s/size/sz/gc
|2,0,1621147266,,"%s/size/sz/gc"
:make !.in
|2,0,1621147266,,"make !.in"
:%s/SortedHeap/sortedHeap/g
|2,0,1621147266,,"%s/SortedHeap/sortedHeap/g"
:make 1.n
|2,0,1621147266,,"make 1.n"
:tabnew reading.cpp
|2,0,1621147266,,"tabnew reading.cpp"
:tabf values.h
|2,0,1621147266,,"tabf values.h"
:tabf reading.cpp
|2,0,1621147266,,"tabf reading.cpp"
:! g++ reading.cpp && cat 1.in | ./a.out
|2,0,1621147266,,"! g++ reading.cpp && cat 1.in | ./a.out"
:%s/visited/dist/g/c
|2,0,1621147266,,"%s/visited/dist/g/c"
:%s/visited/dist/gc
|2,0,1621147266,,"%s/visited/dist/gc"
:! g++ main.cpp && cat 1.in | ./a.out
|2,0,1621147266,,"! g++ main.cpp && cat 1.in | ./a.out"
:! HardwareSimulator Bit.hdl
|2,0,1621147266,,"! HardwareSimulator Bit.hdl"
:! HardwareSimulator Bit.tst
|2,0,1621147266,,"! HardwareSimulator Bit.tst"
:! HardwareSimulator Register.tst
|2,0,1621147266,,"! HardwareSimulator Register.tst"
:! HardwareSimulator RAM8.tst
|2,0,1621147266,,"! HardwareSimulator RAM8.tst"
:tabf Register.hdl
|2,0,1621147266,,"tabf Register.hdl"
:tabf Bit.cmp
|2,0,1621147266,,"tabf Bit.cmp"
:tabf Bit.hdl
|2,0,1621147266,,"tabf Bit.hdl"
:ta
|2,0,1621147266,,"ta"
:tabf RAM64.hdl
|2,0,1621147266,,"tabf RAM64.hdl"
:! HardwareSimulator RAM64.tst
|2,0,1621147266,,"! HardwareSimulator RAM64.tst"
:tab ~/.vimrc
|2,0,1621147266,,"tab ~/.vimrc"
:! HardwareSimulator RAM512.tst
|2,0,1621147266,,"! HardwareSimulator RAM512.tst"
:tabf RAM4K.hdl
|2,0,1621147266,,"tabf RAM4K.hdl"
:! HardwareSimulator RAM4K.tst
|2,0,1621147266,,"! HardwareSimulator RAM4K.tst"
:tabf RAM16K.hdl
|2,0,1621147266,,"tabf RAM16K.hdl"
:! HardwareSimulator RAM16K.tst
|2,0,1621147266,,"! HardwareSimulator RAM16K.tst"
:tabf .
|2,0,1621147266,,"tabf ."
:! HardwareSimulator PC.tst
|2,0,1621147266,,"! HardwareSimulator PC.tst"
:tabf Fill.tst
|2,0,1621147266,,"tabf Fill.tst"
:tabf *.tst
|2,0,1621147266,,"tabf *.tst"
:tabf FillAutomatic.tst
|2,0,1621147266,,"tabf FillAutomatic.tst"
:Q!
|2,0,1621147266,,"Q!"
:! HardwareSimulator CPU.tst
|2,0,1621147266,,"! HardwareSimulator CPU.tst"
:! HardwareSimulator Memory.tst
|2,0,1621147266,,"! HardwareSimulator Memory.tst"
:tabf CPU.hdl
|2,0,1621147266,,"tabf CPU.hdl"
:tabf Memory.hdl
|2,0,1621147266,,"tabf Memory.hdl"
:! HardwareSimulator Computer.tst
|2,0,1621147266,,"! HardwareSimulator Computer.tst"
:! HardwareSimulator
|2,0,1621147266,,"! HardwareSimulator"
:%s/Hash/HashTable/gc
|2,0,1621147266,,"%s/Hash/HashTable/gc"
:! HardwareSimulator Mult.tst
|2,0,1621147266,,"! HardwareSimulator Mult.tst"
:make 2.in
|2,0,1621147266,,"make 2.in"
:! g++ main.cpp && cat 2.in | ./a.out
|2,0,1621147266,,"! g++ main.cpp && cat 2.in | ./a.out"
:! g++ main.cpp && ./a.out
|2,0,1621147266,,"! g++ main.cpp && ./a.out"
:! python3 Assembler.py
|2,0,1621147266,,"! python3 Assembler.py"
:find Makefile
|2,0,1621147266,,"find Makefile"
:mks
|2,0,1621147266,,"mks"
:make pong.asm
|2,0,1621147266,,"make pong.asm"
:make add.asm
|2,0,1621147266,,"make add.asm"
:make max
|2,0,1621147266,,"make max"
:make rect
|2,0,1621147266,,"make rect"
:ma
|2,0,1621147266,,"ma"
:make sum
|2,0,1621147266,,"make sum"
:make pong
|2,0,1621147266,,"make pong"
:! ls -la
|2,0,1621147266,,"! ls -la"
:! make rect
|2,0,1621147266,,"! make rect"
:tabf rect/Rect.hack
|2,0,1621147266,,"tabf rect/Rect.hack"
:tabf rect/cmp.hack
|2,0,1621147266,,"tabf rect/cmp.hack"
:tabnew rect/cmp.hack
|2,0,1621147266,,"tabnew rect/cmp.hack"
:! diff rect/Rect.hack rect/cmp.hack
|2,0,1621147266,,"! diff rect/Rect.hack rect/cmp.hack"
:tabf add/Add.hack
|2,0,1621147266,,"tabf add/Add.hack"
:tabnew add/cmp.hack
|2,0,1621147266,,"tabnew add/cmp.hack"
:! diff add/Add.hack add/cmp.hack
|2,0,1621147266,,"! diff add/Add.hack add/cmp.hack"
:! make max
|2,0,1621147266,,"! make max"
:tabf max/Max.hack
|2,0,1621147266,,"tabf max/Max.hack"
:tabnew max/cmp.hack
|2,0,1621147266,,"tabnew max/cmp.hack"
:! diff max/Max.hack max/cmp.hack
|2,0,1621147266,,"! diff max/Max.hack max/cmp.hack"
:! make pong
|2,0,1621147266,,"! make pong"
:tabnew pong/cmp.hack
|2,0,1621147266,,"tabnew pong/cmp.hack"
:! wget https://github.com/jtdowney/nand2tetris/blob/master/06/pong/Pong.hack
|2,0,1621147266,,"! wget https://github.com/jtdowney/nand2tetris/blob/master/06/pong/Pong.hack"
:! mv Pong.hack cmp.hack
|2,0,1621147266,,"! mv Pong.hack cmp.hack"
:mv cmp.hack pong/
|2,0,1621147266,,"mv cmp.hack pong/"
:! mv cmp.hack pong/
|2,0,1621147266,,"! mv cmp.hack pong/"
:! diff pong/Pong.hack pong/cmp.hack
|2,0,1621147266,,"! diff pong/Pong.hack pong/cmp.hack"
:tabf ./pong/cmp.hack
|2,0,1621147266,,"tabf ./pong/cmp.hack"
:! g++ main.cpp -fsanitize=address
|2,0,1621147266,,"! g++ main.cpp -fsanitize=address"
:! cat 1.in | ./a.out
|2,0,1621147266,,"! cat 1.in | ./a.out"
:m!
|2,0,1621147266,,"m!"
:make 1.in
|2,0,1621147266,,"make 1.in"
:! make 1.in
|2,0,1621147266,,"! make 1.in"
:!make 1.in
|2,0,1621147266,,"!make 1.in"
:! python3 integers.py
|2,0,1621147266,,"! python3 integers.py"
:tabf ../StackTest/StackTest.vm
|2,0,1621147266,,"tabf ../StackTest/StackTest.vm"
:tabf ./StackArithmetic/*/*.vm
|2,0,1621147266,,"tabf ./StackArithmetic/*/*.vm"
:args ./StackArithmetic/*/*.vm
|2,0,1621147266,,"args ./StackArithmetic/*/*.vm"
:tabf *.py
|2,0,1621147266,,"tabf *.py"
:mak
|2,0,1621147266,,"mak"
:! python
|2,0,1621147266,,"! python"
:%s/sp/SP/gc
|2,0,1621147266,,"%s/sp/SP/gc"
:tabf ./StackArithmetic/SimpleAdd/SimpleAdd.asm
|2,0,1621147266,,"tabf ./StackArithmetic/SimpleAdd/SimpleAdd.asm"
:makr
|2,0,1621147266,,"makr"
:mark
|2,0,1621147266,,"mark"
:makrs
|2,0,1621147266,,"makrs"
:m
|2,0,1621147266,,"m"
:! make 
|2,0,1621147266,,"! make "
:! make add
|2,0,1621147266,,"! make add"
:tabf pulse/
|2,0,1621147266,,"tabf pulse/"
:! VMEmulator
|2,0,1621147266,,"! VMEmulator"
:explore
|2,0,1621147266,,"explore"
:!py
|2,0,1621147266,,"!py"
:! man split
|2,0,1621147266,,"! man split"
:! make nested
|2,0,1621147266,,"! make nested"
:!ad
|2,0,1621147266,,"!ad"
:! 	. VMTranslator/bin/activate && \	python3 VMTranslator.py FunctionCalls/StaticsTest/Class1.vm && \	deactivate
|2,0,1621147266,,"! 	. VMTranslator/bin/activate && \\	python3 VMTranslator.py FunctionCalls/StaticsTest/Class1.vm && \\	deactivate"
:!. VMTranslator/bin/activate && python3 VMTranslator.py FunctionCalls/StaticsTest/Class1.vm &&  deactivate
|2,0,1621147266,,"!. VMTranslator/bin/activate && python3 VMTranslator.py FunctionCalls/StaticsTest/Class1.vm &&  deactivate"
:tabf ProgramFlow/BasicLoop/BasicLoop.vm
|2,0,1621147266,,"tabf ProgramFlow/BasicLoop/BasicLoop.vm"
:! make basic
|2,0,1621147266,,"! make basic"
:tabf ./ProgramFlow/BasicLoop/BasicLoop.asm
|2,0,1621147266,,"tabf ./ProgramFlow/BasicLoop/BasicLoop.asm"
:tabf ProgramFlow/BasicLoop/*.asm
|2,0,1621147266,,"tabf ProgramFlow/BasicLoop/*.asm"
:! CPUEmulator ./StackArithmetic/SimpleAdd/SimpleAdd.tst
|2,0,1621147266,,"! CPUEmulator ./StackArithmetic/SimpleAdd/SimpleAdd.tst"
:source Session.vim
|2,0,1621147266,,"source Session.vim"
:tabf ../08/VMTranslator.py
|2,0,1621147266,,"tabf ../08/VMTranslator.py"
:!CPUEmulator
|2,0,1621147266,,"!CPUEmulator"
:tabf ./MemoryAccess/PointerTest/PointerTest.asm
|2,0,1621147266,,"tabf ./MemoryAccess/PointerTest/PointerTest.asm"
:!make poiniter
|2,0,1621147266,,"!make poiniter"
:! make stack
|2,0,1621147266,,"! make stack"
:! make all
|2,0,1621147266,,"! make all"
:tabf ../07/VMTranslator.py
|2,0,1621147266,,"tabf ../07/VMTranslator.py"
:foldmethod
|2,0,1621147266,,"foldmethod"
:set foldmethod
|2,0,1621147266,,"set foldmethod"
:help foldmethod
|2,0,1621147266,,"help foldmethod"
:marks
|2,0,1621147266,,"marks"
:! vim ~/.vimrc
|2,0,1621147266,,"! vim ~/.vimrc"
:set foldmethod=manual
|2,0,1621147266,,"set foldmethod=manual"
:18,8fo
|2,0,1621147266,,"18,8fo"
:set codefolding?
|2,0,1621147266,,"set codefolding?"
:set codefold?
|2,0,1621147266,,"set codefold?"
:set foldmethod?
|2,0,1621147266,,"set foldmethod?"
:set foldmethod=expr
|2,0,1621147266,,"set foldmethod=expr"
:18,26fo
|2,0,1621147266,,"18,26fo"
:tabf ./*/*/*.vm
|2,0,1621147266,,"tabf ./*/*/*.vm"
:n ./*/*/*.vm
|2,0,1621147266,,"n ./*/*/*.vm"
:help tab
|2,0,1621147266,,"help tab"
:next ./*/*/*.vm
|2,0,1621147266,,"next ./*/*/*.vm"
:args ./*/*/*.vm
|2,0,1621147266,,"args ./*/*/*.vm"
:tab all
|2,0,1621147266,,"tab all"
:find ./ProgramFlow/
|2,0,1621147266,,"find ./ProgramFlow/"
:! CPUEmulator
|2,0,1621147266,,"! CPUEmulator"
:tabf ./ProgramFlow/BasicLoop/BasicLoop.vm
|2,0,1621147266,,"tabf ./ProgramFlow/BasicLoop/BasicLoop.vm"
:! make fibs
|2,0,1621147266,,"! make fibs"
:tabf ProgramFlow/FibonacciSeries/FibonacciSeries.tst
|2,0,1621147266,,"tabf ProgramFlow/FibonacciSeries/FibonacciSeries.tst"
:tabf ProgramFlow/FibonacciSeries/FibonacciSeries.tst
|2,0,1621147266,,"tabf ProgramFlow/FibonacciSeries/FibonacciSeries.tst"
:tabf FibonacciSeries.asm
|2,0,1621147266,,"tabf FibonacciSeries.asm"
:! python3
|2,0,1621147266,,"! python3"
:make 
|2,0,1621147266,,"make "
:make add
|2,0,1621147266,,"make add"
:make stack
|2,0,1621147266,,"make stack"
:make pointer
|2,0,1621147266,,"make pointer"
:make static
|2,0,1621147266,,"make static"
:! ls
|2,0,1621147266,,"! ls"
:find ./VMTranslator.py
|2,0,1621147266,,"find ./VMTranslator.py"
:! make fibe
|2,0,1621147266,,"! make fibe"
:make basic
|2,0,1621147266,,"make basic"
:tabf ./VMTranslator/
|2,0,1621147266,,"tabf ./VMTranslator/"
:tabf ./FunctionCalls/FibonacciElement/Main.vm
|2,0,1621147266,,"tabf ./FunctionCalls/FibonacciElement/Main.vm"
:make fibs
|2,0,1621147266,,"make fibs"
::q
|2,0,1621147266,,":q"
:tabf ./FunctionCalls/FibonacciElement/FibonacciElement.asm
|2,0,1621147266,,"tabf ./FunctionCalls/FibonacciElement/FibonacciElement.asm"
:tabf ./ProgramFlow/FibonacciSeries/FibonacciSeries.vm
|2,0,1621147266,,"tabf ./ProgramFlow/FibonacciSeries/FibonacciSeries.vm"
:make fibe
|2,0,1621147266,,"make fibe"
:make simple
|2,0,1621147266,,"make simple"
:tabf 
|2,0,1621147266,,"tabf "
:tabf ./FunctionCalls/
|2,0,1621147266,,"tabf ./FunctionCalls/"
:tabf ./FunctionCalls/NestedCall/Sys.vm
|2,0,1621147266,,"tabf ./FunctionCalls/NestedCall/Sys.vm"
:make nest
|2,0,1621147266,,"make nest"
:make nested
|2,0,1621147266,,"make nested"
:make statics
|2,0,1621147266,,"make statics"
:tabf ./FunctionCalls/StaticsTest/Class1.asm
|2,0,1621147266,,"tabf ./FunctionCalls/StaticsTest/Class1.asm"
:tabf ./FunctionCalls/StaticsTest/StaticsTest.asm
|2,0,1621147266,,"tabf ./FunctionCalls/StaticsTest/StaticsTest.asm"
:Explore 
|2,0,1621147266,,"Explore "
:!VMEmulator
|2,0,1621147266,,"!VMEmulator"
:!make statics
|2,0,1621147266,,"!make statics"
:!make fibe
|2,0,1621147266,,"!make fibe"
:!make nested
|2,0,1621147266,,"!make nested"
:!make simple
|2,0,1621147266,,"!make simple"
:!make fibs
|2,0,1621147266,,"!make fibs"
:!make basic
|2,0,1621147266,,"!make basic"
:!make pointer
|2,0,1621147266,,"!make pointer"
:!make static
|2,0,1621147266,,"!make static"
:!make stack
|2,0,1621147266,,"!make stack"
:!make add
|2,0,1621147266,,"!make add"
:'<,'>!
|2,0,1621147266,,"'<,'>!"
:tabnew 1.in
|2,0,1621147266,,"tabnew 1.in"
:W
|2,0,1621147266,,"W"
:1
|2,0,1621147266,,"1"
:Qa
|2,0,1621147266,,"Qa"
::::::::::!
|2,0,1621147266,,":::::::::!"
:tabnew Main.jack
|2,0,1621147266,,"tabnew Main.jack"
:!tabf ../HelloWorld/Main.jack
|2,0,1621147266,,"!tabf ../HelloWorld/Main.jack"
:!JackCompiler ../
|2,0,1621147266,,"!JackCompiler ../"
:tabf ../HelloWorld/Main.jack
|2,0,1621147266,,"tabf ../HelloWorld/Main.jack"
:tabf ../Fraction/Main.jack
|2,0,1621147266,,"tabf ../Fraction/Main.jack"
:tabf ../Average/Main.jack
|2,0,1621147266,,"tabf ../Average/Main.jack"
:tabf ../Fraction/Fraction.jack
|2,0,1621147266,,"tabf ../Fraction/Fraction.jack"
:%s/circle/circle2/gc
|2,0,1621147266,,"%s/circle/circle2/gc"
:tabnew Empty.jack
|2,0,1621147266,,"tabnew Empty.jack"
:tabnew Cross.jack
|2,0,1621147266,,"tabnew Cross.jack"
:tabnew White.jack
|2,0,1621147266,,"tabnew White.jack"
:mksession Session.vim
|2,0,1621147266,,"mksession Session.vim"
::w
|2,0,1621147266,,":w"
:tabnew Cell.jack
|2,0,1621147266,,"tabnew Cell.jack"
:tabnew State.jack
|2,0,1621147266,,"tabnew State.jack"
:Wa
|2,0,1621147266,,"Wa"
:tabf Cell.jack
|2,0,1621147266,,"tabf Cell.jack"
:tabf State.jack
|2,0,1621147266,,"tabf State.jack"
:tabnew TicTac.jack
|2,0,1621147266,,"tabnew TicTac.jack"
:tabnew KeyListener.jack
|2,0,1621147266,,"tabnew KeyListener.jack"
:tabf ./KeyListener.jack
|2,0,1621147266,,"tabf ./KeyListener.jack"
:tabnew GameState.jack
|2,0,1621147266,,"tabnew GameState.jack"
:s/0/2/g
|2,0,1621147266,,"s/0/2/g"
:tabf GameState.jack
|2,0,1621147266,,"tabf GameState.jack"
:! python3 password.py
|2,0,1621147266,,"! python3 password.py"
:qs
|2,0,1621147266,,"qs"
:%s/string/hello/g
|2,0,1621147266,,"%s/string/hello/g"
:tabnew output.txt
|2,0,1621147266,,"tabnew output.txt"
:tabnew main.py
|2,0,1621147266,,"tabnew main.py"
:!make py
|2,0,1621147266,,"!make py"
:ret
|2,0,1621147266,,"ret"
:tabf ~/.vimrc
|2,0,1621147266,,"tabf ~/.vimrc"
:retab!
|2,0,1621147266,,"retab!"
:!autopep8
|2,0,1621147266,,"!autopep8"
:!pip3 install autopep8
|2,0,1621147266,,"!pip3 install autopep8"
:tabm 4
|2,0,1621147266,,"tabm 4"
:!autopep8 -i main.py
|2,0,1621147266,,"!autopep8 -i main.py"
:! make py
|2,0,1621147266,,"! make py"
:! g++ main.c
|2,0,1621147266,,"! g++ main.c"
:tabnew binary_tree.cpp
|2,0,1621147266,,"tabnew binary_tree.cpp"
:tabnew binary_tree.h
|2,0,1621147266,,"tabnew binary_tree.h"
:tabnew parser.h
|2,0,1621147266,,"tabnew parser.h"
:%s/var/val/g
|2,0,1621147266,,"%s/var/val/g"
:tabf ../guess/1.in
|2,0,1621147266,,"tabf ../guess/1.in"
:! xdg-open ../
|2,0,1621147266,,"! xdg-open ../"
:!make i.in
|2,0,1621147266,,"!make i.in"
:! python3 main.py
|2,0,1621147266,,"! python3 main.py"
:!xdg-open .
|2,0,1621147266,,"!xdg-open ."
:s/0/1/g
|2,0,1621147266,,"s/0/1/g"
:s/1/0/g
|2,0,1621147266,,"s/1/0/g"
:.,.+1!
|2,0,1621147266,,".,.+1!"
:! make i.in
|2,0,1621147266,,"! make i.in"
:tabf d.in
|2,0,1621147266,,"tabf d.in"
:tabnew d.in
|2,0,1621147266,,"tabnew d.in"
:! make d.in
|2,0,1621147266,,"! make d.in"
:python3 JackAnalyser.py
|2,0,1621147266,,"python3 JackAnalyser.py"
:!python3 JackAnalyser.py
|2,0,1621147266,,"!python3 JackAnalyser.py"
:! source ./JackAnalyser/bin/activate
|2,0,1621147266,,"! source ./JackAnalyser/bin/activate"
:tabe 
|2,0,1621147266,,"tabe "
:tabf ./ExpressionLessSquare/Main.jack
|2,0,1621147266,,"tabf ./ExpressionLessSquare/Main.jack"
:Explore
|2,0,1621147266,,"Explore"
:! pwd
|2,0,1621147266,,"! pwd"
:!make express
|2,0,1621147266,,"!make express"
:tabnew CodeReader.py
|2,0,1621147266,,"tabnew CodeReader.py"
:tabf jack_tokenizer.py
|2,0,1621147266,,"tabf jack_tokenizer.py"
:!make jack_tokenizer
|2,0,1621147266,,"!make jack_tokenizer"
:tabf ./ExpressionLessSquare/Square.xml
|2,0,1621147266,,"tabf ./ExpressionLessSquare/Square.xml"
:tabf SquareGameT.xml
|2,0,1621147266,,"tabf SquareGameT.xml"
:! diff SquareGameT.JT.xml SquareGameT.xml
|2,0,1621147266,,"! diff SquareGameT.JT.xml SquareGameT.xml"
:! TextComparer
|2,0,1621147266,,"! TextComparer"
:! TextComparer SquareGameT.JT.xml SquareGameT.xml
|2,0,1621147266,,"! TextComparer SquareGameT.JT.xml SquareGameT.xml"
:! TextCompare
|2,0,1621147266,,"! TextCompare"
:tabm 0
|2,0,1621147266,,"tabm 0"
:tabf Square.xml
|2,0,1621147266,,"tabf Square.xml"
:tabf Main.jack
|2,0,1621147266,,"tabf Main.jack"
:g++ lims.cpp && ./a.out
|2,0,1621147266,,"g++ lims.cpp && ./a.out"
:! g++ lims.cpp && ./a.out
|2,0,1621147266,,"! g++ lims.cpp && ./a.out"
:s/a/b/g
|2,0,1621147266,,"s/a/b/g"
:!g++ --version
|2,0,1621147266,,"!g++ --version"
:%/long long/unsigned long long/g
|2,0,1621147266,,"%/long long/unsigned long long/g"
:%s/long long/unsigned long long/g
|2,0,1621147266,,"%s/long long/unsigned long long/g"
:tabf ~
|2,0,1621147266,,"tabf ~"
:%s/long long/int/g
|2,0,1621147266,,"%s/long long/int/g"
:%s/[nx][ny]/[ny][nx]/gc
|2,0,1621147266,,"%s/[nx][ny]/[ny][nx]/gc"
:!g++ main.cpp && cat 1.in | ./a.out
|2,0,1621147266,,"!g++ main.cpp && cat 1.in | ./a.out"
:!g++ main.cpp -fsanitize=address && cat 1.in | ./a.out
|2,0,1621147266,,"!g++ main.cpp -fsanitize=address && cat 1.in | ./a.out"
:!python3 roman.py
|2,0,1621147266,,"!python3 roman.py"
:%/>>/<</g
|2,0,1621147266,,"%/>>/<</g"
:s/>>/<</g
|2,0,1621147266,,"s/>>/<</g"
:tabf
|2,0,1621147266,,"tabf"
:tabnew 2.out
|2,0,1621147266,,"tabnew 2.out"
:!make 2.in
|2,0,1621147266,,"!make 2.in"
:! make 2
|2,0,1621147266,,"! make 2"
:! make
|2,0,1621147266,,"! make"
:tab
|2,0,1621147266,,"tab"
:color industry
|2,0,1621147266,,"color industry"
:color desert
|2,0,1621147266,,"color desert"
:%/ull/ll/g
|2,0,1621147266,,"%/ull/ll/g"
:%s/ull/ll/g
|2,0,1621147266,,"%s/ull/ll/g"
:python
|2,0,1621147266,,"python"
:!cat 1.in | python3 main.py
|2,0,1621147266,,"!cat 1.in | python3 main.py"
:5y
|2,0,1621147266,,"5y"
:tabm 3
|2,0,1621147266,,"tabm 3"
:s/i/t
|2,0,1621147266,,"s/i/t"
:s/i/t/g
|2,0,1621147266,,"s/i/t/g"
:s/ //g
|2,0,1621147266,,"s/ //g"
:!g++ hello_world.cpp && ./a.out
|2,0,1621147266,,"!g++ hello_world.cpp && ./a.out"
:!./a.out
|2,0,1621147266,,"!./a.out"
:s/3/ /g
|2,0,1621147266,,"s/3/ /g"
:s/_3//g
|2,0,1621147266,,"s/_3//g"
:%dp+
|2,0,1621147266,,"%dp+"
:%p+
|2,0,1621147266,,"%p+"
:s/M/j/g
|2,0,1621147266,,"s/M/j/g"
:%v
|2,0,1621147266,,"%v"
:%s/char * str/string str/gc
|2,0,1621147266,,"%s/char * str/string str/gc"
:s/str[i]/c/g
|2,0,1621147266,,"s/str[i]/c/g"
:s/str\[i\]/c/g
|2,0,1621147266,,"s/str\\[i\\]/c/g"
:%s/&str/str/gc
|2,0,1621147266,,"%s/&str/str/gc"
:%s/void/string/gc
|2,0,1621147266,,"%s/void/string/gc"
:k
|2,0,1621147266,,"k"
:!python3 inter
|2,0,1621147266,,"!python3 inter"
:!python3 interleavings.py
|2,0,1621147266,,"!python3 interleavings.py"
:!python3 interleavings.py > output.txt
|2,0,1621147266,,"!python3 interleavings.py > output.txt"
:tabf output.txt
|2,0,1621147266,,"tabf output.txt"
:!python
|2,0,1621147266,,"!python"
:tabf 2.in
|2,0,1621147266,,"tabf 2.in"
:%s/2//gc
|2,0,1621147266,,"%s/2//gc"
:!make 1 && make 2
|2,0,1621147266,,"!make 1 && make 2"
:tabf 2.out
|2,0,1621147266,,"tabf 2.out"
:%s/./a.out/main
|2,0,1621147266,,"%s/./a.out/main"
:%s/.\/a.out/main.g
|2,0,1621147266,,"%s/.\\/a.out/main.g"
:%s/.\/a.out/main/g
|2,0,1621147266,,"%s/.\\/a.out/main/g"
:tabf main.cpp
|2,0,1621147266,,"tabf main.cpp"
:mks Session.vim
|2,0,1621147266,,"mks Session.vim"
:tabf ./shapecolour.p
|2,0,1621147266,,"tabf ./shapecolour.p"
:Wqa
|2,0,1621147266,,"Wqa"
:s/,//g
|2,0,1621147266,,"s/,//g"
:tabf ./main2.cpp
|2,0,1621147266,,"tabf ./main2.cpp"
:!mawke
|2,0,1621147266,,"!mawke"
:!make 
|2,0,1621147266,,"!make "
:!make all
|2,0,1621147266,,"!make all"
:%s/big/b/g
|2,0,1621147266,,"%s/big/b/g"
:%s/small/s/g
|2,0,1621147266,,"%s/small/s/g"
:%s/'/"/g
|2,0,1621147266,,"%s/'/\"/g"
:%s/\'/\"/g
|2,0,1621147266,,"%s/\\'/\\\"/g"
:%s/\â€˜/\'/g
|2,0,1621147266,,"%s/\\â€˜/\\'/g"
:%s/â€˜/'/g
|2,0,1621147266,,"%s/â€˜/'/g"
:%/â€™/'/g
|2,0,1621147266,,"%/â€™/'/g"
:%s/â€™/'/g
|2,0,1621147266,,"%s/â€™/'/g"
:%s/convert/str2int/gc
|2,0,1621147266,,"%s/convert/str2int/gc"
:ewqa
|2,0,1621147266,,"ewqa"
:s/makepair/make_pair/g
|2,0,1621147266,,"s/makepair/make_pair/g"
:%s/\.\/a\.out/main/g
|2,0,1621147266,,"%s/\\.\\/a\\.out/main/g"
:!mks
|2,0,1621147266,,"!mks"
:mks!
|2,0,1621147266,,"mks!"
:!ma
|2,0,1621147266,,"!ma"
:tabf 1.cm
|2,0,1621147266,,"tabf 1.cm"
:! diff
|2,0,1621147266,,"! diff"
:! diff 1.out 1.cmp
|2,0,1621147266,,"! diff 1.out 1.cmp"
:%y
|2,0,1621147266,,"%y"
:tabf main2.cpp
|2,0,1621147266,,"tabf main2.cpp"
:!rm ./a.out
|2,0,1621147266,,"!rm ./a.out"
:!make krusk
|2,0,1621147266,,"!make krusk"
:!mke
|2,0,1621147266,,"!mke"
:s/\<count\>/countP/g
|2,0,1621147266,,"s/\\<count\\>/countP/g"
:s/j/n/g
|2,0,1621147266,,"s/j/n/g"
:tabnew main2.cpp
|2,0,1621147266,,"tabnew main2.cpp"
:s/i/j/g
|2,0,1621147266,,"s/i/j/g"
:!mkae
|2,0,1621147266,,"!mkae"
:'<,'>
|2,0,1621147266,,"'<,'>"
:%s/\<n\>/N/gc
|2,0,1621147266,,"%s/\\<n\\>/N/gc"
:tabnew 1.out
|2,0,1621147266,,"tabnew 1.out"
:tabf 1.cmp
|2,0,1621147266,,"tabf 1.cmp"
:tabm 1
|2,0,1621147266,,"tabm 1"
:tabf 1.in
|2,0,1621147266,,"tabf 1.in"
:tabf ../1/main.cpp
|2,0,1621147266,,"tabf ../1/main.cpp"
:s/prims/Prims/g
|2,0,1621147266,,"s/prims/Prims/g"
:tabnew 2.in
|2,0,1621147266,,"tabnew 2.in"
:make 2
|2,0,1621147266,,"make 2"
:%s/Prims/Prim's/gc
|2,0,1621147266,,"%s/Prims/Prim's/gc"
:!make 2
|2,0,1621147266,,"!make 2"
:!make 2cp
|2,0,1621147266,,"!make 2cp"
:!make 1
|2,0,1621147266,,"!make 1"
:make cp
|2,0,1621147266,,"make cp"
:make 1cp
|2,0,1621147266,,"make 1cp"
:!make cp
|2,0,1621147266,,"!make cp"
:mks Session.vim 
|2,0,1621147266,,"mks Session.vim "
:wqaa
|2,0,1621147266,,"wqaa"
:.!
|2,0,1621147266,,".!"
:tabm 2
|2,0,1621147266,,"tabm 2"
:%s/queue/deque/gc
|2,0,1621147266,,"%s/queue/deque/gc"
:tabnew 1.cmp
|2,0,1621147266,,"tabnew 1.cmp"
:!make 1cp
|2,0,1621147266,,"!make 1cp"
:s/1/2/g
|2,0,1621147266,,"s/1/2/g"
:!make 1out
|2,0,1621147266,,"!make 1out"
:!mae
|2,0,1621147266,,"!mae"
:!mak
|2,0,1621147266,,"!mak"
:!mk
|2,0,1621147266,,"!mk"
:~
|2,0,1621147266,,"~"
:tabf 1.out
|2,0,1621147266,,"tabf 1.out"
:%y+
|2,0,1621147266,,"%y+"
:!python3 main.py
|2,0,1621147266,,"!python3 main.py"
:python3 acronym	
|2,0,1621147266,,"python3 acronym	"
:!pythond3 acronym.py
|2,0,1621147266,,"!pythond3 acronym.py"
:!python3 acronym.py1
|2,0,1621147266,,"!python3 acronym.py1"
:!python3 acronym.py
|2,0,1621147266,,"!python3 acronym.py"
:!python3
|2,0,1621147266,,"!python3"
:!python3 longest_distance.py
|2,0,1621147266,,"!python3 longest_distance.py"
:wq
|2,0,1621147266,,"wq"
:%s/data/d/g
|2,0,1621147266,,"%s/data/d/g"
:!
|2,0,1621147266,,"!"
:! g++ 
|2,0,1621147266,,"! g++ "
:!python3 lucky.py
|2,0,1621147266,,"!python3 lucky.py"
:wqa
|2,0,1621147266,,"wqa"
:!m
|2,0,1621147266,,"!m"
:split
|2,0,1621147266,,"split"
:%yC
|2,0,1621147266,,"%yC"
:re
|2,0,1621147266,,"re"
:%yp
|2,0,1621147266,,"%yp"
:%y"p
|2,0,1621147266,,"%y\"p"
:%"py
|2,0,1621147266,,"%\"py"
:%py
|2,0,1621147266,,"%py"
:s/\<i\>/kg
|2,0,1621147266,,"s/\\<i\\>/kg"
:%=
|2,0,1621147266,,"%="
:s/\<i\>/j/g
|2,0,1621147266,,"s/\\<i\\>/j/g"
:%cy
|2,0,1621147266,,"%cy"
:%yc
|2,0,1621147266,,"%yc"
:%"cy
|2,0,1621147266,,"%\"cy"
:tabf module.c module.h
|2,0,1621147266,,"tabf module.c module.h"
:help tabnew
|2,0,1621147266,,"help tabnew"
:%s/\<.\>/./g
|2,0,1621147266,,"%s/\\<.\\>/./g"
:%s/\<.\>/\<_\>/g
|2,0,1621147266,,"%s/\\<.\\>/\\<_\\>/g"
:%s/\<.\>/_/g
|2,0,1621147266,,"%s/\\<.\\>/_/g"
:%s/./_/g
|2,0,1621147266,,"%s/./_/g"
:let "@ = expand("%")
|2,0,1621147266,,"let \"@ = expand(\"%\")"
:let @" = explore("%")
|2,0,1621147266,,"let @\" = explore(\"%\")"
:tabnew module_2.h
|2,0,1621147266,,"tabnew module_2.h"
:v
|2,0,1621147266,,"v"
:s
|2,0,1621147266,,"s"
:split ter
|2,0,1621147266,,"split ter"
:s/\<j\>/k/
|2,0,1621147266,,"s/\\<j\\>/k/"
:tabnew hello.h
|2,0,1621147266,,"tabnew hello.h"
:put expand("%")
|2,0,1621147266,,"put expand(\"%\")"
:put =expand("%")
|2,0,1621147266,,"put =expand(\"%\")"
:put strftime('%c')
|2,0,1621147266,,"put strftime('%c')"
:put =strftime('%c')
|2,0,1621147266,,"put =strftime('%c')"
:let = expand("%")
|2,0,1621147266,,"let = expand(\"%\")"
:p
|2,0,1621147266,,"p"
:%
|2,0,1621147266,,"%"
:let @"=expand("%")
|2,0,1621147266,,"let @\"=expand(\"%\")"
:qa
|2,0,1621147266,,"qa"
:qa!
|2,0,1621147266,,"qa!"
:tabf hello.h
|2,0,1621147266,,"tabf hello.h"
:tabnew module.h
|2,0,1621147266,,"tabnew module.h"
:tabnew
|2,0,1621147266,,"tabnew"
:tabf Makefile
|2,0,1621147266,,"tabf Makefile"
:tab ter
|2,0,1621147266,,"tab ter"
:!rm Makefile
|2,0,1621147266,,"!rm Makefile"
:!ls
|2,0,1621147266,,"!ls"
:1make
|2,0,1621147266,,"1make"
:tabnew Makefile
|2,0,1621147266,,"tabnew Makefile"
:tabe
|2,0,1621147266,,"tabe"
:E
|2,0,1621147266,,"E"
:make
|2,0,1621147266,,"make"
:help mksession
|2,0,1621147266,,"help mksession"
:vsplit
|2,0,1621147266,,"vsplit"
:help
|2,0,1621147266,,"help"
:close
|2,0,1621147266,,"close"
:help autocmd
|2,0,1621147266,,"help autocmd"
:endfor
|2,0,1621147266,,"endfor"
:elseif
|2,0,1621147266,,"elseif"
:tabf ~/.viminfo
|2,0,1621147266,,"tabf ~/.viminfo"
:!make
|2,0,1621147266,,"!make"
:s/\<i\>/k/g
|2,0,1621147266,,"s/\\<i\\>/k/g"
:q!
|2,0,1621147266,,"q!"
:wv cinfo.vim
|2,0,1621147266,,"wv cinfo.vim"
:rv! ~/.cinfo.vim
|2,0,1621147266,,"rv! ~/.cinfo.vim"
:!rv ~/.cinfo.vim
|2,0,1621147266,,"!rv ~/.cinfo.vim"
:tabf main.c
|2,0,1621147266,,"tabf main.c"
:tabf ~/.pyinfo.vim
|2,0,1621147266,,"tabf ~/.pyinfo.vim"
:erg
|2,0,1621147266,,"erg"
:tabnew main.c
|2,0,1621147266,,"tabnew main.c"
:ter
|2,0,1621147266,,"ter"
:set relativenumber
|2,0,1621147266,,"set relativenumber"
:tabnew 
|2,0,1621147266,,"tabnew "
:help session
|2,0,1621147266,,"help session"
:help rv
|2,0,1621147266,,"help rv"
:help viminfo
|2,0,1621147266,,"help viminfo"
:rv! pyinfo.vim
|2,0,1621147266,,"rv! pyinfo.vim"
:wv! pyinfo.vim
|2,0,1621147266,,"wv! pyinfo.vim"
:rv pyinfo.vim
|2,0,1621147266,,"rv pyinfo.vim"
:!python3 solve.py
|2,0,1621147266,,"!python3 solve.py"
:s/eqns/eqs/g
|2,0,1621147266,,"s/eqns/eqs/g"
:[
|2,0,1621147266,,"["
:!pip3 install sympy
|2,0,1621147266,,"!pip3 install sympy"
:!python3 sol
|2,0,1621147266,,"!python3 sol"
:tabf cinfo.vim
|2,0,1621147266,,"tabf cinfo.vim"
:tabf pyinfo.vim
|2,0,1621147266,,"tabf pyinfo.vim"
:rv cinfo.vim
|2,0,1621147266,,"rv cinfo.vim"
:wv pyinfo.vim
|2,0,1621147266,,"wv pyinfo.vim"
:set @" = expand("%")
|2,0,1621147266,,"set @\" = expand(\"%\")"
:tabnew main2.py
|2,0,1621147266,,"tabnew main2.py"
:!rv pyinfo.vim
|2,0,1621147266,,"!rv pyinfo.vim"
:scripname
|2,0,1621147266,,"scripname"
:rv! ../../c/zeev/cinfo.vim
|2,0,1621147266,,"rv! ../../c/zeev/cinfo.vim"
:%s/\<k\>/e/g
|2,0,1621147266,,"%s/\\<k\\>/e/g"
:let @" = expand("%")
|2,0,1621147266,,"let @\" = expand(\"%\")"
:put = strftime('%c')
|2,0,1621147266,,"put = strftime('%c')"
:help Session
|2,0,1621147266,,"help Session"
:python3 %
|2,0,1621147266,,"python3 %"
:!python3 %
|2,0,1621147266,,"!python3 %"
:wv! ~/.pyinfo.vim
|2,0,1621147266,,"wv! ~/.pyinfo.vim"
:rege
|2,0,1621147266,,"rege"
:wv ~/.cinfo.vim
|2,0,1621147266,,"wv ~/.cinfo.vim"
:wv! ~/.cinfo.vim
|2,0,1621147266,,"wv! ~/.cinfo.vim"
:reg
|2,0,1621147266,,"reg"
:tabm2
|2,0,1621147266,,"tabm2"
:reg d
|2,0,1621147266,,"reg d"
:let @" =expand("%")
|2,0,1621147266,,"let @\" =expand(\"%\")"

# Search String History (newest to oldest):
? \<j\>
|2,1,1621147266,,"\\<j\\>"
? \<main\>
|2,1,1621147266,,"\\<main\\>"
? hello
|2,1,1621147266,,"hello"
?/hello
|2,1,1621147266,47,"hello"
? \<b\>
|2,1,1621147266,,"\\<b\\>"
? \<cd\>
|2,1,1621147266,,"\\<cd\\>"
? \<ab\>
|2,1,1621147266,,"\\<ab\\>"
? \<ans\>
|2,1,1621147266,,"\\<ans\\>"
? \<world\>
|2,1,1621147266,,"\\<world\\>"
? hey
|2,1,1621147266,,"hey"
??buffer
|2,1,1621147266,63,"buffer"
??help tabf
|2,1,1621147266,63,"help tabf"
??filetype
|2,1,1621147266,63,"filetype"
??plugin
|2,1,1621147266,63,"plugin"
? \<w\>
|2,1,1621147266,,"\\<w\\>"
??add_exe
|2,1,1621147266,63,"add_exe"
??memory
|2,1,1621147266,63,"memory"
??AddTwoInts
|2,1,1621147266,63,"AddTwoInts"
??Add
|2,1,1621147266,63,"Add"
??add_execu
|2,1,1621147266,63,"add_execu"
??add_executable
|2,1,1621147266,63,"add_executable"
??request
|2,1,1621147266,63,"request"
??install
|2,1,1621147266,63,"install"
??build_depend
|2,1,1621147266,63,"build_depend"
??timer_call
|2,1,1621147266,63,"timer_call"
??find_package
|2,1,1621147266,63,"find_package"
??turt
|2,1,1621147266,63,"turt"
??subscription
|2,1,1621147266,63,"subscription"
??private
|2,1,1621147266,63,"private"
??String
|2,1,1621147266,63,"String"
??tur
|2,1,1621147266,63,"tur"
??kkkk
|2,1,1621147266,63,"kkkk"
??std::m
|2,1,1621147266,63,"std::m"
??std_msgs
|2,1,1621147266,63,"std_msgs"
??std_
|2,1,1621147266,63,"std_"
? \<add_newdoc_ufunc\>
|2,1,1621147266,,"\\<add_newdoc_ufunc\\>"
??def Settings
|2,1,1621147266,63,"def Settings"
??setting
|2,1,1621147266,63,"setting"
??set
|2,1,1621147266,63,"set"
? \<flags\>
|2,1,1621147266,,"\\<flags\\>"
??family
|2,1,1621147266,63,"family"
??plugged
|2,1,1621147266,63,"plugged"
??shiftwidth
|2,1,1621147266,63,"shiftwidth"
??find_package(rosidl_default_generators R
|2,1,1621147266,63,"find_package(rosidl_default_generators R"
??set(msg_files
|2,1,1621147266,63,"set(msg_files"
??"msg/AddressBook.msg
|2,1,1621147266,63,"\"msg/AddressBook.msg"
??rosidl_generate_interfaces(${PROJECT_NAME}
|2,1,1621147266,63,"rosidl_generate_interfaces(${PROJECT_NAME}"
??ament_export_dependencies(rosidl_default_runtime)
|2,1,1621147266,63,"ament_export_dependencies(rosidl_default_runtime)"
? MAX
|2,1,1621147266,,"MAX"
??root
|2,1,1621147266,63,"root"
? \<small_rotation\>
|2,1,1621147266,,"\\<small_rotation\\>"
? \<update\>
|2,1,1621147266,,"\\<update\\>"
??Vertex
|2,1,1621147266,63,"Vertex"
? >
|2,1,1621147266,,">"
??printf
|2,1,1621147266,63,"printf"
? \<Makes\>
|2,1,1621147266,,"\\<Makes\\>"
?/root
|2,1,1621147266,47,"root"
? R
|2,1,1621147266,,"R"
? \<new\>
|2,1,1621147266,,"\\<new\\>"
? v
|2,1,1621147266,,"v"
? \<fromString\>
|2,1,1621147266,,"\\<fromString\\>"
??size()
|2,1,1621147266,63,"size()"
? \<debugger\>
|2,1,1621147266,,"\\<debugger\\>"
??fromSt
|2,1,1621147266,63,"fromSt"
? \<cassert\>
|2,1,1621147266,,"\\<cassert\\>"
??split19k
|2,1,1621147266,63,"split19k"
? \<orderStats\>
|2,1,1621147266,,"\\<orderStats\\>"
??left
|2,1,1621147266,63,"left"
??left->in
|2,1,1621147266,63,"left->in"
??SplayTree
|2,1,1621147266,63,"SplayTree"
??inOrder
|2,1,1621147266,63,"inOrder"
??merged
|2,1,1621147266,63,"merged"
??process
|2,1,1621147266,63,"process"
??end
|2,1,1621147266,63,"end"
??merge
|2,1,1621147266,63,"merge"
??splay
|2,1,1621147266,63,"splay"
??fn
|2,1,1621147266,63,"fn"
??orderStats
|2,1,1621147266,63,"orderStats"
??T
|2,1,1621147266,63,"T"
??fromString
|2,1,1621147266,63,"fromString"
? \<SplayTree\>
|2,1,1621147266,,"\\<SplayTree\\>"
??delete
|2,1,1621147266,63,"delete"
??split
|2,1,1621147266,63,"split"
? \<split\>
|2,1,1621147266,,"\\<split\\>"
??delete(this)
|2,1,1621147266,63,"delete(this)"
??delete this
|2,1,1621147266,63,"delete this"
??DFS
|2,1,1621147266,63,"DFS"
? \<explore\>
|2,1,1621147266,,"\\<explore\\>"
??vector<list
|2,1,1621147266,63,"vector<list"
? vector<list
|2,1,1621147266,,"vector<list"
??explore
|2,1,1621147266,63,"explore"
??push_back
|2,1,1621147266,63,"push_back"
??filter
|2,1,1621147266,63,"filter"
? \<filter\>
|2,1,1621147266,,"\\<filter\\>"
? std::pair<long long, int>
|2,1,1621147266,,"std::pair<long long, int>"
??std::pair
|2,1,1621147266,63,"std::pair"
??continue
|2,1,1621147266,63,"continue"
?/h
|2,1,1621147266,47,"h"
?/incremen
|2,1,1621147266,47,"incremen"
? \<:Next\>
|2,1,1621147266,,"\\<:Next\\>"
? \<:next\>
|2,1,1621147266,,"\\<:next\\>"
? ;
|2,1,1621147266,,";"
??back
|2,1,1621147266,63,"back"
??int
|2,1,1621147266,63,"int"
??new
|2,1,1621147266,63,"new"
? \<back\>
|2,1,1621147266,,"\\<back\\>"
? \<tail\>
|2,1,1621147266,,"\\<tail\\>"
??Enter
|2,1,1621147266,63,"Enter"
? \<s\>
|2,1,1621147266,,"\\<s\\>"
??const
|2,1,1621147266,63,"const"
? \<sort\>
|2,1,1621147266,,"\\<sort\\>"
??key
|2,1,1621147266,63,"key"
? \<partition\>
|2,1,1621147266,,"\\<partition\\>"
??assert
|2,1,1621147266,63,"assert"
? \<swap\>
|2,1,1621147266,,"\\<swap\\>"
??std::cout 
|2,1,1621147266,63,"std::cout "
??partition
|2,1,1621147266,63,"partition"
??yo
|2,1,1621147266,63,"yo"
??sort
|2,1,1621147266,63,"sort"
??loop
|2,1,1621147266,63,"loop"
??9
|2,1,1621147266,63,"9"
??counter
|2,1,1621147266,63,"counter"
??parti
|2,1,1621147266,63,"parti"
??swap
|2,1,1621147266,63,"swap"
??data
|2,1,1621147266,63,"data"
??std::cout
|2,1,1621147266,63,"std::cout"
? \<clustering\>
|2,1,1621147266,,"\\<clustering\\>"
? \\
|2,1,1621147266,,"\\\\"
??D2
|2,1,1621147266,63,"D2"
? bfs
|2,1,1621147266,,"bfs"
??export
|2,1,1621147266,63,"export"
? s
|2,1,1621147266,,"s"
? sel
|2,1,1621147266,,"sel"
? And
|2,1,1621147266,,"And"
? x
|2,1,1621147266,,"x"
? zx
|2,1,1621147266,,"zx"
??Add16
|2,1,1621147266,63,"Add16"
? \<ng\>
|2,1,1621147266,,"\\<ng\\>"
? a.out: main.cpp
|2,1,1621147266,,"a.out: main.cpp"
??size_t
|2,1,1621147266,63,"size_t"
? \<Heap\>
|2,1,1621147266,,"\\<Heap\\>"
? \<heap\>
|2,1,1621147266,,"\\<heap\\>"
? \<getInput\>
|2,1,1621147266,,"\\<getInput\\>"
? \<verbose\>
|2,1,1621147266,,"\\<verbose\\>"
? size
|2,1,1621147266,,"size"
? SortedHeap
|2,1,1621147266,,"SortedHeap"
??size
|2,1,1621147266,63,"size"
??heapn
|2,1,1621147266,63,"heapn"
??heap
|2,1,1621147266,63,"heap"
??sifDown
|2,1,1621147266,63,"sifDown"
??siftDown
|2,1,1621147266,63,"siftDown"
??siftup
|2,1,1621147266,63,"siftup"
??debugger
|2,1,1621147266,63,"debugger"
??ChangePr
|2,1,1621147266,63,"ChangePr"
?/main
|2,1,1621147266,47,"main"
??visited
|2,1,1621147266,63,"visited"
? visited
|2,1,1621147266,,"visited"
? \<ChangePriority\>
|2,1,1621147266,,"\\<ChangePriority\\>"
? \<changePriority\>
|2,1,1621147266,,"\\<changePriority\\>"
??debugg
|2,1,1621147266,63,"debugg"
??deb
|2,1,1621147266,63,"deb"
??de
|2,1,1621147266,63,"de"
??max
|2,1,1621147266,63,"max"
??extract
|2,1,1621147266,63,"extract"
? \<pc\>
|2,1,1621147266,,"\\<pc\\>"
? \<PC\>
|2,1,1621147266,,"\\<PC\\>"
??loadA
|2,1,1621147266,63,"loadA"
??loadD
|2,1,1621147266,63,"loadD"
??jtl
|2,1,1621147266,63,"jtl"
? Hash
|2,1,1621147266,,"Hash"
??<
|2,1,1621147266,63,"<"
??>=
|2,1,1621147266,63,">="
??s
|2,1,1621147266,63,"s"
?/hash
|2,1,1621147266,47,"hash"
? \<hashtable\>
|2,1,1621147266,,"\\<hashtable\\>"
? \<HashTable\>
|2,1,1621147266,,"\\<HashTable\\>"
??class Hash
|2,1,1621147266,63,"class Hash"
??hash(
|2,1,1621147266,63,"hash("
? \<precompute\>
|2,1,1621147266,,"\\<precompute\\>"
??precompute
|2,1,1621147266,63,"precompute"
??ez_l
|2,1,1621147266,63,"ez_l"
??ez-life
|2,1,1621147266,63,"ez-life"
??file_list
|2,1,1621147266,63,"file_list"
? \<ConvertSymbols\>
|2,1,1621147266,,"\\<ConvertSymbols\\>"
??"M"
|2,1,1621147266,63,"\"M\""
??[1]
|2,1,1621147266,63,"[1]"
? \<file_name\>
|2,1,1621147266,,"\\<file_name\\>"
??hack
|2,1,1621147266,63,"hack"
??Handle
|2,1,1621147266,63,"Handle"
??hash
|2,1,1621147266,63,"hash"
??x_l
|2,1,1621147266,63,"x_l"
??getPow
|2,1,1621147266,63,"getPow"
? \<getPow\>
|2,1,1621147266,,"\\<getPow\\>"
??getHash
|2,1,1621147266,63,"getHash"
??Command
|2,1,1621147266,63,"Command"
? sp
|2,1,1621147266,,"sp"
??__init__
|2,1,1621147266,63,"__init__"
? \<write\>
|2,1,1621147266,,"\\<write\\>"
??else if
|2,1,1621147266,63,"else if"
??Aritm
|2,1,1621147266,63,"Aritm"
??PopCon
|2,1,1621147266,63,"PopCon"
?/temp
|2,1,1621147266,47,"temp"
??push
|2,1,1621147266,63,"push"
??main
|2,1,1621147266,63,"main"
??input_file_name
|2,1,1621147266,63,"input_file_name"
??os
|2,1,1621147266,63,"os"
??parser.
|2,1,1621147266,63,"parser."
??parser\.
|2,1,1621147266,63,"parser\\."
??commands
|2,1,1621147266,63,"commands"
? \<CommandPreprocessor\>
|2,1,1621147266,,"\\<CommandPreprocessor\\>"
? \<line\>
|2,1,1621147266,,"\\<line\\>"
??self.parser
|2,1,1621147266,63,"self.parser"
??current_file_full
|2,1,1621147266,63,"current_file_full"
??cmd2type
|2,1,1621147266,63,"cmd2type"
??current_filename
|2,1,1621147266,63,"current_filename"
??Parse
|2,1,1621147266,63,"Parse"
??directory
|2,1,1621147266,63,"directory"
??full_directory_
|2,1,1621147266,63,"full_directory_"
??rsplit
|2,1,1621147266,63,"rsplit"
??full_directory_path
|2,1,1621147266,63,"full_directory_path"
??full_path
|2,1,1621147266,63,"full_path"
??path_is_file
|2,1,1621147266,63,"path_is_file"
??full_out_filename
|2,1,1621147266,63,"full_out_filename"
??self.full_directory
|2,1,1621147266,63,"self.full_directory"
? \<cmd2type\>
|2,1,1621147266,,"\\<cmd2type\\>"
??'r'
|2,1,1621147266,63,"'r'"
??tst
|2,1,1621147266,63,"tst"
? \<full_file_path\>
|2,1,1621147266,,"\\<full_file_path\\>"
? \<commands\>
|2,1,1621147266,,"\\<commands\\>"
??po
|2,1,1621147266,63,"po"
??classmethod
|2,1,1621147266,63,"classmethod"
??foo
|2,1,1621147266,63,"foo"
??writePush
|2,1,1621147266,63,"writePush"
??write
|2,1,1621147266,63,"write"
??foldmethod
|2,1,1621147266,63,"foldmethod"
??Ad12
|2,1,1621147266,63,"Ad12"
??add12
|2,1,1621147266,63,"add12"
??call
|2,1,1621147266,63,"call"
? \<BasicLoop\>
|2,1,1621147266,,"\\<BasicLoop\\>"
??function
|2,1,1621147266,63,"function"
??Arith
|2,1,1621147266,63,"Arith"
??temp
|2,1,1621147266,63,"temp"
??this.func
|2,1,1621147266,63,"this.func"
? \<writeGoto\>
|2,1,1621147266,,"\\<writeGoto\\>"
??convertLabel
|2,1,1621147266,63,"convertLabel"
? \<convertLabel\>
|2,1,1621147266,,"\\<convertLabel\\>"
? \<convertIf\>
|2,1,1621147266,,"\\<convertIf\\>"
? \<convertGoto\>
|2,1,1621147266,,"\\<convertGoto\\>"
??rect
|2,1,1621147266,63,"rect"
??ret
|2,1,1621147266,63,"ret"
? \<return_address\>
|2,1,1621147266,,"\\<return_address\\>"
??Return
|2,1,1621147266,63,"Return"
??convertReturn
|2,1,1621147266,63,"convertReturn"
??Branch
|2,1,1621147266,63,"Branch"
??n_var
|2,1,1621147266,63,"n_var"
??Sys
|2,1,1621147266,63,"Sys"
??{
|2,1,1621147266,63,"{"
??}
|2,1,1621147266,63,"}"
??push n
|2,1,1621147266,63,"push n"
??/#
|2,1,1621147266,63,"/#"
??argument
|2,1,1621147266,63,"argument"
??Sys.init
|2,1,1621147266,63,"Sys.init"
??sys
|2,1,1621147266,63,"sys"
??function Sys.init 0
|2,1,1621147266,63,"function Sys.init 0"
??goto while
|2,1,1621147266,63,"goto while"
?/function sys
|2,1,1621147266,47,"function sys"
??0;JMP
|2,1,1621147266,63,"0;JMP"
??label
|2,1,1621147266,63,"label"
??pop
|2,1,1621147266,63,"pop"
?//
|2,1,1621147266,47,"/"
??convertCall
|2,1,1621147266,63,"convertCall"
? \<convertCall\>
|2,1,1621147266,,"\\<convertCall\\>"
? \<writeBootStrap\>
|2,1,1621147266,,"\\<writeBootStrap\\>"
?/sys.init$ret
|2,1,1621147266,47,"sys.init$ret"
??@sysinit
|2,1,1621147266,63,"@sysinit"
??sys.init
|2,1,1621147266,63,"sys.init"
? \<init\>
|2,1,1621147266,,"\\<init\\>"
? \<sys\>
|2,1,1621147266,,"\\<sys\\>"
? \<Sys\>
|2,1,1621147266,,"\\<Sys\\>"
??4
|2,1,1621147266,63,"4"
??Main.fibonacci
|2,1,1621147266,63,"Main.fibonacci"
??@Main.fibonacci$IF
|2,1,1621147266,63,"@Main.fibonacci$IF"
??@Main.fibonacci$IF_F
|2,1,1621147266,63,"@Main.fibonacci$IF_F"
??IF_FALSE
|2,1,1621147266,63,"IF_FALSE"
??.pop()
|2,1,1621147266,63,".pop()"
? \<fromCmd\>
|2,1,1621147266,,"\\<fromCmd\\>"
? \<CodeWriter\>
|2,1,1621147266,,"\\<CodeWriter\\>"
? circle
|2,1,1621147266,,"circle"
??static
|2,1,1621147266,63,"static"
??10
|2,1,1621147266,63,"10"
??100
|2,1,1621147266,63,"100"
??state
|2,1,1621147266,63,"state"
??initArray
|2,1,1621147266,63,"initArray"
?/setState
|2,1,1621147266,47,"setState"
??draw()
|2,1,1621147266,63,"draw()"
? \<setPos\>
|2,1,1621147266,,"\\<setPos\\>"
??changePos
|2,1,1621147266,63,"changePos"
? \<changePos\>
|2,1,1621147266,,"\\<changePos\\>"
??fill
|2,1,1621147266,63,"fill"
??get
|2,1,1621147266,63,"get"
??setPos
|2,1,1621147266,63,"setPos"
??getState
|2,1,1621147266,63,"getState"
??clear()
|2,1,1621147266,63,"clear()"
??clear
|2,1,1621147266,63,"clear"
??reset
|2,1,1621147266,63,"reset"
??checkSolved
|2,1,1621147266,63,"checkSolved"
? \<iostream\>
|2,1,1621147266,,"\\<iostream\\>"
? string
|2,1,1621147266,,"string"
?/string
|2,1,1621147266,47,"string"
??comp
|2,1,1621147266,63,"comp"
??ans
|2,1,1621147266,63,"ans"
??hou
|2,1,1621147266,63,"hou"
? \<comp\>
|2,1,1621147266,,"\\<comp\\>"
? var
|2,1,1621147266,,"var"
??Parser
|2,1,1621147266,63,"Parser"
??Node
|2,1,1621147266,63,"Node"
? \<inNode\>
|2,1,1621147266,,"\\<inNode\\>"
??top
|2,1,1621147266,63,"top"
??revers
|2,1,1621147266,63,"revers"
??store
|2,1,1621147266,63,"store"
? 0
|2,1,1621147266,,"0"
? \<bfs\>
|2,1,1621147266,,"\\<bfs\\>"
??q.end()
|2,1,1621147266,63,"q.end()"
??dfs
|2,1,1621147266,63,"dfs"
??parent
|2,1,1621147266,63,"parent"
??inNode
|2,1,1621147266,63,"inNode"
??disp
|2,1,1621147266,63,"disp"
? \<next\>
|2,1,1621147266,,"\\<next\\>"
??right
|2,1,1621147266,63,"right"
??find
|2,1,1621147266,63,"find"
??bfs
|2,1,1621147266,63,"bfs"
??insert
|2,1,1621147266,63,"insert"
??m
|2,1,1621147266,63,"m"
??game
|2,1,1621147266,63,"game"
??input
|2,1,1621147266,63,"input"
??string constant
|2,1,1621147266,63,"string constant"
??&lt
|2,1,1621147266,63,"&lt"
??let length
|2,1,1621147266,63,"let length"
? a
|2,1,1621147266,,"a"
??solve
|2,1,1621147266,63,"solve"
??\a
|2,1,1621147266,63,"\\a"
??list
|2,1,1621147266,63,"list"
??ipair
|2,1,1621147266,63,"ipair"
??wh
|2,1,1621147266,63,"wh"
??who
|2,1,1621147266,63,"who"
? long long
|2,1,1621147266,,"long long"
??long long
|2,1,1621147266,63,"long long"
??cout 
|2,1,1621147266,63,"cout "
??auto
|2,1,1621147266,63,"auto"
??open
|2,1,1621147266,63,"open"
? [nx][ny]
|2,1,1621147266,,"[nx][ny]"
? >>
|2,1,1621147266,,">>"
? ull
|2,1,1621147266,,"ull"
? \<comb\>
|2,1,1621147266,,"\\<comb\\>"
? );
|2,1,1621147266,,");"
? \<power\>
|2,1,1621147266,,"\\<power\\>"
?  
|2,1,1621147266,," "
??C
|2,1,1621147266,63,"C"
? 3
|2,1,1621147266,,"3"
? _3
|2,1,1621147266,,"_3"
? M
|2,1,1621147266,,"M"
??modInverse
|2,1,1621147266,63,"modInverse"
??comb
|2,1,1621147266,63,"comb"
??min
|2,1,1621147266,63,"min"
??eval
|2,1,1621147266,63,"eval"
? \<eval\>
|2,1,1621147266,,"\\<eval\\>"
? char * str
|2,1,1621147266,,"char * str"
? \<lower\>
|2,1,1621147266,,"\\<lower\\>"
? str[i]
|2,1,1621147266,,"str[i]"
? str\[i\]
|2,1,1621147266,,"str\\[i\\]"
??&str
|2,1,1621147266,63,"&str"
? &str
|2,1,1621147266,,"&str"
? void
|2,1,1621147266,,"void"
??origin
|2,1,1621147266,63,"origin"
??cout
|2,1,1621147266,63,"cout"
? 2
|2,1,1621147266,,"2"
? .\/a.out
|2,1,1621147266,,".\\/a.out"
? \<solve\>
|2,1,1621147266,,"\\<solve\\>"
? \<c\>
|2,1,1621147266,,"\\<c\\>"
? \<disp\>
|2,1,1621147266,,"\\<disp\\>"
? ,
|2,1,1621147266,,","
? big
|2,1,1621147266,,"big"
? small
|2,1,1621147266,,"small"
? '
|2,1,1621147266,,"'"
? \'
|2,1,1621147266,,"\\'"
? \â€˜
|2,1,1621147266,,"\\â€˜"
? â€˜
|2,1,1621147266,,"â€˜"
? â€™
|2,1,1621147266,,"â€™"
? convert
|2,1,1621147266,,"convert"
? \<convert\>
|2,1,1621147266,,"\\<convert\\>"
??print
|2,1,1621147266,63,"print"
? \<include\>
|2,1,1621147266,,"\\<include\\>"
? makepair
|2,1,1621147266,,"makepair"
? \<ull\>
|2,1,1621147266,,"\\<ull\\>"
? \.\/a\.out
|2,1,1621147266,,"\\.\\/a\\.out"
??emplace
|2,1,1621147266,63,"emplace"
? \<extractMin\>
|2,1,1621147266,,"\\<extractMin\\>"
??t
|2,1,1621147266,63,"t"
? \<array\>
|2,1,1621147266,,"\\<array\\>"
? \<find\>
|2,1,1621147266,,"\\<find\\>"
? \<count\>
|2,1,1621147266,,"\\<count\\>"
? j
|2,1,1621147266,,"j"
? \<countP\>
|2,1,1621147266,,"\\<countP\\>"
? i
|2,1,1621147266,,"i"
? \<n\>
|2,1,1621147266,,"\\<n\\>"
? \<quickSort\>
|2,1,1621147266,,"\\<quickSort\\>"
? \<mergeSort\>
|2,1,1621147266,,"\\<mergeSort\\>"
? prims
|2,1,1621147266,,"prims"
? Prims
|2,1,1621147266,,"Prims"
??count
|2,1,1621147266,63,"count"
??for
|2,1,1621147266,63,"for"
??while
|2,1,1621147266,63,"while"
??i++
|2,1,1621147266,63,"i++"
?/++
|2,1,1621147266,47,"++"
??unsigned
|2,1,1621147266,63,"unsigned"
??keywords
|2,1,1621147266,63,"keywords"
??keyword
|2,1,1621147266,63,"keyword"
??return
|2,1,1621147266,63,"return"
??dynamic
|2,1,1621147266,63,"dynamic"
? \<nsol\>
|2,1,1621147266,,"\\<nsol\\>"
? queue
|2,1,1621147266,,"queue"
??aho
|2,1,1621147266,63,"aho"
? 1
|2,1,1621147266,,"1"
? \<cp\>
|2,1,1621147266,,"\\<cp\\>"
? \<f\>
|2,1,1621147266,,"\\<f\\>"
? \<I\>
|2,1,1621147266,,"\\<I\\>"
? \<pow\>
|2,1,1621147266,,"\\<pow\\>"
??cp
|2,1,1621147266,63,"cp"
??exit
|2,1,1621147266,63,"exit"
??Aho-Corasick
|2,1,1621147266,63,"Aho-Corasick"
??>
|2,1,1621147266,63,">"
? data
|2,1,1621147266,,"data"
? \<testRabinKarpPatternSearch\>
|2,1,1621147266,,"\\<testRabinKarpPatternSearch\\>"
? \<parse\>
|2,1,1621147266,,"\\<parse\\>"
??tabs
|2,1,1621147266,63,"tabs"
??tab
|2,1,1621147266,63,"tab"
? \<.\>
|2,1,1621147266,,"\\<.\\>"
? .
|2,1,1621147266,,"."
?/*
|2,1,1621147266,47,"*"
? @$
|2,1,1621147266,,"@$"
??wv
|2,1,1621147266,63,"wv"
? \<:autocmd\>
|2,1,1621147266,,"\\<:autocmd\\>"
??jkkkkkkkkkk
|2,1,1621147266,63,"jkkkkkkkkkk"
? \<i\>
|2,1,1621147266,,"\\<i\\>"
??registers
|2,1,1621147266,63,"registers"
??-rv
|2,1,1621147266,63,"-rv"
??rv
|2,1,1621147266,63,"rv"
? \<-rv\>
|2,1,1621147266,,"\\<-rv\\>"
??bufnew
|2,1,1621147266,63,"bufnew"
??buff
|2,1,1621147266,63,"buff"
? \<viminfo-file\>
|2,1,1621147266,,"\\<viminfo-file\\>"
? \<session-file\>
|2,1,1621147266,,"\\<session-file\\>"
? eqns
|2,1,1621147266,,"eqns"
??:rv
|2,1,1621147266,63,":rv"
? \<k\>
|2,1,1621147266,,"\\<k\\>"

# Expression History (newest to oldest):
=100 * 50 + 10
|2,2,1621147266,,"100 * 50 + 10"
=100 * 50 + 20
|2,2,1621147266,,"100 * 50 + 20"
=10 * 20 + 5
|2,2,1621147266,,"10 * 20 + 5"
=p
|2,2,1621147266,,"p"

# Input Line History (newest to oldest):
@printf
|2,3,1621147266,,"printf"
@p class = root>
|2,3,1621147266,,"p class = root>"
@p class="hello world">
|2,3,1621147266,,"p class=\"hello world\">"
@depend
|2,3,1621147266,,"depend"
@build_depend>
|2,3,1621147266,,"build_depend>"
@exev_depend>
|2,3,1621147266,,"exev_depend>"
@depend>
|2,3,1621147266,,"depend>"
@buildtool_depend>
|2,3,1621147266,,"buildtool_depend>"
@exec_depend>
|2,3,1621147266,,"exec_depend>"
@member_of_group>
|2,3,1621147266,,"member_of_group>"
@p>
|2,3,1621147266,,"p>"
@[{y(es)},n(o),a(ll),q(uit)] y
|2,3,1621147266,,"[{y(es)},n(o),a(ll),q(uit)] y"
@print
|2,3,1621147266,,"print"
@list
|2,3,1621147266,,"list"
@dict
|2,3,1621147266,,"dict"

# Debug Line History (newest to oldest):

# Registers:
"0	CHAR	0
	main.c
|3,0,0,0,1,0,1621080293,"main.c"
""1	LINE	0
	:wv! ~/.vim/info/.cinfo.vim
|3,1,1,1,1,0,1621147258,":wv! ~/.vim/info/.cinfo.vim"
"2	LINE	0
	
|3,0,2,1,1,0,1621080338,""
"3	LINE	0
	
|3,0,3,1,1,0,1621080335,""
"4	LINE	0
	
|3,0,4,1,1,0,1621080314,""
"5	LINE	0
	
|3,0,5,1,1,0,1621080304,""
"6	LINE	0
	
|3,0,6,1,1,0,1621080302,""
"7	LINE	0
	
|3,0,7,1,1,0,1621080285,""
"8	LINE	0
	
|3,0,8,1,1,0,1621078518,""
"9	LINE	0
	#include<stdio.h>
	#include<stdlib.h>
	#include<limits.h>
	
	
	
	int main(void){
	
		return 0;
	}
|3,0,9,1,10,0,1621078515,"#include<stdio.h>","#include<stdlib.h>","#include<limits.h>","","","","int main(void){","","	return 0;","}"
"a	CHAR	0
	i €ýak
|3,0,10,0,1,0,1612342066,"i €ýak"
"b	CHAR	0
	i#include<stdio.h>#include<stdlib.h>#include<limits.h>int main(void){€ýaOretrnreturn 0;€ýak
|3,0,11,0,1,0,1621078513,"i#include<stdio.h>#include<stdlib.h>#include<limits.h>int main(void){€ýaOretrnreturn 0;€ýak"
"c	LINE	0
	#include<stdio.h>
	#include<stdlib.h>
	#include<limits.h>
	
	
	int main(void){
		return 0;
	}
	
	
|3,0,12,1,10,0,1620963634,"#include<stdio.h>","#include<stdlib.h>","#include<limits.h>","","","int main(void){","	return 0;","}","",""
"d	CHAR	0
	@b€ýa@t
|3,0,13,0,1,0,1621078122,"@b€ýa@t"
"e	CHAR	0
	$i&&€ýa
|3,0,14,0,1,0,1614340553,"$i&&€ýa"
"f	CHAR	0
	ggO/*File AneName: €ýa:put = let @" = ep€kbxpand("%")poDate of Creation: €ýa:put = explore("strftime("€kb'%c')kJoAuthor: Josiah Tan€kb€kb€kb*/€ýa
|3,0,15,0,1,0,1620986375,"ggO/*File AneName: €ýa:put = let @\" = ep€kbxpand(\"%\")poDate of Creation: €ýa:put = explore(\"strftime(\"€kb'%c')kJoAuthor: Josiah Tan€kb€kb€kb*/€ýa"
"g	CHAR	0
	i#ifndef €ýa:let @" ex€kb€kb=expand("%")pF.r_viWUviwyo#define €ýapo€ýaG10o€ýao#endif€ýa9k
|3,0,16,0,1,0,1621079858,"i#ifndef €ýa:let @\" ex€kb€kb=expand(\"%\")pF.r_viWUviwyo#define €ýapo€ýaG10o€ýao#endif€ýa9k"
"h	LINE	0
	ggO/*File Name: €ýa:let @l€kb" = expand("%")poDatw€kbe of Cration€kl€kl€kl€kl€kle€ýaA: €ýa:put = strftime('%c')kJoAuthor: Josiah TanDescription: €kb€kb€kb*/€ýa
|3,0,17,1,1,0,1621078907,"ggO/*File Name: €ýa:let @l€kb\" = expand(\"%\")poDatw€kbe of Cration€kl€kl€kl€kl€kle€ýaA: €ýa:put = strftime('%c')kJoAuthor: Josiah TanDescription: €kb€kb€kb*/€ýa"
"i	CHAR	0
	Sfor (int i=0;i<n;i++){€ýaO€ýa
|3,0,18,0,1,0,1620986139,"Sfor (int i=0;i<n;i++){€ýaO€ýa"
"j	CHAR	0
	Sfor (int j=0;j<m;j++){€ýaO€ýa
|3,0,19,0,1,0,1620986173,"Sfor (int j=0;j<m;j++){€ýaO€ýa"
"l	CHAR	0
	f,i: Ar€kb€ýal
|3,0,21,0,1,0,1613564205,"f,i: Ar€kb€ýal"
"m	CHAR	0
	:tabnew Mae€kbkei€kbfiletabnew Makefile:%diall: ./a.outcat 1.in | ./a.ou€kb€kbout./a.out: main.cpp€kb€kbg++ mainc€kb.cp€kb€ýa
|3,0,22,0,1,0,1620986862,":tabnew Mae€kbkei€kbfiletabnew Makefile:%diall: ./a.outcat 1.in | ./a.ou€kb€kbout./a.out: main.cpp€kb€kbg++ mainc€kb.cp€kb€ýa"
"n	LINE	0
	Josiah Tan
|3,0,23,1,1,0,1620984417,"Josiah Tan"
"p	LINE	0
	#include<iostream>
	#include<vector>
	#include<climits>
	
	
	int main(void){
		return 0;
	}
	
|3,0,25,1,9,0,1620959626,"#include<iostream>","#include<vector>","#include<climits>","","","int main(void){","	return 0;","}",""
"q	CHAR	0
	igoodbye world€ýa
|3,0,26,0,1,0,1621002658,"igoodbye world€ýa"
"r	CHAR	0
	:!gcc % && ./a.out
|3,0,27,0,1,0,1621074808,":!gcc % && ./a.out"
"s	CHAR	0
	f,geysiw"f,
|3,0,28,0,1,0,1613478510,"f,geysiw\"f,"
"t	CHAR	0
	Sfor(€kb (int t-0€kb€kb=0;t<T;t++){€ýaO€ýa
|3,0,29,0,1,0,1621080334,"Sfor(€kb (int t-0€kb€kb=0;t<T;t++){€ýaO€ýa"
"u	CHAR	0
	^veUk
|3,0,30,0,1,0,1613212860,"^veUk"
"v@	LINE	0
	:wv! ~/.vim/info/.cinfo.vim
|3,2,31,1,1,0,1621147255,":wv! ~/.vim/info/.cinfo.vim"
"w	CHAR	0
	thii€kbti€kb€kbthis is a program that copies registtakprints what is in register w t€kb€kb€kbq twice€ýa@w@q@q
|3,0,32,0,1,0,1620987224,"thii€kbti€kb€kbthis is a program that copies registtakprints what is in register w t€kb€kb€kbq twice€ýa@w@q@q"
"-	CHAR	0
	info€kb€kb€kb€kb
|3,0,36,0,1,0,1621076321,"info€kb€kb€kb€kb"

# global variables:

# File marks:
'P  2  20  ~/Desktop/josiah_folder/nand2tetris/projects/07/StackArithmetic/SimpleAdd/SimpleAdd.asm
|4,80,2,20,1613618169,"~/Desktop/josiah_folder/nand2tetris/projects/07/StackArithmetic/SimpleAdd/SimpleAdd.asm"
'V  43  0  ~/.vimrc
|4,86,43,0,1612532244,"~/.vimrc"
'0  27  0  ~/Desktop/josiah_folder/vim/vimvscode/main.c
|4,48,27,0,1621147269,"~/Desktop/josiah_folder/vim/vimvscode/main.c"
'1  30  0  ~/Desktop/josiah_folder/vim/vimvscode/main.c
|4,49,30,0,1621147258,"~/Desktop/josiah_folder/vim/vimvscode/main.c"
'2  30  0  ~/Desktop/josiah_folder/vim/vimvscode/main.c
|4,50,30,0,1621147258,"~/Desktop/josiah_folder/vim/vimvscode/main.c"
'3  1  0  ~/Desktop/josiah_folder/vim/vimvscode/main.py
|4,51,1,0,1621147175,"~/Desktop/josiah_folder/vim/vimvscode/main.py"
'4  1  0  ~/Desktop/josiah_folder/vim/vimvscode/main.py
|4,52,1,0,1621147175,"~/Desktop/josiah_folder/vim/vimvscode/main.py"
'5  1  0  ~/Desktop/josiah_folder/vim/vimvscode/main.py
|4,53,1,0,1621147175,"~/Desktop/josiah_folder/vim/vimvscode/main.py"
'6  1  0  ~/Desktop/josiah_folder/vim/vimvscode/main.py
|4,54,1,0,1621147175,"~/Desktop/josiah_folder/vim/vimvscode/main.py"
'7  1  0  ~/Desktop/josiah_folder/vim/vimvscode/main.py
|4,55,1,0,1621147175,"~/Desktop/josiah_folder/vim/vimvscode/main.py"
'8  1  0  ~/Desktop/josiah_folder/vim/vimvscode/main.py
|4,56,1,0,1621147175,"~/Desktop/josiah_folder/vim/vimvscode/main.py"
'9  1  0  ~/Desktop/josiah_folder/vim/vimvscode/main.py
|4,57,1,0,1621147175,"~/Desktop/josiah_folder/vim/vimvscode/main.py"

# Jumplist (newest first):
-'  27  0  ~/Desktop/josiah_folder/vim/vimvscode/main.c
|4,39,27,0,1621147269,"~/Desktop/josiah_folder/vim/vimvscode/main.c"
-'  1  0  ~/Desktop/josiah_folder/vim/vimvscode/main.py
|4,39,1,0,1621147266,"~/Desktop/josiah_folder/vim/vimvscode/main.py"
-'  30  0  ~/Desktop/josiah_folder/vim/vimvscode/main.c
|4,39,30,0,1621147258,"~/Desktop/josiah_folder/vim/vimvscode/main.c"
-'  27  0  ~/Desktop/josiah_folder/vim/vimvscode/main.py
|4,39,27,0,1621147164,"~/Desktop/josiah_folder/vim/vimvscode/main.py"
-'  28  0  ~/Desktop/josiah_folder/vim/vimvscode/main.py
|4,39,28,0,1621147132,"~/Desktop/josiah_folder/vim/vimvscode/main.py"
-'  2  0  ~/Desktop/josiah_folder/vim/vimvscode/main.py
|4,39,2,0,1621147115,"~/Desktop/josiah_folder/vim/vimvscode/main.py"
-'  23  21  ~/Desktop/josiah_folder/vim/vimvscode/main.py
|4,39,23,21,1621146898,"~/Desktop/josiah_folder/vim/vimvscode/main.py"
-'  2  0  ~/Desktop/josiah_folder/vim/vimvscode/main.c
|4,39,2,0,1621146848,"~/Desktop/josiah_folder/vim/vimvscode/main.c"
-'  1  0  ~/Desktop/josiah_folder/vim/vimvscode/mian.c
|4,39,1,0,1621146831,"~/Desktop/josiah_folder/vim/vimvscode/mian.c"
-'  23  3  ~/Desktop/josiah_folder/vim/vimvscode/main.c
|4,39,23,3,1621146812,"~/Desktop/josiah_folder/vim/vimvscode/main.c"
-'  1  0  ~/Desktop/josiah_folder/vim/vimvscode/main.c
|4,39,1,0,1621146811,"~/Desktop/josiah_folder/vim/vimvscode/main.c"
-'  22  4  ~/Desktop/josiah_folder/vim/vimvscode/main.c
|4,39,22,4,1621146811,"~/Desktop/josiah_folder/vim/vimvscode/main.c"
-'  21  5  ~/Desktop/josiah_folder/vim/vimvscode/main.c
|4,39,21,5,1621146808,"~/Desktop/josiah_folder/vim/vimvscode/main.c"
-'  69  0  ~/.vim/vimrc
|4,39,69,0,1621146794,"~/.vim/vimrc"
-'  59  0  ~/.vim/vimrc
|4,39,59,0,1621146785,"~/.vim/vimrc"

# History of marks within files (newest to oldest):

> ~/Desktop/josiah_folder/vim/vimvscode/main.c
	*	1621147269	0
	"	27	0
	.	31	0
	+	26	9
	+	16	0
	+	7	0
	+	16	17
	+	17	23
	+	18	24
	+	19	25
	+	20	26
	+	21	0
	+	20	0
	+	21	27
	+	1	0
	+	29	0
	+	31	0
	+	26	9
	+	16	0
	+	7	0
	+	16	17
	+	17	23
	+	18	24
	+	19	25
	+	20	26
	+	21	0
	+	20	0
	+	21	27
	+	1	0
	+	29	0
	+	31	0

> ~/Desktop/josiah_folder/vim/vimvscode/main.py
	*	1621147175	0
	"	1	0
	.	28	0
	+	23	21
	+	1	0
	+	26	0
	+	28	0
	+	10	0
	+	15	9
	+	14	10
	+	18	4
	+	18	21
	+	20	16
	+	21	0
	+	23	4
	+	23	21
	+	1	0
	+	26	0
	+	28	0
	+	10	0
	+	15	9
	+	14	10
	+	18	4
	+	18	21
	+	20	16
	+	21	0
	+	23	4
	+	23	21
	+	1	0
	+	26	0
	+	28	0
	+	10	0
	+	15	9
	+	14	10
	+	18	4
	+	18	21
	+	20	16
	+	21	0
	+	23	4
	+	23	21
	+	1	0
	+	26	0
	+	28	0
	+	10	0
	+	15	9
	+	14	10
	+	18	4
	+	18	21
	+	20	16
	+	21	0
	+	23	4
	+	23	21
	+	1	0
	+	26	0
	+	28	0
	+	10	0
	+	15	9
	+	14	10
	+	18	4
	+	18	21
	+	20	16
	+	21	0
	+	23	4
	+	23	21
	+	1	0
	+	26	0
	+	28	0
	+	10	0
	+	15	9
	+	14	10
	+	18	4
	+	18	21
	+	20	16
	+	21	0
	+	23	4
	+	23	21
	+	1	0
	+	26	0
	+	28	0
	+	10	0
	+	15	9
	+	14	10
	+	18	4
	+	18	21
	+	20	16
	+	21	0
	+	23	4
	+	23	21
	+	1	0
	+	26	0
	+	28	0
	+	10	0
	+	15	9
	+	14	10
	+	18	4
	+	18	21
	+	20	16
	+	21	0
	+	23	4
	+	23	21
	+	1	0
	+	26	0
	+	28	0

> ~/Desktop/josiah_folder/vim/vimvscode/module.h
	*	1621147020	0
	"	13	0
	.	13	0
	+	1	8
	+	1	5
	+	1	0
	+	1	8
	+	1	0
	+	13	0
	+	1	8
	+	1	5
	+	1	0
	+	1	8
	+	1	0
	+	13	0
