# This viminfo file was generated by Vim 8.1.
# You may edit it if you are careful!

# Viminfo version
|1,4

# Value of 'encoding' when this file was written
*encoding=utf-8


# hlsearch on (H) or off (h):
~h
# Last Search Pattern:
~MSle0~/registers

# Last Substitute Search Pattern:
~MSle0&.

# Last Substitute String:
$

# Command Line History (newest to oldest):
:s/\<ab\>/a/g
|2,0,1621147014,,"s/\\<ab\\>/a/g"
:s/\<cd\>/b/g
|2,0,1621147014,,"s/\\<cd\\>/b/g"
:s/a/ab/g
|2,0,1621147014,,"s/a/ab/g"
:s/\<b\>/cd/g
|2,0,1621147014,,"s/\\<b\\>/cd/g"
:vsplit intro.txt
|2,0,1621147014,,"vsplit intro.txt"
:%s/hello/goodbye/g
|2,0,1621147014,,"%s/hello/goodbye/g"
:vsplit main.c
|2,0,1621147014,,"vsplit main.c"
:s/\<j\>/k/g
|2,0,1621147014,,"s/\\<j\\>/k/g"
:tabnew mod.h
|2,0,1621147014,,"tabnew mod.h"
:tabf main.py
|2,0,1621147014,,"tabf main.py"
:! cp ~/.cinfo.vim ~/.cppinfo.vim
|2,0,1621147014,,"! cp ~/.cinfo.vim ~/.cppinfo.vim"
:%s/;/,/gc
|2,0,1621147014,,"%s/;/,/gc"
:w
|2,0,1621147014,,"w"
:reg d
|2,0,1621147014,,"reg d"
:tabm2
|2,0,1621147014,,"tabm2"
:wv! ~/.hinfo.vim
|2,0,1621147014,,"wv! ~/.hinfo.vim"
:wv ~/.pyinfo.vim
|2,0,1621147014,,"wv ~/.pyinfo.vim"
:s/hey/Hey/g
|2,0,1621147014,,"s/hey/Hey/g"
:!gcc % && ./a.out
|2,0,1621147014,,"!gcc % && ./a.out"
:!gcc main.c
|2,0,1621147014,,"!gcc main.c"
:!make % && ./a.out
|2,0,1621147014,,"!make % && ./a.out"
:!g++ % && ./a.out
|2,0,1621147014,,"!g++ % && ./a.out"
:rv! ~/.pyinfo.vim
|2,0,1621147014,,"rv! ~/.pyinfo.vim"
:tab solve.py
|2,0,1621147014,,"tab solve.py"
:tabf solver.py
|2,0,1621147014,,"tabf solver.py"
:tabf solve.py
|2,0,1621147014,,"tabf solve.py"
:help beffer
|2,0,1621147014,,"help beffer"
:help BufnewFile
|2,0,1621147014,,"help BufnewFile"
:help buffer
|2,0,1621147014,,"help buffer"
:help tabf
|2,0,1621147014,,"help tabf"
:tabf ~./
|2,0,1621147014,,"tabf ~./"
:! cp ~/.cinfo.vim ~/.hinfo.vim
|2,0,1621147014,,"! cp ~/.cinfo.vim ~/.hinfo.vim"
:tabf module.h
|2,0,1621147014,,"tabf module.h"
:t
|2,0,1621147014,,"t"
:reg 
|2,0,1621147014,,"reg "
:help Session
|2,0,1621147014,,"help Session"
:python3 %
|2,0,1621147014,,"python3 %"
:!python3 %
|2,0,1621147014,,"!python3 %"
:wv! ~/.pyinfo.vim
|2,0,1621147014,,"wv! ~/.pyinfo.vim"
:wv! ~/.cinfo.vim
|2,0,1621147014,,"wv! ~/.cinfo.vim"
:e
|2,0,1621147014,,"e"
:wv!
|2,0,1621147014,,"wv!"
:wv ~/.cinfo.vim
|2,0,1621147014,,"wv ~/.cinfo.vim"
:tabf ~/.cinfo.vim
|2,0,1621147014,,"tabf ~/.cinfo.vim"
:q
|2,0,1621147014,,"q"
:scripnames
|2,0,1621147014,,"scripnames"
:%y*
|2,0,1621147014,,"%y*"
:checkhealth
|2,0,1621147014,,"checkhealth"
:Helptags
|2,0,1621147014,,"Helptags"
:tabnew first_vim.py
|2,0,1621147014,,"tabnew first_vim.py"
:version
|2,0,1621147014,,"version"
:set wrap
|2,0,1621147014,,"set wrap"
:set breakindent
|2,0,1621147014,,"set breakindent"
:set formatoptions=l
|2,0,1621147014,,"set formatoptions=l"
:set lbr
|2,0,1621147014,,"set lbr"
:foldmethod=syntax
|2,0,1621147014,,"foldmethod=syntax"
:set foldmethod=syntax
|2,0,1621147014,,"set foldmethod=syntax"
:help folding
|2,0,1621147014,,"help folding"
:w !python
|2,0,1621147014,,"w !python"
:w !python3
|2,0,1621147014,,"w !python3"
:tabnew subscriber_member_function2.cpp
|2,0,1621147014,,"tabnew subscriber_member_function2.cpp"
:tabf ../
|2,0,1621147014,,"tabf ../"
:tabf ../CMakeLists.txt
|2,0,1621147014,,"tabf ../CMakeLists.txt"
:h find
|2,0,1621147014,,"h find"
:h expandtab
|2,0,1621147014,,"h expandtab"
:set expandtab 2
|2,0,1621147014,,"set expandtab 2"
:set expandtab=2
|2,0,1621147014,,"set expandtab=2"
:vim ~/.vimrc
|2,0,1621147014,,"vim ~/.vimrc"
:set shiftwidth=4
|2,0,1621147014,,"set shiftwidth=4"
:h tabstop
|2,0,1621147014,,"h tabstop"
:h shiftwidth()
|2,0,1621147014,,"h shiftwidth()"
:h shiftwidth
|2,0,1621147014,,"h shiftwidth"
:findf ~/.vimrc
|2,0,1621147014,,"findf ~/.vimrc"
:tabf CMakeLists.txt
|2,0,1621147014,,"tabf CMakeLists.txt"
:tabf ..
|2,0,1621147014,,"tabf .."
:tabnew src/publish_address_book.cpp
|2,0,1621147014,,"tabnew src/publish_address_book.cpp"
:tabf package.xml
|2,0,1621147014,,"tabf package.xml"
:tabf msg/AddressBook.msg
|2,0,1621147014,,"tabf msg/AddressBook.msg"
:tabf src/publish_address_book.cpp
|2,0,1621147014,,"tabf src/publish_address_book.cpp"
:s/MAX/MIN/g
|2,0,1621147014,,"s/MAX/MIN/g"
:set tabstop=4
|2,0,1621147014,,"set tabstop=4"
:set tabstop=2
|2,0,1621147014,,"set tabstop=2"
:set shiftwidth=2
|2,0,1621147014,,"set shiftwidth=2"
:tabf ../*4/*.cpp
|2,0,1621147014,,"tabf ../*4/*.cpp"
:%s/R/
|2,0,1621147014,,"%s/R/"
:%s/R/v/gc
|2,0,1621147014,,"%s/R/v/gc"
:set paste
|2,0,1621147014,,"set paste"
:set nopaste
|2,0,1621147014,,"set nopaste"
:s/v/root/g
|2,0,1621147014,,"s/v/root/g"
:s/v/T->root/g
|2,0,1621147014,,"s/v/T->root/g"
:tabf ../4_set_range_sum/set_range_sum.cpp
|2,0,1621147014,,"tabf ../4_set_range_sum/set_range_sum.cpp"
:%s/vector<list/list<list/gc
|2,0,1621147014,,"%s/vector<list/list<list/gc"
:wqwa
|2,0,1621147014,,"wqwa"
:Wq
|2,0,1621147014,,"Wq"
:s/std::pair<long long, int>/ipair/gc
|2,0,1621147014,,"s/std::pair<long long, int>/ipair/gc"
:scriptnames
|2,0,1621147014,,"scriptnames"
:wq!
|2,0,1621147014,,"wq!"
:w!
|2,0,1621147014,,"w!"
:tabf /usr/share/vim/vimrc
|2,0,1621147014,,"tabf /usr/share/vim/vimrc"
:h next
|2,0,1621147014,,"h next"
:mksession sess.vim
|2,0,1621147014,,"mksession sess.vim"
:tabf ./sess.vim
|2,0,1621147014,,"tabf ./sess.vim"
:Vtabnew hello.cpp
|2,0,1621147014,,"Vtabnew hello.cpp"
:split file2
|2,0,1621147014,,"split file2"
:hsplit hello.cpp
|2,0,1621147014,,"hsplit hello.cpp"
:vsplit yo.cpp
|2,0,1621147014,,"vsplit yo.cpp"
:!man cout
|2,0,1621147014,,"!man cout"
:!man std::cout 
|2,0,1621147014,,"!man std::cout "
:!man vim
|2,0,1621147014,,"!man vim"
:tabf ~/.vim/
|2,0,1621147014,,"tabf ~/.vim/"
:tabf /etc/vim/vimrc
|2,0,1621147014,,"tabf /etc/vim/vimrc"
:tabf make
|2,0,1621147014,,"tabf make"
:make test2
|2,0,1621147014,,"make test2"
:make test3
|2,0,1621147014,,"make test3"
:mkae
|2,0,1621147014,,"mkae"
:%s/c/
|2,0,1621147014,,"%s/c/"
:source
|2,0,1621147014,,"source"
:make test
|2,0,1621147014,,"make test"
:male
|2,0,1621147014,,"male"
:mae
|2,0,1621147014,,"mae"
:ake
|2,0,1621147014,,"ake"
:s/i/x/gc
|2,0,1621147014,,"s/i/x/gc"
:tabnew 3.in
|2,0,1621147014,,"tabnew 3.in"
:make 3
|2,0,1621147014,,"make 3"
:tabnew 4.in
|2,0,1621147014,,"tabnew 4.in"
:make 4
|2,0,1621147014,,"make 4"
:tabnew 5.in
|2,0,1621147014,,"tabnew 5.in"
:make 5
|2,0,1621147014,,"make 5"
:source S
|2,0,1621147014,,"source S"
:tabnew 1.in Makefile -p
|2,0,1621147014,,"tabnew 1.in Makefile -p"
:make1
|2,0,1621147014,,"make1"
:tabf Session.vim
|2,0,1621147014,,"tabf Session.vim"
:ls
|2,0,1621147014,,"ls"
:cd ..
|2,0,1621147014,,"cd .."
:time
|2,0,1621147014,,"time"
:type -a time
|2,0,1621147014,,"type -a time"
:mksession prim.vim
|2,0,1621147014,,"mksession prim.vim"
:tabf 1.in 2.in
|2,0,1621147014,,"tabf 1.in 2.in"
:source prim.vim
|2,0,1621147014,,"source prim.vim"
:make all
|2,0,1621147014,,"make all"
:%s/\\/ /gc
|2,0,1621147014,,"%s/\\\\/ /gc"
:make prim
|2,0,1621147014,,"make prim"
:amke
|2,0,1621147014,,"amke"
:%s/bfs/dfs/gc
|2,0,1621147014,,"%s/bfs/dfs/gc"
:! HardwareSimulator And.tst
|2,0,1621147014,,"! HardwareSimulator And.tst"
:tabf Not.hdl
|2,0,1621147014,,"tabf Not.hdl"
:! HardwareSimulator Or.tst
|2,0,1621147014,,"! HardwareSimulator Or.tst"
:! HardwareSimulator Xor.tst
|2,0,1621147014,,"! HardwareSimulator Xor.tst"
:s/s/sel/g
|2,0,1621147014,,"s/s/sel/g"
:! HardwareSimulator Mux.tst
|2,0,1621147014,,"! HardwareSimulator Mux.tst"
:s/sel/in/g
|2,0,1621147014,,"s/sel/in/g"
:! HardwareSimulator DMux.tst
|2,0,1621147014,,"! HardwareSimulator DMux.tst"
:! HardwareSimulator Not16.tst
|2,0,1621147014,,"! HardwareSimulator Not16.tst"
:!HardwareSimulator And.tst
|2,0,1621147014,,"!HardwareSimulator And.tst"
:!HardwareSimulator Or16.tst
|2,0,1621147014,,"!HardwareSimulator Or16.tst"
:!HardwareSimulator And16.tst
|2,0,1621147014,,"!HardwareSimulator And16.tst"
:tabf Mux.hdl
|2,0,1621147014,,"tabf Mux.hdl"
:!HardwareSimulator Mux16.tst
|2,0,1621147014,,"!HardwareSimulator Mux16.tst"
:tabf Or.hdl
|2,0,1621147014,,"tabf Or.hdl"
:find
|2,0,1621147014,,"find"
:! HardwareSimulator Mux16.tst
|2,0,1621147014,,"! HardwareSimulator Mux16.tst"
:tabf Mux16.hdl
|2,0,1621147014,,"tabf Mux16.hdl"
:tabf Mux4Way16.cmp
|2,0,1621147014,,"tabf Mux4Way16.cmp"
:tabf Mux4Way16.out
|2,0,1621147014,,"tabf Mux4Way16.out"
:! HardwareSimulator Mux4Way16.tst
|2,0,1621147014,,"! HardwareSimulator Mux4Way16.tst"
:! HardwareSimulator Mux8Way16.tst
|2,0,1621147014,,"! HardwareSimulator Mux8Way16.tst"
:! HardwareSimulator DMux4Way.tst
|2,0,1621147014,,"! HardwareSimulator DMux4Way.tst"
:tabf Mux8Way16.hdl
|2,0,1621147014,,"tabf Mux8Way16.hdl"
:tabnew Xor16.hdl
|2,0,1621147014,,"tabnew Xor16.hdl"
:%s/And/Xor/gc
|2,0,1621147014,,"%s/And/Xor/gc"
:! HardwareSimulator DMux8Way.tst
|2,0,1621147014,,"! HardwareSimulator DMux8Way.tst"
:s/x/y/g
|2,0,1621147014,,"s/x/y/g"
:s/zx/f/g
|2,0,1621147014,,"s/zx/f/g"
:tabf Add16.hdl
|2,0,1621147014,,"tabf Add16.hdl"
:! HardwareSimulator Add16.hdl
|2,0,1621147014,,"! HardwareSimulator Add16.hdl"
:! HardwareSimulator Add16.tst
|2,0,1621147014,,"! HardwareSimulator Add16.tst"
:! HardwareSimulator Or8Way.hdl
|2,0,1621147014,,"! HardwareSimulator Or8Way.hdl"
:! HardwareSimulator Or8Way.tst
|2,0,1621147014,,"! HardwareSimulator Or8Way.tst"
:! HardwareSimulator ALU.tst
|2,0,1621147014,,"! HardwareSimulator ALU.tst"
:edit main.cpp
|2,0,1621147014,,"edit main.cpp"
:make 1
|2,0,1621147014,,"make 1"
:source Makefile
|2,0,1621147014,,"source Makefile"
:make 1.ini
|2,0,1621147014,,"make 1.ini"
:%s/size/sz/gc
|2,0,1621147014,,"%s/size/sz/gc"
:make !.in
|2,0,1621147014,,"make !.in"
:%s/SortedHeap/sortedHeap/g
|2,0,1621147014,,"%s/SortedHeap/sortedHeap/g"
:make 1.n
|2,0,1621147014,,"make 1.n"
:tabnew reading.cpp
|2,0,1621147014,,"tabnew reading.cpp"
:tabf values.h
|2,0,1621147014,,"tabf values.h"
:tabf reading.cpp
|2,0,1621147014,,"tabf reading.cpp"
:! g++ reading.cpp && cat 1.in | ./a.out
|2,0,1621147014,,"! g++ reading.cpp && cat 1.in | ./a.out"
:%s/visited/dist/g/c
|2,0,1621147014,,"%s/visited/dist/g/c"
:%s/visited/dist/gc
|2,0,1621147014,,"%s/visited/dist/gc"
:! g++ main.cpp && cat 1.in | ./a.out
|2,0,1621147014,,"! g++ main.cpp && cat 1.in | ./a.out"
:! HardwareSimulator Bit.hdl
|2,0,1621147014,,"! HardwareSimulator Bit.hdl"
:! HardwareSimulator Bit.tst
|2,0,1621147014,,"! HardwareSimulator Bit.tst"
:! HardwareSimulator Register.tst
|2,0,1621147014,,"! HardwareSimulator Register.tst"
:! HardwareSimulator RAM8.tst
|2,0,1621147014,,"! HardwareSimulator RAM8.tst"
:tabf Register.hdl
|2,0,1621147014,,"tabf Register.hdl"
:tabf Bit.cmp
|2,0,1621147014,,"tabf Bit.cmp"
:tabf Bit.hdl
|2,0,1621147014,,"tabf Bit.hdl"
:ta
|2,0,1621147014,,"ta"
:tabf RAM64.hdl
|2,0,1621147014,,"tabf RAM64.hdl"
:! HardwareSimulator RAM64.tst
|2,0,1621147014,,"! HardwareSimulator RAM64.tst"
:tab ~/.vimrc
|2,0,1621147014,,"tab ~/.vimrc"
:! HardwareSimulator RAM512.tst
|2,0,1621147014,,"! HardwareSimulator RAM512.tst"
:tabf RAM4K.hdl
|2,0,1621147014,,"tabf RAM4K.hdl"
:! HardwareSimulator RAM4K.tst
|2,0,1621147014,,"! HardwareSimulator RAM4K.tst"
:tabf RAM16K.hdl
|2,0,1621147014,,"tabf RAM16K.hdl"
:! HardwareSimulator RAM16K.tst
|2,0,1621147014,,"! HardwareSimulator RAM16K.tst"
:tabf .
|2,0,1621147014,,"tabf ."
:! HardwareSimulator PC.tst
|2,0,1621147014,,"! HardwareSimulator PC.tst"
:tabf Fill.tst
|2,0,1621147014,,"tabf Fill.tst"
:tabf *.tst
|2,0,1621147014,,"tabf *.tst"
:tabf FillAutomatic.tst
|2,0,1621147014,,"tabf FillAutomatic.tst"
:Q!
|2,0,1621147014,,"Q!"
:! HardwareSimulator CPU.tst
|2,0,1621147014,,"! HardwareSimulator CPU.tst"
:! HardwareSimulator Memory.tst
|2,0,1621147014,,"! HardwareSimulator Memory.tst"
:tabf CPU.hdl
|2,0,1621147014,,"tabf CPU.hdl"
:tabf Memory.hdl
|2,0,1621147014,,"tabf Memory.hdl"
:! HardwareSimulator Computer.tst
|2,0,1621147014,,"! HardwareSimulator Computer.tst"
:! HardwareSimulator
|2,0,1621147014,,"! HardwareSimulator"
:%s/Hash/HashTable/gc
|2,0,1621147014,,"%s/Hash/HashTable/gc"
:! HardwareSimulator Mult.tst
|2,0,1621147014,,"! HardwareSimulator Mult.tst"
:make 2.in
|2,0,1621147014,,"make 2.in"
:! g++ main.cpp && cat 2.in | ./a.out
|2,0,1621147014,,"! g++ main.cpp && cat 2.in | ./a.out"
:! g++ main.cpp && ./a.out
|2,0,1621147014,,"! g++ main.cpp && ./a.out"
:! python3 Assembler.py
|2,0,1621147014,,"! python3 Assembler.py"
:find Makefile
|2,0,1621147014,,"find Makefile"
:mks
|2,0,1621147014,,"mks"
:make pong.asm
|2,0,1621147014,,"make pong.asm"
:make add.asm
|2,0,1621147014,,"make add.asm"
:make max
|2,0,1621147014,,"make max"
:make rect
|2,0,1621147014,,"make rect"
:ma
|2,0,1621147014,,"ma"
:make sum
|2,0,1621147014,,"make sum"
:make pong
|2,0,1621147014,,"make pong"
:! ls -la
|2,0,1621147014,,"! ls -la"
:! make rect
|2,0,1621147014,,"! make rect"
:tabf rect/Rect.hack
|2,0,1621147014,,"tabf rect/Rect.hack"
:tabf rect/cmp.hack
|2,0,1621147014,,"tabf rect/cmp.hack"
:tabnew rect/cmp.hack
|2,0,1621147014,,"tabnew rect/cmp.hack"
:! diff rect/Rect.hack rect/cmp.hack
|2,0,1621147014,,"! diff rect/Rect.hack rect/cmp.hack"
:tabf add/Add.hack
|2,0,1621147014,,"tabf add/Add.hack"
:tabnew add/cmp.hack
|2,0,1621147014,,"tabnew add/cmp.hack"
:! diff add/Add.hack add/cmp.hack
|2,0,1621147014,,"! diff add/Add.hack add/cmp.hack"
:! make max
|2,0,1621147014,,"! make max"
:tabf max/Max.hack
|2,0,1621147014,,"tabf max/Max.hack"
:tabnew max/cmp.hack
|2,0,1621147014,,"tabnew max/cmp.hack"
:! diff max/Max.hack max/cmp.hack
|2,0,1621147014,,"! diff max/Max.hack max/cmp.hack"
:! make pong
|2,0,1621147014,,"! make pong"
:tabnew pong/cmp.hack
|2,0,1621147014,,"tabnew pong/cmp.hack"
:! wget https://github.com/jtdowney/nand2tetris/blob/master/06/pong/Pong.hack
|2,0,1621147014,,"! wget https://github.com/jtdowney/nand2tetris/blob/master/06/pong/Pong.hack"
:! mv Pong.hack cmp.hack
|2,0,1621147014,,"! mv Pong.hack cmp.hack"
:mv cmp.hack pong/
|2,0,1621147014,,"mv cmp.hack pong/"
:! mv cmp.hack pong/
|2,0,1621147014,,"! mv cmp.hack pong/"
:! diff pong/Pong.hack pong/cmp.hack
|2,0,1621147014,,"! diff pong/Pong.hack pong/cmp.hack"
:tabf ./pong/cmp.hack
|2,0,1621147014,,"tabf ./pong/cmp.hack"
:! g++ main.cpp -fsanitize=address
|2,0,1621147014,,"! g++ main.cpp -fsanitize=address"
:! cat 1.in | ./a.out
|2,0,1621147014,,"! cat 1.in | ./a.out"
:m!
|2,0,1621147014,,"m!"
:make 1.in
|2,0,1621147014,,"make 1.in"
:! make 1.in
|2,0,1621147014,,"! make 1.in"
:!make 1.in
|2,0,1621147014,,"!make 1.in"
:! python3 integers.py
|2,0,1621147014,,"! python3 integers.py"
:tabf ../StackTest/StackTest.vm
|2,0,1621147014,,"tabf ../StackTest/StackTest.vm"
:tabf ./StackArithmetic/*/*.vm
|2,0,1621147014,,"tabf ./StackArithmetic/*/*.vm"
:args ./StackArithmetic/*/*.vm
|2,0,1621147014,,"args ./StackArithmetic/*/*.vm"
:tabf *.py
|2,0,1621147014,,"tabf *.py"
:mak
|2,0,1621147014,,"mak"
:! python
|2,0,1621147014,,"! python"
:%s/sp/SP/gc
|2,0,1621147014,,"%s/sp/SP/gc"
:tabf ./StackArithmetic/SimpleAdd/SimpleAdd.asm
|2,0,1621147014,,"tabf ./StackArithmetic/SimpleAdd/SimpleAdd.asm"
:makr
|2,0,1621147014,,"makr"
:mark
|2,0,1621147014,,"mark"
:makrs
|2,0,1621147014,,"makrs"
:m
|2,0,1621147014,,"m"
:! make 
|2,0,1621147014,,"! make "
:! make add
|2,0,1621147014,,"! make add"
:tabf pulse/
|2,0,1621147014,,"tabf pulse/"
:! VMEmulator
|2,0,1621147014,,"! VMEmulator"
:explore
|2,0,1621147014,,"explore"
:!py
|2,0,1621147014,,"!py"
:! man split
|2,0,1621147014,,"! man split"
:! make nested
|2,0,1621147014,,"! make nested"
:!ad
|2,0,1621147014,,"!ad"
:! 	. VMTranslator/bin/activate && \	python3 VMTranslator.py FunctionCalls/StaticsTest/Class1.vm && \	deactivate
|2,0,1621147014,,"! 	. VMTranslator/bin/activate && \\	python3 VMTranslator.py FunctionCalls/StaticsTest/Class1.vm && \\	deactivate"
:!. VMTranslator/bin/activate && python3 VMTranslator.py FunctionCalls/StaticsTest/Class1.vm &&  deactivate
|2,0,1621147014,,"!. VMTranslator/bin/activate && python3 VMTranslator.py FunctionCalls/StaticsTest/Class1.vm &&  deactivate"
:tabf ProgramFlow/BasicLoop/BasicLoop.vm
|2,0,1621147014,,"tabf ProgramFlow/BasicLoop/BasicLoop.vm"
:! make basic
|2,0,1621147014,,"! make basic"
:tabf ./ProgramFlow/BasicLoop/BasicLoop.asm
|2,0,1621147014,,"tabf ./ProgramFlow/BasicLoop/BasicLoop.asm"
:tabf ProgramFlow/BasicLoop/*.asm
|2,0,1621147014,,"tabf ProgramFlow/BasicLoop/*.asm"
:! CPUEmulator ./StackArithmetic/SimpleAdd/SimpleAdd.tst
|2,0,1621147014,,"! CPUEmulator ./StackArithmetic/SimpleAdd/SimpleAdd.tst"
:source Session.vim
|2,0,1621147014,,"source Session.vim"
:tabf ../08/VMTranslator.py
|2,0,1621147014,,"tabf ../08/VMTranslator.py"
:!CPUEmulator
|2,0,1621147014,,"!CPUEmulator"
:tabf ./MemoryAccess/PointerTest/PointerTest.asm
|2,0,1621147014,,"tabf ./MemoryAccess/PointerTest/PointerTest.asm"
:!make poiniter
|2,0,1621147014,,"!make poiniter"
:! make stack
|2,0,1621147014,,"! make stack"
:! make all
|2,0,1621147014,,"! make all"
:tabf ../07/VMTranslator.py
|2,0,1621147014,,"tabf ../07/VMTranslator.py"
:foldmethod
|2,0,1621147014,,"foldmethod"
:set foldmethod
|2,0,1621147014,,"set foldmethod"
:help foldmethod
|2,0,1621147014,,"help foldmethod"
:marks
|2,0,1621147014,,"marks"
:! vim ~/.vimrc
|2,0,1621147014,,"! vim ~/.vimrc"
:set foldmethod=manual
|2,0,1621147014,,"set foldmethod=manual"
:18,8fo
|2,0,1621147014,,"18,8fo"
:set codefolding?
|2,0,1621147014,,"set codefolding?"
:set codefold?
|2,0,1621147014,,"set codefold?"
:set foldmethod?
|2,0,1621147014,,"set foldmethod?"
:set foldmethod=expr
|2,0,1621147014,,"set foldmethod=expr"
:18,26fo
|2,0,1621147014,,"18,26fo"
:tabf ./*/*/*.vm
|2,0,1621147014,,"tabf ./*/*/*.vm"
:n ./*/*/*.vm
|2,0,1621147014,,"n ./*/*/*.vm"
:help tab
|2,0,1621147014,,"help tab"
:next ./*/*/*.vm
|2,0,1621147014,,"next ./*/*/*.vm"
:args ./*/*/*.vm
|2,0,1621147014,,"args ./*/*/*.vm"
:tab all
|2,0,1621147014,,"tab all"
:find ./ProgramFlow/
|2,0,1621147014,,"find ./ProgramFlow/"
:! CPUEmulator
|2,0,1621147014,,"! CPUEmulator"
:tabf ./ProgramFlow/BasicLoop/BasicLoop.vm
|2,0,1621147014,,"tabf ./ProgramFlow/BasicLoop/BasicLoop.vm"
:! make fibs
|2,0,1621147014,,"! make fibs"
:tabf ProgramFlow/FibonacciSeries/FibonacciSeries.tst
|2,0,1621147014,,"tabf ProgramFlow/FibonacciSeries/FibonacciSeries.tst"
:tabf ProgramFlow/FibonacciSeries/FibonacciSeries.tst
|2,0,1621147014,,"tabf ProgramFlow/FibonacciSeries/FibonacciSeries.tst"
:tabf FibonacciSeries.asm
|2,0,1621147014,,"tabf FibonacciSeries.asm"
:! python3
|2,0,1621147014,,"! python3"
:make 
|2,0,1621147014,,"make "
:make add
|2,0,1621147014,,"make add"
:make stack
|2,0,1621147014,,"make stack"
:make pointer
|2,0,1621147014,,"make pointer"
:make static
|2,0,1621147014,,"make static"
:! ls
|2,0,1621147014,,"! ls"
:find ./VMTranslator.py
|2,0,1621147014,,"find ./VMTranslator.py"
:! make fibe
|2,0,1621147014,,"! make fibe"
:make basic
|2,0,1621147014,,"make basic"
:tabf ./VMTranslator/
|2,0,1621147014,,"tabf ./VMTranslator/"
:tabf ./FunctionCalls/FibonacciElement/Main.vm
|2,0,1621147014,,"tabf ./FunctionCalls/FibonacciElement/Main.vm"
:make fibs
|2,0,1621147014,,"make fibs"
::q
|2,0,1621147014,,":q"
:tabf ./FunctionCalls/FibonacciElement/FibonacciElement.asm
|2,0,1621147014,,"tabf ./FunctionCalls/FibonacciElement/FibonacciElement.asm"
:tabf ./ProgramFlow/FibonacciSeries/FibonacciSeries.vm
|2,0,1621147014,,"tabf ./ProgramFlow/FibonacciSeries/FibonacciSeries.vm"
:make fibe
|2,0,1621147014,,"make fibe"
:make simple
|2,0,1621147014,,"make simple"
:tabf 
|2,0,1621147014,,"tabf "
:tabf ./FunctionCalls/
|2,0,1621147014,,"tabf ./FunctionCalls/"
:tabf ./FunctionCalls/NestedCall/Sys.vm
|2,0,1621147014,,"tabf ./FunctionCalls/NestedCall/Sys.vm"
:make nest
|2,0,1621147014,,"make nest"
:make nested
|2,0,1621147014,,"make nested"
:make statics
|2,0,1621147014,,"make statics"
:tabf ./FunctionCalls/StaticsTest/Class1.asm
|2,0,1621147014,,"tabf ./FunctionCalls/StaticsTest/Class1.asm"
:tabf ./FunctionCalls/StaticsTest/StaticsTest.asm
|2,0,1621147014,,"tabf ./FunctionCalls/StaticsTest/StaticsTest.asm"
:Explore 
|2,0,1621147014,,"Explore "
:!VMEmulator
|2,0,1621147014,,"!VMEmulator"
:!make statics
|2,0,1621147014,,"!make statics"
:!make fibe
|2,0,1621147014,,"!make fibe"
:!make nested
|2,0,1621147014,,"!make nested"
:!make simple
|2,0,1621147014,,"!make simple"
:!make fibs
|2,0,1621147014,,"!make fibs"
:!make basic
|2,0,1621147014,,"!make basic"
:!make pointer
|2,0,1621147014,,"!make pointer"
:!make static
|2,0,1621147014,,"!make static"
:!make stack
|2,0,1621147014,,"!make stack"
:!make add
|2,0,1621147014,,"!make add"
:'<,'>!
|2,0,1621147014,,"'<,'>!"
:tabnew 1.in
|2,0,1621147014,,"tabnew 1.in"
:W
|2,0,1621147014,,"W"
:1
|2,0,1621147014,,"1"
:Qa
|2,0,1621147014,,"Qa"
::::::::::!
|2,0,1621147014,,":::::::::!"
:tabnew Main.jack
|2,0,1621147014,,"tabnew Main.jack"
:!tabf ../HelloWorld/Main.jack
|2,0,1621147014,,"!tabf ../HelloWorld/Main.jack"
:!JackCompiler ../
|2,0,1621147014,,"!JackCompiler ../"
:tabf ../HelloWorld/Main.jack
|2,0,1621147014,,"tabf ../HelloWorld/Main.jack"
:tabf ../Fraction/Main.jack
|2,0,1621147014,,"tabf ../Fraction/Main.jack"
:tabf ../Average/Main.jack
|2,0,1621147014,,"tabf ../Average/Main.jack"
:tabf ../Fraction/Fraction.jack
|2,0,1621147014,,"tabf ../Fraction/Fraction.jack"
:%s/circle/circle2/gc
|2,0,1621147014,,"%s/circle/circle2/gc"
:tabnew Empty.jack
|2,0,1621147014,,"tabnew Empty.jack"
:tabnew Cross.jack
|2,0,1621147014,,"tabnew Cross.jack"
:tabnew White.jack
|2,0,1621147014,,"tabnew White.jack"
:mksession Session.vim
|2,0,1621147014,,"mksession Session.vim"
::w
|2,0,1621147014,,":w"
:tabnew Cell.jack
|2,0,1621147014,,"tabnew Cell.jack"
:tabnew State.jack
|2,0,1621147014,,"tabnew State.jack"
:Wa
|2,0,1621147014,,"Wa"
:tabf Cell.jack
|2,0,1621147014,,"tabf Cell.jack"
:tabf State.jack
|2,0,1621147014,,"tabf State.jack"
:tabnew TicTac.jack
|2,0,1621147014,,"tabnew TicTac.jack"
:tabnew KeyListener.jack
|2,0,1621147014,,"tabnew KeyListener.jack"
:tabf ./KeyListener.jack
|2,0,1621147014,,"tabf ./KeyListener.jack"
:tabnew GameState.jack
|2,0,1621147014,,"tabnew GameState.jack"
:s/0/2/g
|2,0,1621147014,,"s/0/2/g"
:tabf GameState.jack
|2,0,1621147014,,"tabf GameState.jack"
:! python3 password.py
|2,0,1621147014,,"! python3 password.py"
:qs
|2,0,1621147014,,"qs"
:%s/string/hello/g
|2,0,1621147014,,"%s/string/hello/g"
:tabnew output.txt
|2,0,1621147014,,"tabnew output.txt"
:tabnew main.py
|2,0,1621147014,,"tabnew main.py"
:!make py
|2,0,1621147014,,"!make py"
:ret
|2,0,1621147014,,"ret"
:tabf ~/.vimrc
|2,0,1621147014,,"tabf ~/.vimrc"
:retab!
|2,0,1621147014,,"retab!"
:!autopep8
|2,0,1621147014,,"!autopep8"
:!pip3 install autopep8
|2,0,1621147014,,"!pip3 install autopep8"
:tabm 4
|2,0,1621147014,,"tabm 4"
:!autopep8 -i main.py
|2,0,1621147014,,"!autopep8 -i main.py"
:! make py
|2,0,1621147014,,"! make py"
:! g++ main.c
|2,0,1621147014,,"! g++ main.c"
:tabnew binary_tree.cpp
|2,0,1621147014,,"tabnew binary_tree.cpp"
:tabnew binary_tree.h
|2,0,1621147014,,"tabnew binary_tree.h"
:tabnew parser.h
|2,0,1621147014,,"tabnew parser.h"
:%s/var/val/g
|2,0,1621147014,,"%s/var/val/g"
:tabf ../guess/1.in
|2,0,1621147014,,"tabf ../guess/1.in"
:! xdg-open ../
|2,0,1621147014,,"! xdg-open ../"
:!make i.in
|2,0,1621147014,,"!make i.in"
:! python3 main.py
|2,0,1621147014,,"! python3 main.py"
:!xdg-open .
|2,0,1621147014,,"!xdg-open ."
:s/0/1/g
|2,0,1621147014,,"s/0/1/g"
:s/1/0/g
|2,0,1621147014,,"s/1/0/g"
:.,.+1!
|2,0,1621147014,,".,.+1!"
:! make i.in
|2,0,1621147014,,"! make i.in"
:tabf d.in
|2,0,1621147014,,"tabf d.in"
:tabnew d.in
|2,0,1621147014,,"tabnew d.in"
:! make d.in
|2,0,1621147014,,"! make d.in"
:python3 JackAnalyser.py
|2,0,1621147014,,"python3 JackAnalyser.py"
:!python3 JackAnalyser.py
|2,0,1621147014,,"!python3 JackAnalyser.py"
:! source ./JackAnalyser/bin/activate
|2,0,1621147014,,"! source ./JackAnalyser/bin/activate"
:tabe 
|2,0,1621147014,,"tabe "
:tabf ./ExpressionLessSquare/Main.jack
|2,0,1621147014,,"tabf ./ExpressionLessSquare/Main.jack"
:Explore
|2,0,1621147014,,"Explore"
:! pwd
|2,0,1621147014,,"! pwd"
:!make express
|2,0,1621147014,,"!make express"
:tabnew CodeReader.py
|2,0,1621147014,,"tabnew CodeReader.py"
:tabf jack_tokenizer.py
|2,0,1621147014,,"tabf jack_tokenizer.py"
:!make jack_tokenizer
|2,0,1621147014,,"!make jack_tokenizer"
:tabf ./ExpressionLessSquare/Square.xml
|2,0,1621147014,,"tabf ./ExpressionLessSquare/Square.xml"
:tabf SquareGameT.xml
|2,0,1621147014,,"tabf SquareGameT.xml"
:! diff SquareGameT.JT.xml SquareGameT.xml
|2,0,1621147014,,"! diff SquareGameT.JT.xml SquareGameT.xml"
:! TextComparer
|2,0,1621147014,,"! TextComparer"
:! TextComparer SquareGameT.JT.xml SquareGameT.xml
|2,0,1621147014,,"! TextComparer SquareGameT.JT.xml SquareGameT.xml"
:! TextCompare
|2,0,1621147014,,"! TextCompare"
:tabm 0
|2,0,1621147014,,"tabm 0"
:tabf Square.xml
|2,0,1621147014,,"tabf Square.xml"
:tabf Main.jack
|2,0,1621147014,,"tabf Main.jack"
:g++ lims.cpp && ./a.out
|2,0,1621147014,,"g++ lims.cpp && ./a.out"
:! g++ lims.cpp && ./a.out
|2,0,1621147014,,"! g++ lims.cpp && ./a.out"
:s/a/b/g
|2,0,1621147014,,"s/a/b/g"
:!g++ --version
|2,0,1621147014,,"!g++ --version"
:%/long long/unsigned long long/g
|2,0,1621147014,,"%/long long/unsigned long long/g"
:%s/long long/unsigned long long/g
|2,0,1621147014,,"%s/long long/unsigned long long/g"
:tabf ~
|2,0,1621147014,,"tabf ~"
:%s/long long/int/g
|2,0,1621147014,,"%s/long long/int/g"
:%s/[nx][ny]/[ny][nx]/gc
|2,0,1621147014,,"%s/[nx][ny]/[ny][nx]/gc"
:!g++ main.cpp && cat 1.in | ./a.out
|2,0,1621147014,,"!g++ main.cpp && cat 1.in | ./a.out"
:!g++ main.cpp -fsanitize=address && cat 1.in | ./a.out
|2,0,1621147014,,"!g++ main.cpp -fsanitize=address && cat 1.in | ./a.out"
:!python3 roman.py
|2,0,1621147014,,"!python3 roman.py"
:%/>>/<</g
|2,0,1621147014,,"%/>>/<</g"
:s/>>/<</g
|2,0,1621147014,,"s/>>/<</g"
:tabf
|2,0,1621147014,,"tabf"
:tabnew 2.out
|2,0,1621147014,,"tabnew 2.out"
:!make 2.in
|2,0,1621147014,,"!make 2.in"
:! make 2
|2,0,1621147014,,"! make 2"
:! make
|2,0,1621147014,,"! make"
:tab
|2,0,1621147014,,"tab"
:color industry
|2,0,1621147014,,"color industry"
:color desert
|2,0,1621147014,,"color desert"
:%/ull/ll/g
|2,0,1621147014,,"%/ull/ll/g"
:%s/ull/ll/g
|2,0,1621147014,,"%s/ull/ll/g"
:python
|2,0,1621147014,,"python"
:!cat 1.in | python3 main.py
|2,0,1621147014,,"!cat 1.in | python3 main.py"
:5y
|2,0,1621147014,,"5y"
:tabm 3
|2,0,1621147014,,"tabm 3"
:s/i/t
|2,0,1621147014,,"s/i/t"
:s/i/t/g
|2,0,1621147014,,"s/i/t/g"
:s/ //g
|2,0,1621147014,,"s/ //g"
:!g++ hello_world.cpp && ./a.out
|2,0,1621147014,,"!g++ hello_world.cpp && ./a.out"
:!./a.out
|2,0,1621147014,,"!./a.out"
:s/3/ /g
|2,0,1621147014,,"s/3/ /g"
:s/_3//g
|2,0,1621147014,,"s/_3//g"
:%dp+
|2,0,1621147014,,"%dp+"
:%p+
|2,0,1621147014,,"%p+"
:s/M/j/g
|2,0,1621147014,,"s/M/j/g"
:%v
|2,0,1621147014,,"%v"
:%s/char * str/string str/gc
|2,0,1621147014,,"%s/char * str/string str/gc"
:s/str[i]/c/g
|2,0,1621147014,,"s/str[i]/c/g"
:s/str\[i\]/c/g
|2,0,1621147014,,"s/str\\[i\\]/c/g"
:%s/&str/str/gc
|2,0,1621147014,,"%s/&str/str/gc"
:%s/void/string/gc
|2,0,1621147014,,"%s/void/string/gc"
:k
|2,0,1621147014,,"k"
:!python3 inter
|2,0,1621147014,,"!python3 inter"
:!python3 interleavings.py
|2,0,1621147014,,"!python3 interleavings.py"
:!python3 interleavings.py > output.txt
|2,0,1621147014,,"!python3 interleavings.py > output.txt"
:tabf output.txt
|2,0,1621147014,,"tabf output.txt"
:!python
|2,0,1621147014,,"!python"
:tabf 2.in
|2,0,1621147014,,"tabf 2.in"
:%s/2//gc
|2,0,1621147014,,"%s/2//gc"
:!make 1 && make 2
|2,0,1621147014,,"!make 1 && make 2"
:tabf 2.out
|2,0,1621147014,,"tabf 2.out"
:%s/./a.out/main
|2,0,1621147014,,"%s/./a.out/main"
:%s/.\/a.out/main.g
|2,0,1621147014,,"%s/.\\/a.out/main.g"
:%s/.\/a.out/main/g
|2,0,1621147014,,"%s/.\\/a.out/main/g"
:tabf main.cpp
|2,0,1621147014,,"tabf main.cpp"
:mks Session.vim
|2,0,1621147014,,"mks Session.vim"
:tabf ./shapecolour.p
|2,0,1621147014,,"tabf ./shapecolour.p"
:Wqa
|2,0,1621147014,,"Wqa"
:s/,//g
|2,0,1621147014,,"s/,//g"
:tabf ./main2.cpp
|2,0,1621147014,,"tabf ./main2.cpp"
:!mawke
|2,0,1621147014,,"!mawke"
:!make 
|2,0,1621147014,,"!make "
:!make all
|2,0,1621147014,,"!make all"
:%s/big/b/g
|2,0,1621147014,,"%s/big/b/g"
:%s/small/s/g
|2,0,1621147014,,"%s/small/s/g"
:%s/'/"/g
|2,0,1621147014,,"%s/'/\"/g"
:%s/\'/\"/g
|2,0,1621147014,,"%s/\\'/\\\"/g"
:%s/\â€˜/\'/g
|2,0,1621147014,,"%s/\\â€˜/\\'/g"
:%s/â€˜/'/g
|2,0,1621147014,,"%s/â€˜/'/g"
:%/â€™/'/g
|2,0,1621147014,,"%/â€™/'/g"
:%s/â€™/'/g
|2,0,1621147014,,"%s/â€™/'/g"
:%s/convert/str2int/gc
|2,0,1621147014,,"%s/convert/str2int/gc"
:ewqa
|2,0,1621147014,,"ewqa"
:s/makepair/make_pair/g
|2,0,1621147014,,"s/makepair/make_pair/g"
:%s/\.\/a\.out/main/g
|2,0,1621147014,,"%s/\\.\\/a\\.out/main/g"
:!mks
|2,0,1621147014,,"!mks"
:mks!
|2,0,1621147014,,"mks!"
:!ma
|2,0,1621147014,,"!ma"
:tabf 1.cm
|2,0,1621147014,,"tabf 1.cm"
:! diff
|2,0,1621147014,,"! diff"
:! diff 1.out 1.cmp
|2,0,1621147014,,"! diff 1.out 1.cmp"
:%y
|2,0,1621147014,,"%y"
:tabf main2.cpp
|2,0,1621147014,,"tabf main2.cpp"
:!rm ./a.out
|2,0,1621147014,,"!rm ./a.out"
:!make krusk
|2,0,1621147014,,"!make krusk"
:!mke
|2,0,1621147014,,"!mke"
:s/\<count\>/countP/g
|2,0,1621147014,,"s/\\<count\\>/countP/g"
:s/j/n/g
|2,0,1621147014,,"s/j/n/g"
:tabnew main2.cpp
|2,0,1621147014,,"tabnew main2.cpp"
:s/i/j/g
|2,0,1621147014,,"s/i/j/g"
:!mkae
|2,0,1621147014,,"!mkae"
:'<,'>
|2,0,1621147014,,"'<,'>"
:%s/\<n\>/N/gc
|2,0,1621147014,,"%s/\\<n\\>/N/gc"
:tabnew 1.out
|2,0,1621147014,,"tabnew 1.out"
:tabf 1.cmp
|2,0,1621147014,,"tabf 1.cmp"
:tabm 1
|2,0,1621147014,,"tabm 1"
:tabf 1.in
|2,0,1621147014,,"tabf 1.in"
:tabf ../1/main.cpp
|2,0,1621147014,,"tabf ../1/main.cpp"
:s/prims/Prims/g
|2,0,1621147014,,"s/prims/Prims/g"
:tabnew 2.in
|2,0,1621147014,,"tabnew 2.in"
:make 2
|2,0,1621147014,,"make 2"
:%s/Prims/Prim's/gc
|2,0,1621147014,,"%s/Prims/Prim's/gc"
:!make 2
|2,0,1621147014,,"!make 2"
:!make 2cp
|2,0,1621147014,,"!make 2cp"
:!make 1
|2,0,1621147014,,"!make 1"
:make cp
|2,0,1621147014,,"make cp"
:make 1cp
|2,0,1621147014,,"make 1cp"
:!make cp
|2,0,1621147014,,"!make cp"
:mks Session.vim 
|2,0,1621147014,,"mks Session.vim "
:wqaa
|2,0,1621147014,,"wqaa"
:.!
|2,0,1621147014,,".!"
:tabm 2
|2,0,1621147014,,"tabm 2"
:%s/queue/deque/gc
|2,0,1621147014,,"%s/queue/deque/gc"
:tabnew 1.cmp
|2,0,1621147014,,"tabnew 1.cmp"
:!make 1cp
|2,0,1621147014,,"!make 1cp"
:s/1/2/g
|2,0,1621147014,,"s/1/2/g"
:!make 1out
|2,0,1621147014,,"!make 1out"
:!mae
|2,0,1621147014,,"!mae"
:!mak
|2,0,1621147014,,"!mak"
:!mk
|2,0,1621147014,,"!mk"
:~
|2,0,1621147014,,"~"
:tabf 1.out
|2,0,1621147014,,"tabf 1.out"
:%y+
|2,0,1621147014,,"%y+"
:!python3 main.py
|2,0,1621147014,,"!python3 main.py"
:python3 acronym	
|2,0,1621147014,,"python3 acronym	"
:!pythond3 acronym.py
|2,0,1621147014,,"!pythond3 acronym.py"
:!python3 acronym.py1
|2,0,1621147014,,"!python3 acronym.py1"
:!python3 acronym.py
|2,0,1621147014,,"!python3 acronym.py"
:!python3
|2,0,1621147014,,"!python3"
:!python3 longest_distance.py
|2,0,1621147014,,"!python3 longest_distance.py"
:wq
|2,0,1621147014,,"wq"
:%s/data/d/g
|2,0,1621147014,,"%s/data/d/g"
:!
|2,0,1621147014,,"!"
:! g++ 
|2,0,1621147014,,"! g++ "
:!python3 lucky.py
|2,0,1621147014,,"!python3 lucky.py"
:wqa
|2,0,1621147014,,"wqa"
:!m
|2,0,1621147014,,"!m"
:split
|2,0,1621147014,,"split"
:%yC
|2,0,1621147014,,"%yC"
:%yp
|2,0,1621147014,,"%yp"
:%y"p
|2,0,1621147014,,"%y\"p"
:%"py
|2,0,1621147014,,"%\"py"
:%py
|2,0,1621147014,,"%py"
:s/\<i\>/kg
|2,0,1621147014,,"s/\\<i\\>/kg"
:%=
|2,0,1621147014,,"%="
:s/\<i\>/j/g
|2,0,1621147014,,"s/\\<i\\>/j/g"
:%cy
|2,0,1621147014,,"%cy"
:%yc
|2,0,1621147014,,"%yc"
:%"cy
|2,0,1621147014,,"%\"cy"
:tabf module.c module.h
|2,0,1621147014,,"tabf module.c module.h"
:help tabnew
|2,0,1621147014,,"help tabnew"
:%s/\<.\>/./g
|2,0,1621147014,,"%s/\\<.\\>/./g"
:%s/\<.\>/\<_\>/g
|2,0,1621147014,,"%s/\\<.\\>/\\<_\\>/g"
:%s/\<.\>/_/g
|2,0,1621147014,,"%s/\\<.\\>/_/g"
:%s/./_/g
|2,0,1621147014,,"%s/./_/g"
:let "@ = expand("%")
|2,0,1621147014,,"let \"@ = expand(\"%\")"
:let @" = explore("%")
|2,0,1621147014,,"let @\" = explore(\"%\")"
:tabnew module_2.h
|2,0,1621147014,,"tabnew module_2.h"
:v
|2,0,1621147014,,"v"
:s
|2,0,1621147014,,"s"
:split ter
|2,0,1621147014,,"split ter"
:s/\<j\>/k/
|2,0,1621147014,,"s/\\<j\\>/k/"
:tabnew hello.h
|2,0,1621147014,,"tabnew hello.h"
:put expand("%")
|2,0,1621147014,,"put expand(\"%\")"
:put =expand("%")
|2,0,1621147014,,"put =expand(\"%\")"
:put strftime('%c')
|2,0,1621147014,,"put strftime('%c')"
:put =strftime('%c')
|2,0,1621147014,,"put =strftime('%c')"
:let = expand("%")
|2,0,1621147014,,"let = expand(\"%\")"
:p
|2,0,1621147014,,"p"
:%
|2,0,1621147014,,"%"
:let @"=expand("%")
|2,0,1621147014,,"let @\"=expand(\"%\")"
:qa
|2,0,1621147014,,"qa"
:qa!
|2,0,1621147014,,"qa!"
:put = strftime('%c')
|2,0,1621147014,,"put = strftime('%c')"
:tabf hello.h
|2,0,1621147014,,"tabf hello.h"
:tabnew module.h
|2,0,1621147014,,"tabnew module.h"
:tabnew
|2,0,1621147014,,"tabnew"
:tabf Makefile
|2,0,1621147014,,"tabf Makefile"
:tab ter
|2,0,1621147014,,"tab ter"
:wa
|2,0,1621147014,,"wa"
:!rm Makefile
|2,0,1621147014,,"!rm Makefile"
:!ls
|2,0,1621147014,,"!ls"
:1make
|2,0,1621147014,,"1make"
:tabnew Makefile
|2,0,1621147014,,"tabnew Makefile"
:tabe
|2,0,1621147014,,"tabe"
:E
|2,0,1621147014,,"E"
:make
|2,0,1621147014,,"make"
:help mksession
|2,0,1621147014,,"help mksession"
:vsplit
|2,0,1621147014,,"vsplit"
:help
|2,0,1621147014,,"help"
:close
|2,0,1621147014,,"close"
:help autocmd
|2,0,1621147014,,"help autocmd"
:endfor
|2,0,1621147014,,"endfor"
:elseif
|2,0,1621147014,,"elseif"
:tabf ~/.viminfo
|2,0,1621147014,,"tabf ~/.viminfo"
:!make
|2,0,1621147014,,"!make"
:s/\<i\>/k/g
|2,0,1621147014,,"s/\\<i\\>/k/g"
:q!
|2,0,1621147014,,"q!"
:wv cinfo.vim
|2,0,1621147014,,"wv cinfo.vim"
:rv! ~/.cinfo.vim
|2,0,1621147014,,"rv! ~/.cinfo.vim"
:!rv ~/.cinfo.vim
|2,0,1621147014,,"!rv ~/.cinfo.vim"
:tabf main.c
|2,0,1621147014,,"tabf main.c"
:tabf ~/.pyinfo.vim
|2,0,1621147014,,"tabf ~/.pyinfo.vim"
:erg
|2,0,1621147014,,"erg"
:tabnew main.c
|2,0,1621147014,,"tabnew main.c"
:ter
|2,0,1621147014,,"ter"
:set relativenumber
|2,0,1621147014,,"set relativenumber"
:tabnew 
|2,0,1621147014,,"tabnew "
:help session
|2,0,1621147014,,"help session"
:help rv
|2,0,1621147014,,"help rv"
:help viminfo
|2,0,1621147014,,"help viminfo"
:rv! pyinfo.vim
|2,0,1621147014,,"rv! pyinfo.vim"
:wv! pyinfo.vim
|2,0,1621147014,,"wv! pyinfo.vim"
:rv pyinfo.vim
|2,0,1621147014,,"rv pyinfo.vim"
:!python3 solve.py
|2,0,1621147014,,"!python3 solve.py"
:s/eqns/eqs/g
|2,0,1621147014,,"s/eqns/eqs/g"
:[
|2,0,1621147014,,"["
:!pip3 install sympy
|2,0,1621147014,,"!pip3 install sympy"
:!python3 sol
|2,0,1621147014,,"!python3 sol"
:tabf cinfo.vim
|2,0,1621147014,,"tabf cinfo.vim"
:tabf pyinfo.vim
|2,0,1621147014,,"tabf pyinfo.vim"
:rv cinfo.vim
|2,0,1621147014,,"rv cinfo.vim"
:wv pyinfo.vim
|2,0,1621147014,,"wv pyinfo.vim"
:set @" = expand("%")
|2,0,1621147014,,"set @\" = expand(\"%\")"
:tabnew main2.py
|2,0,1621147014,,"tabnew main2.py"
:!rv pyinfo.vim
|2,0,1621147014,,"!rv pyinfo.vim"
:scripname
|2,0,1621147014,,"scripname"
:rv! ../../c/zeev/cinfo.vim
|2,0,1621147014,,"rv! ../../c/zeev/cinfo.vim"
:%s/\<k\>/e/g
|2,0,1621147014,,"%s/\\<k\\>/e/g"
:rege
|2,0,1621147014,,"rege"
:re
|2,0,1621147014,,"re"
:let @" = expand("%")
|2,0,1621147014,,"let @\" = expand(\"%\")"
:let @" =expand("%")
|2,0,1621147014,,"let @\" =expand(\"%\")"
:%d
|2,0,1621147014,,"%d"
:reg
|2,0,1621147014,,"reg"

# Search String History (newest to oldest):
? \<ab\>
|2,1,1621147014,,"\\<ab\\>"
? \<cd\>
|2,1,1621147014,,"\\<cd\\>"
? \<b\>
|2,1,1621147014,,"\\<b\\>"
?/hello
|2,1,1621147014,47,"hello"
? hello
|2,1,1621147014,,"hello"
? \<main\>
|2,1,1621147014,,"\\<main\\>"
? \<j\>
|2,1,1621147014,,"\\<j\\>"
? \<ans\>
|2,1,1621147014,,"\\<ans\\>"
? \<world\>
|2,1,1621147014,,"\\<world\\>"
? hey
|2,1,1621147014,,"hey"
??buffer
|2,1,1621147014,63,"buffer"
??help tabf
|2,1,1621147014,63,"help tabf"
??filetype
|2,1,1621147014,63,"filetype"
??plugin
|2,1,1621147014,63,"plugin"
? \<w\>
|2,1,1621147014,,"\\<w\\>"
??add_exe
|2,1,1621147014,63,"add_exe"
??memory
|2,1,1621147014,63,"memory"
??AddTwoInts
|2,1,1621147014,63,"AddTwoInts"
??Add
|2,1,1621147014,63,"Add"
??add_execu
|2,1,1621147014,63,"add_execu"
??add_executable
|2,1,1621147014,63,"add_executable"
??request
|2,1,1621147014,63,"request"
??install
|2,1,1621147014,63,"install"
??build_depend
|2,1,1621147014,63,"build_depend"
??timer_call
|2,1,1621147014,63,"timer_call"
??find_package
|2,1,1621147014,63,"find_package"
??turt
|2,1,1621147014,63,"turt"
??subscription
|2,1,1621147014,63,"subscription"
??private
|2,1,1621147014,63,"private"
??String
|2,1,1621147014,63,"String"
??tur
|2,1,1621147014,63,"tur"
??kkkk
|2,1,1621147014,63,"kkkk"
??std::m
|2,1,1621147014,63,"std::m"
??std_msgs
|2,1,1621147014,63,"std_msgs"
??std_
|2,1,1621147014,63,"std_"
? \<add_newdoc_ufunc\>
|2,1,1621147014,,"\\<add_newdoc_ufunc\\>"
??def Settings
|2,1,1621147014,63,"def Settings"
??setting
|2,1,1621147014,63,"setting"
??set
|2,1,1621147014,63,"set"
? \<flags\>
|2,1,1621147014,,"\\<flags\\>"
??family
|2,1,1621147014,63,"family"
??plugged
|2,1,1621147014,63,"plugged"
??shiftwidth
|2,1,1621147014,63,"shiftwidth"
??find_package(rosidl_default_generators R
|2,1,1621147014,63,"find_package(rosidl_default_generators R"
??set(msg_files
|2,1,1621147014,63,"set(msg_files"
??"msg/AddressBook.msg
|2,1,1621147014,63,"\"msg/AddressBook.msg"
??rosidl_generate_interfaces(${PROJECT_NAME}
|2,1,1621147014,63,"rosidl_generate_interfaces(${PROJECT_NAME}"
??ament_export_dependencies(rosidl_default_runtime)
|2,1,1621147014,63,"ament_export_dependencies(rosidl_default_runtime)"
? MAX
|2,1,1621147014,,"MAX"
??root
|2,1,1621147014,63,"root"
? \<small_rotation\>
|2,1,1621147014,,"\\<small_rotation\\>"
? \<update\>
|2,1,1621147014,,"\\<update\\>"
??Vertex
|2,1,1621147014,63,"Vertex"
? >
|2,1,1621147014,,">"
??printf
|2,1,1621147014,63,"printf"
? \<Makes\>
|2,1,1621147014,,"\\<Makes\\>"
?/root
|2,1,1621147014,47,"root"
? R
|2,1,1621147014,,"R"
? \<new\>
|2,1,1621147014,,"\\<new\\>"
? v
|2,1,1621147014,,"v"
? \<fromString\>
|2,1,1621147014,,"\\<fromString\\>"
??size()
|2,1,1621147014,63,"size()"
? \<debugger\>
|2,1,1621147014,,"\\<debugger\\>"
??fromSt
|2,1,1621147014,63,"fromSt"
? \<cassert\>
|2,1,1621147014,,"\\<cassert\\>"
??split19k
|2,1,1621147014,63,"split19k"
? \<orderStats\>
|2,1,1621147014,,"\\<orderStats\\>"
??left
|2,1,1621147014,63,"left"
??left->in
|2,1,1621147014,63,"left->in"
??SplayTree
|2,1,1621147014,63,"SplayTree"
??inOrder
|2,1,1621147014,63,"inOrder"
??merged
|2,1,1621147014,63,"merged"
??process
|2,1,1621147014,63,"process"
??end
|2,1,1621147014,63,"end"
??merge
|2,1,1621147014,63,"merge"
??splay
|2,1,1621147014,63,"splay"
??fn
|2,1,1621147014,63,"fn"
??orderStats
|2,1,1621147014,63,"orderStats"
??T
|2,1,1621147014,63,"T"
??fromString
|2,1,1621147014,63,"fromString"
? \<SplayTree\>
|2,1,1621147014,,"\\<SplayTree\\>"
??delete
|2,1,1621147014,63,"delete"
??split
|2,1,1621147014,63,"split"
? \<split\>
|2,1,1621147014,,"\\<split\\>"
??delete(this)
|2,1,1621147014,63,"delete(this)"
??delete this
|2,1,1621147014,63,"delete this"
??DFS
|2,1,1621147014,63,"DFS"
? \<explore\>
|2,1,1621147014,,"\\<explore\\>"
??vector<list
|2,1,1621147014,63,"vector<list"
? vector<list
|2,1,1621147014,,"vector<list"
??explore
|2,1,1621147014,63,"explore"
??push_back
|2,1,1621147014,63,"push_back"
??filter
|2,1,1621147014,63,"filter"
? \<filter\>
|2,1,1621147014,,"\\<filter\\>"
? std::pair<long long, int>
|2,1,1621147014,,"std::pair<long long, int>"
??std::pair
|2,1,1621147014,63,"std::pair"
??continue
|2,1,1621147014,63,"continue"
?/h
|2,1,1621147014,47,"h"
?/incremen
|2,1,1621147014,47,"incremen"
? \<:Next\>
|2,1,1621147014,,"\\<:Next\\>"
? \<:next\>
|2,1,1621147014,,"\\<:next\\>"
? ;
|2,1,1621147014,,";"
??back
|2,1,1621147014,63,"back"
??int
|2,1,1621147014,63,"int"
??new
|2,1,1621147014,63,"new"
? \<back\>
|2,1,1621147014,,"\\<back\\>"
? \<tail\>
|2,1,1621147014,,"\\<tail\\>"
??Enter
|2,1,1621147014,63,"Enter"
? \<s\>
|2,1,1621147014,,"\\<s\\>"
??const
|2,1,1621147014,63,"const"
? \<sort\>
|2,1,1621147014,,"\\<sort\\>"
??key
|2,1,1621147014,63,"key"
? \<partition\>
|2,1,1621147014,,"\\<partition\\>"
??assert
|2,1,1621147014,63,"assert"
? \<swap\>
|2,1,1621147014,,"\\<swap\\>"
??std::cout 
|2,1,1621147014,63,"std::cout "
??partition
|2,1,1621147014,63,"partition"
??yo
|2,1,1621147014,63,"yo"
??sort
|2,1,1621147014,63,"sort"
??loop
|2,1,1621147014,63,"loop"
??9
|2,1,1621147014,63,"9"
??counter
|2,1,1621147014,63,"counter"
??parti
|2,1,1621147014,63,"parti"
??swap
|2,1,1621147014,63,"swap"
??data
|2,1,1621147014,63,"data"
??std::cout
|2,1,1621147014,63,"std::cout"
? \<clustering\>
|2,1,1621147014,,"\\<clustering\\>"
? \\
|2,1,1621147014,,"\\\\"
??D2
|2,1,1621147014,63,"D2"
? bfs
|2,1,1621147014,,"bfs"
??export
|2,1,1621147014,63,"export"
? s
|2,1,1621147014,,"s"
? sel
|2,1,1621147014,,"sel"
? And
|2,1,1621147014,,"And"
? x
|2,1,1621147014,,"x"
? zx
|2,1,1621147014,,"zx"
??Add16
|2,1,1621147014,63,"Add16"
? \<ng\>
|2,1,1621147014,,"\\<ng\\>"
? a.out: main.cpp
|2,1,1621147014,,"a.out: main.cpp"
??size_t
|2,1,1621147014,63,"size_t"
? \<Heap\>
|2,1,1621147014,,"\\<Heap\\>"
? \<heap\>
|2,1,1621147014,,"\\<heap\\>"
? \<getInput\>
|2,1,1621147014,,"\\<getInput\\>"
? \<verbose\>
|2,1,1621147014,,"\\<verbose\\>"
? size
|2,1,1621147014,,"size"
? SortedHeap
|2,1,1621147014,,"SortedHeap"
??size
|2,1,1621147014,63,"size"
??heapn
|2,1,1621147014,63,"heapn"
??heap
|2,1,1621147014,63,"heap"
??sifDown
|2,1,1621147014,63,"sifDown"
??siftDown
|2,1,1621147014,63,"siftDown"
??siftup
|2,1,1621147014,63,"siftup"
??debugger
|2,1,1621147014,63,"debugger"
??ChangePr
|2,1,1621147014,63,"ChangePr"
?/main
|2,1,1621147014,47,"main"
??visited
|2,1,1621147014,63,"visited"
? visited
|2,1,1621147014,,"visited"
? \<ChangePriority\>
|2,1,1621147014,,"\\<ChangePriority\\>"
? \<changePriority\>
|2,1,1621147014,,"\\<changePriority\\>"
??debugg
|2,1,1621147014,63,"debugg"
??deb
|2,1,1621147014,63,"deb"
??de
|2,1,1621147014,63,"de"
??max
|2,1,1621147014,63,"max"
??extract
|2,1,1621147014,63,"extract"
? \<pc\>
|2,1,1621147014,,"\\<pc\\>"
? \<PC\>
|2,1,1621147014,,"\\<PC\\>"
??loadA
|2,1,1621147014,63,"loadA"
??loadD
|2,1,1621147014,63,"loadD"
??jtl
|2,1,1621147014,63,"jtl"
? Hash
|2,1,1621147014,,"Hash"
??<
|2,1,1621147014,63,"<"
??>=
|2,1,1621147014,63,">="
??s
|2,1,1621147014,63,"s"
?/hash
|2,1,1621147014,47,"hash"
? \<hashtable\>
|2,1,1621147014,,"\\<hashtable\\>"
? \<HashTable\>
|2,1,1621147014,,"\\<HashTable\\>"
??class Hash
|2,1,1621147014,63,"class Hash"
??hash(
|2,1,1621147014,63,"hash("
? \<precompute\>
|2,1,1621147014,,"\\<precompute\\>"
??precompute
|2,1,1621147014,63,"precompute"
??ez_l
|2,1,1621147014,63,"ez_l"
??ez-life
|2,1,1621147014,63,"ez-life"
??file_list
|2,1,1621147014,63,"file_list"
? \<ConvertSymbols\>
|2,1,1621147014,,"\\<ConvertSymbols\\>"
??"M"
|2,1,1621147014,63,"\"M\""
??[1]
|2,1,1621147014,63,"[1]"
? \<file_name\>
|2,1,1621147014,,"\\<file_name\\>"
??hack
|2,1,1621147014,63,"hack"
??Handle
|2,1,1621147014,63,"Handle"
??hash
|2,1,1621147014,63,"hash"
??x_l
|2,1,1621147014,63,"x_l"
??getPow
|2,1,1621147014,63,"getPow"
? \<getPow\>
|2,1,1621147014,,"\\<getPow\\>"
??getHash
|2,1,1621147014,63,"getHash"
??Command
|2,1,1621147014,63,"Command"
? sp
|2,1,1621147014,,"sp"
??__init__
|2,1,1621147014,63,"__init__"
? \<write\>
|2,1,1621147014,,"\\<write\\>"
??else if
|2,1,1621147014,63,"else if"
??Aritm
|2,1,1621147014,63,"Aritm"
??PopCon
|2,1,1621147014,63,"PopCon"
?/temp
|2,1,1621147014,47,"temp"
??push
|2,1,1621147014,63,"push"
??main
|2,1,1621147014,63,"main"
??input_file_name
|2,1,1621147014,63,"input_file_name"
??os
|2,1,1621147014,63,"os"
??parser.
|2,1,1621147014,63,"parser."
??parser\.
|2,1,1621147014,63,"parser\\."
??commands
|2,1,1621147014,63,"commands"
? \<CommandPreprocessor\>
|2,1,1621147014,,"\\<CommandPreprocessor\\>"
? \<line\>
|2,1,1621147014,,"\\<line\\>"
??self.parser
|2,1,1621147014,63,"self.parser"
??current_file_full
|2,1,1621147014,63,"current_file_full"
??cmd2type
|2,1,1621147014,63,"cmd2type"
??current_filename
|2,1,1621147014,63,"current_filename"
??Parse
|2,1,1621147014,63,"Parse"
??directory
|2,1,1621147014,63,"directory"
??full_directory_
|2,1,1621147014,63,"full_directory_"
??rsplit
|2,1,1621147014,63,"rsplit"
??full_directory_path
|2,1,1621147014,63,"full_directory_path"
??full_path
|2,1,1621147014,63,"full_path"
??path_is_file
|2,1,1621147014,63,"path_is_file"
??full_out_filename
|2,1,1621147014,63,"full_out_filename"
??self.full_directory
|2,1,1621147014,63,"self.full_directory"
? \<cmd2type\>
|2,1,1621147014,,"\\<cmd2type\\>"
??'r'
|2,1,1621147014,63,"'r'"
??tst
|2,1,1621147014,63,"tst"
? \<full_file_path\>
|2,1,1621147014,,"\\<full_file_path\\>"
? \<commands\>
|2,1,1621147014,,"\\<commands\\>"
??po
|2,1,1621147014,63,"po"
??classmethod
|2,1,1621147014,63,"classmethod"
??foo
|2,1,1621147014,63,"foo"
??writePush
|2,1,1621147014,63,"writePush"
??write
|2,1,1621147014,63,"write"
??foldmethod
|2,1,1621147014,63,"foldmethod"
??Ad12
|2,1,1621147014,63,"Ad12"
??add12
|2,1,1621147014,63,"add12"
??call
|2,1,1621147014,63,"call"
? \<BasicLoop\>
|2,1,1621147014,,"\\<BasicLoop\\>"
??function
|2,1,1621147014,63,"function"
??Arith
|2,1,1621147014,63,"Arith"
??temp
|2,1,1621147014,63,"temp"
??this.func
|2,1,1621147014,63,"this.func"
? \<writeGoto\>
|2,1,1621147014,,"\\<writeGoto\\>"
??convertLabel
|2,1,1621147014,63,"convertLabel"
? \<convertLabel\>
|2,1,1621147014,,"\\<convertLabel\\>"
? \<convertIf\>
|2,1,1621147014,,"\\<convertIf\\>"
? \<convertGoto\>
|2,1,1621147014,,"\\<convertGoto\\>"
??rect
|2,1,1621147014,63,"rect"
??ret
|2,1,1621147014,63,"ret"
? \<return_address\>
|2,1,1621147014,,"\\<return_address\\>"
??Return
|2,1,1621147014,63,"Return"
??convertReturn
|2,1,1621147014,63,"convertReturn"
??Branch
|2,1,1621147014,63,"Branch"
??n_var
|2,1,1621147014,63,"n_var"
??Sys
|2,1,1621147014,63,"Sys"
??{
|2,1,1621147014,63,"{"
??}
|2,1,1621147014,63,"}"
??push n
|2,1,1621147014,63,"push n"
??/#
|2,1,1621147014,63,"/#"
??argument
|2,1,1621147014,63,"argument"
??Sys.init
|2,1,1621147014,63,"Sys.init"
??sys
|2,1,1621147014,63,"sys"
??function Sys.init 0
|2,1,1621147014,63,"function Sys.init 0"
??goto while
|2,1,1621147014,63,"goto while"
?/function sys
|2,1,1621147014,47,"function sys"
??0;JMP
|2,1,1621147014,63,"0;JMP"
??label
|2,1,1621147014,63,"label"
??pop
|2,1,1621147014,63,"pop"
?//
|2,1,1621147014,47,"/"
??convertCall
|2,1,1621147014,63,"convertCall"
? \<convertCall\>
|2,1,1621147014,,"\\<convertCall\\>"
? \<writeBootStrap\>
|2,1,1621147014,,"\\<writeBootStrap\\>"
?/sys.init$ret
|2,1,1621147014,47,"sys.init$ret"
??@sysinit
|2,1,1621147014,63,"@sysinit"
??sys.init
|2,1,1621147014,63,"sys.init"
? \<init\>
|2,1,1621147014,,"\\<init\\>"
? \<sys\>
|2,1,1621147014,,"\\<sys\\>"
? \<Sys\>
|2,1,1621147014,,"\\<Sys\\>"
??4
|2,1,1621147014,63,"4"
??Main.fibonacci
|2,1,1621147014,63,"Main.fibonacci"
??@Main.fibonacci$IF
|2,1,1621147014,63,"@Main.fibonacci$IF"
??@Main.fibonacci$IF_F
|2,1,1621147014,63,"@Main.fibonacci$IF_F"
??IF_FALSE
|2,1,1621147014,63,"IF_FALSE"
??.pop()
|2,1,1621147014,63,".pop()"
? \<fromCmd\>
|2,1,1621147014,,"\\<fromCmd\\>"
? \<CodeWriter\>
|2,1,1621147014,,"\\<CodeWriter\\>"
? circle
|2,1,1621147014,,"circle"
??static
|2,1,1621147014,63,"static"
??10
|2,1,1621147014,63,"10"
??100
|2,1,1621147014,63,"100"
??state
|2,1,1621147014,63,"state"
??initArray
|2,1,1621147014,63,"initArray"
?/setState
|2,1,1621147014,47,"setState"
??draw()
|2,1,1621147014,63,"draw()"
? \<setPos\>
|2,1,1621147014,,"\\<setPos\\>"
??changePos
|2,1,1621147014,63,"changePos"
? \<changePos\>
|2,1,1621147014,,"\\<changePos\\>"
??fill
|2,1,1621147014,63,"fill"
??get
|2,1,1621147014,63,"get"
??setPos
|2,1,1621147014,63,"setPos"
??getState
|2,1,1621147014,63,"getState"
??clear()
|2,1,1621147014,63,"clear()"
??clear
|2,1,1621147014,63,"clear"
??reset
|2,1,1621147014,63,"reset"
??checkSolved
|2,1,1621147014,63,"checkSolved"
? \<iostream\>
|2,1,1621147014,,"\\<iostream\\>"
? string
|2,1,1621147014,,"string"
?/string
|2,1,1621147014,47,"string"
??comp
|2,1,1621147014,63,"comp"
??ans
|2,1,1621147014,63,"ans"
??hou
|2,1,1621147014,63,"hou"
? \<comp\>
|2,1,1621147014,,"\\<comp\\>"
? var
|2,1,1621147014,,"var"
??Parser
|2,1,1621147014,63,"Parser"
??Node
|2,1,1621147014,63,"Node"
? \<inNode\>
|2,1,1621147014,,"\\<inNode\\>"
??top
|2,1,1621147014,63,"top"
??revers
|2,1,1621147014,63,"revers"
??store
|2,1,1621147014,63,"store"
? 0
|2,1,1621147014,,"0"
? \<bfs\>
|2,1,1621147014,,"\\<bfs\\>"
??q.end()
|2,1,1621147014,63,"q.end()"
??dfs
|2,1,1621147014,63,"dfs"
??parent
|2,1,1621147014,63,"parent"
??inNode
|2,1,1621147014,63,"inNode"
??disp
|2,1,1621147014,63,"disp"
? \<next\>
|2,1,1621147014,,"\\<next\\>"
??right
|2,1,1621147014,63,"right"
??find
|2,1,1621147014,63,"find"
??bfs
|2,1,1621147014,63,"bfs"
??insert
|2,1,1621147014,63,"insert"
??m
|2,1,1621147014,63,"m"
??game
|2,1,1621147014,63,"game"
??input
|2,1,1621147014,63,"input"
??string constant
|2,1,1621147014,63,"string constant"
??&lt
|2,1,1621147014,63,"&lt"
??let length
|2,1,1621147014,63,"let length"
? a
|2,1,1621147014,,"a"
??solve
|2,1,1621147014,63,"solve"
??\a
|2,1,1621147014,63,"\\a"
??list
|2,1,1621147014,63,"list"
??ipair
|2,1,1621147014,63,"ipair"
??wh
|2,1,1621147014,63,"wh"
??who
|2,1,1621147014,63,"who"
? long long
|2,1,1621147014,,"long long"
??long long
|2,1,1621147014,63,"long long"
??cout 
|2,1,1621147014,63,"cout "
??auto
|2,1,1621147014,63,"auto"
??open
|2,1,1621147014,63,"open"
? [nx][ny]
|2,1,1621147014,,"[nx][ny]"
? >>
|2,1,1621147014,,">>"
? ull
|2,1,1621147014,,"ull"
? \<comb\>
|2,1,1621147014,,"\\<comb\\>"
? );
|2,1,1621147014,,");"
? \<power\>
|2,1,1621147014,,"\\<power\\>"
?  
|2,1,1621147014,," "
??C
|2,1,1621147014,63,"C"
? 3
|2,1,1621147014,,"3"
? _3
|2,1,1621147014,,"_3"
? M
|2,1,1621147014,,"M"
??modInverse
|2,1,1621147014,63,"modInverse"
??comb
|2,1,1621147014,63,"comb"
??min
|2,1,1621147014,63,"min"
??eval
|2,1,1621147014,63,"eval"
? \<eval\>
|2,1,1621147014,,"\\<eval\\>"
? char * str
|2,1,1621147014,,"char * str"
? \<lower\>
|2,1,1621147014,,"\\<lower\\>"
? str[i]
|2,1,1621147014,,"str[i]"
? str\[i\]
|2,1,1621147014,,"str\\[i\\]"
??&str
|2,1,1621147014,63,"&str"
? &str
|2,1,1621147014,,"&str"
? void
|2,1,1621147014,,"void"
??origin
|2,1,1621147014,63,"origin"
??cout
|2,1,1621147014,63,"cout"
? 2
|2,1,1621147014,,"2"
? .\/a.out
|2,1,1621147014,,".\\/a.out"
? \<solve\>
|2,1,1621147014,,"\\<solve\\>"
? \<c\>
|2,1,1621147014,,"\\<c\\>"
? \<disp\>
|2,1,1621147014,,"\\<disp\\>"
? ,
|2,1,1621147014,,","
? big
|2,1,1621147014,,"big"
? small
|2,1,1621147014,,"small"
? '
|2,1,1621147014,,"'"
? \'
|2,1,1621147014,,"\\'"
? \â€˜
|2,1,1621147014,,"\\â€˜"
? â€˜
|2,1,1621147014,,"â€˜"
? â€™
|2,1,1621147014,,"â€™"
? convert
|2,1,1621147014,,"convert"
? \<convert\>
|2,1,1621147014,,"\\<convert\\>"
??print
|2,1,1621147014,63,"print"
? \<include\>
|2,1,1621147014,,"\\<include\\>"
? makepair
|2,1,1621147014,,"makepair"
? \<ull\>
|2,1,1621147014,,"\\<ull\\>"
? \.\/a\.out
|2,1,1621147014,,"\\.\\/a\\.out"
??emplace
|2,1,1621147014,63,"emplace"
? \<extractMin\>
|2,1,1621147014,,"\\<extractMin\\>"
??t
|2,1,1621147014,63,"t"
? \<array\>
|2,1,1621147014,,"\\<array\\>"
? \<find\>
|2,1,1621147014,,"\\<find\\>"
? \<count\>
|2,1,1621147014,,"\\<count\\>"
? j
|2,1,1621147014,,"j"
? \<countP\>
|2,1,1621147014,,"\\<countP\\>"
? i
|2,1,1621147014,,"i"
? \<n\>
|2,1,1621147014,,"\\<n\\>"
? \<quickSort\>
|2,1,1621147014,,"\\<quickSort\\>"
? \<mergeSort\>
|2,1,1621147014,,"\\<mergeSort\\>"
? prims
|2,1,1621147014,,"prims"
? Prims
|2,1,1621147014,,"Prims"
??count
|2,1,1621147014,63,"count"
??for
|2,1,1621147014,63,"for"
??while
|2,1,1621147014,63,"while"
??i++
|2,1,1621147014,63,"i++"
?/++
|2,1,1621147014,47,"++"
??unsigned
|2,1,1621147014,63,"unsigned"
??keywords
|2,1,1621147014,63,"keywords"
??keyword
|2,1,1621147014,63,"keyword"
??return
|2,1,1621147014,63,"return"
??dynamic
|2,1,1621147014,63,"dynamic"
? \<nsol\>
|2,1,1621147014,,"\\<nsol\\>"
? queue
|2,1,1621147014,,"queue"
??aho
|2,1,1621147014,63,"aho"
? 1
|2,1,1621147014,,"1"
? \<cp\>
|2,1,1621147014,,"\\<cp\\>"
? \<f\>
|2,1,1621147014,,"\\<f\\>"
? \<I\>
|2,1,1621147014,,"\\<I\\>"
? \<pow\>
|2,1,1621147014,,"\\<pow\\>"
??cp
|2,1,1621147014,63,"cp"
??exit
|2,1,1621147014,63,"exit"
??Aho-Corasick
|2,1,1621147014,63,"Aho-Corasick"
??>
|2,1,1621147014,63,">"
? data
|2,1,1621147014,,"data"
? \<testRabinKarpPatternSearch\>
|2,1,1621147014,,"\\<testRabinKarpPatternSearch\\>"
? \<parse\>
|2,1,1621147014,,"\\<parse\\>"
??tabs
|2,1,1621147014,63,"tabs"
??tab
|2,1,1621147014,63,"tab"
? \<.\>
|2,1,1621147014,,"\\<.\\>"
? .
|2,1,1621147014,,"."
?/*
|2,1,1621147014,47,"*"
? @$
|2,1,1621147014,,"@$"
??wv
|2,1,1621147014,63,"wv"
? \<:autocmd\>
|2,1,1621147014,,"\\<:autocmd\\>"
??jkkkkkkkkkk
|2,1,1621147014,63,"jkkkkkkkkkk"
? \<i\>
|2,1,1621147014,,"\\<i\\>"
??registers
|2,1,1621147014,63,"registers"
??-rv
|2,1,1621147014,63,"-rv"
??rv
|2,1,1621147014,63,"rv"
? \<-rv\>
|2,1,1621147014,,"\\<-rv\\>"
??bufnew
|2,1,1621147014,63,"bufnew"
??buff
|2,1,1621147014,63,"buff"
? \<viminfo-file\>
|2,1,1621147014,,"\\<viminfo-file\\>"
? \<session-file\>
|2,1,1621147014,,"\\<session-file\\>"
? eqns
|2,1,1621147014,,"eqns"
??:rv
|2,1,1621147014,63,":rv"
? \<k\>
|2,1,1621147014,,"\\<k\\>"

# Expression History (newest to oldest):
=10 * 20 + 5
|2,2,1621147014,,"10 * 20 + 5"
=100 * 50 + 20
|2,2,1621147014,,"100 * 50 + 20"
=100 * 50 + 10
|2,2,1621147014,,"100 * 50 + 10"
=p
|2,2,1621147014,,"p"

# Input Line History (newest to oldest):
@p class = root>
|2,3,1621147014,,"p class = root>"
@printf
|2,3,1621147014,,"printf"
@p class="hello world">
|2,3,1621147014,,"p class=\"hello world\">"
@depend
|2,3,1621147014,,"depend"
@build_depend>
|2,3,1621147014,,"build_depend>"
@exev_depend>
|2,3,1621147014,,"exev_depend>"
@depend>
|2,3,1621147014,,"depend>"
@buildtool_depend>
|2,3,1621147014,,"buildtool_depend>"
@exec_depend>
|2,3,1621147014,,"exec_depend>"
@member_of_group>
|2,3,1621147014,,"member_of_group>"
@p>
|2,3,1621147014,,"p>"
@[{y(es)},n(o),a(ll),q(uit)] y
|2,3,1621147014,,"[{y(es)},n(o),a(ll),q(uit)] y"
@print
|2,3,1621147014,,"print"
@list
|2,3,1621147014,,"list"
@dict
|2,3,1621147014,,"dict"

# Debug Line History (newest to oldest):

# Registers:
"0	CHAR	0
	MODULE_H
|3,0,0,0,1,0,1621146912,"MODULE_H"
""1	LINE	0
	:wv! ~/.vim/info/.hinfo.vim
|3,1,1,1,1,0,1621146991,":wv! ~/.vim/info/.hinfo.vim"
"2	LINE	0
	/*
	 * File Name: module.h
	 * Date of Creation: Sun 16 May 2021 10:45:30
	 * Author: Josiah Tan
	 * Description: 
	*/
	
	
	#ifndef MODULE_H
	#define MODULE_H
	
	
	
	
	
	
	
	
	
	
	
	#endif
|3,0,2,1,22,0,1621146910,"/*"," * File Name: module.h"," * Date of Creation: Sun 16 May 2021 10:45:30"," * Author: Josiah Tan"," * Description: ","*/","","","#ifndef MODULE_H","#define MODULE_H","","","","","","","","","","","","#endif"
"3	LINE	0
	/*
	 * File Name: module.h
	 * Date of Creation: Sat 15 May 2021 22:01:11
	 * Author: Josiah Tan
	 * Description: 
	*/
	
	
	#ifndef MODULE_H
	#define MODULE_H
	
	
	
	
	
	
	
	
	
	
	
	#endif
|3,0,3,1,22,0,1621080077,"/*"," * File Name: module.h"," * Date of Creation: Sat 15 May 2021 22:01:11"," * Author: Josiah Tan"," * Description: ","*/","","","#ifndef MODULE_H","#define MODULE_H","","","","","","","","","","","","#endif"
"4	LINE	0
	#ifndef MODULE_H
	#define MODULE_H
	
	
	
	
	
	
	
	
	
	
	
	#endif
|3,0,4,1,14,0,1621079860,"#ifndef MODULE_H","#define MODULE_H","","","","","","","","","","","","#endif"
"5	LINE	0
	#ifndef MODULE_H
	#define MODULE_H
	
	
	
	
	
	
	
	
	
	
	
	
|3,0,5,1,14,0,1621079796,"#ifndef MODULE_H","#define MODULE_H","","","","","","","","","","","",""
"6	LINE	0
	#ifndef MODULE_H
	#define MODULE_H
	
	
	
	
	
	
	
	
	
	
	
	#endif
|3,0,6,1,14,0,1621079788,"#ifndef MODULE_H","#define MODULE_H","","","","","","","","","","","","#endif"
"7	LINE	0
	#ifndef MODULE_H
	#define MODULE_H
	
	#endif
	
	
	
	
	
|3,0,7,1,9,0,1621079673,"#ifndef MODULE_H","#define MODULE_H","","#endif","","","","",""
"8	LINE	0
	#ifndef MAIN_C
	#define MAIN_C
	
	
	
	
	
	#endif
	
|3,0,8,1,9,0,1621079606,"#ifndef MAIN_C","#define MAIN_C","","","","","","#endif",""
"9	LINE	0
	/*
	 * File Name: main.c
	 * Date of Creation: Sat 15 May 2021 21:36:00
	 * Author: Josiah Tan
	 * Description: 
	*/
	
	
	#include<stdio.h>
	#include<stdlib.h>
	#include<limits.h>
	
	
	
	int main(void){
		int T=9, n=3, m=2;
	
		return 0;
	}
	
	
	
	ggO/*File Name: €ýa:let @l€kb" = expand("%")poDatw€kbe of Cration€kl€kl€kl€kl€kle€ýaA: €ýa:put = strftime('%c')kJoAuthor: Josiah TanDescription: €kb€kb€kb*/€ýa
|3,0,9,1,23,0,1621079526,"/*"," * File Name: main.c"," * Date of Creation: Sat 15 May 2021 21:36:00"," * Author: Josiah Tan"," * Description: ","*/","","","#include<stdio.h>","#include<stdlib.h>","#include<limits.h>","","","","int main(void){","	int T=9, n=3, m=2;","","	return 0;","}","","","",>176
|<"ggO/*File Name: €ýa:let @l€kb\" = expand(\"%\")poDatw€kbe of Cration€kl€kl€kl€kl€kle€ýaA: €ýa:put = strftime('%c')kJoAuthor: Josiah TanDescription: €kb€kb€kb*/€ýa"
"a	CHAR	0
	i €ýak
|3,0,10,0,1,0,1612342066,"i €ýak"
"b	CHAR	0
	i#include<stdio.h>#include<stdlib.h>#include<limits.h>int main(void){€ýaOretrnreturn 0;€ýak
|3,0,11,0,1,0,1621078513,"i#include<stdio.h>#include<stdlib.h>#include<limits.h>int main(void){€ýaOretrnreturn 0;€ýak"
"c	LINE	0
	#include<stdio.h>
	#include<stdlib.h>
	#include<limits.h>
	
	
	int main(void){
		return 0;
	}
	
	
|3,0,12,1,10,0,1620963634,"#include<stdio.h>","#include<stdlib.h>","#include<limits.h>","","","int main(void){","	return 0;","}","",""
"d	CHAR	0
	@g@h
|3,0,13,0,1,0,1621080074,"@g@h"
"e	CHAR	0
	$i&&€ýa
|3,0,14,0,1,0,1614340553,"$i&&€ýa"
"f	CHAR	0
	ggO/*File AneName: €ýa:put = let @" = ep€kbxpand("%")poDate of Creation: €ýa:put = explore("strftime("€kb'%c')kJoAuthor: Josiah Tan€kb€kb€kb*/€ýa
|3,0,15,0,1,0,1620986375,"ggO/*File AneName: €ýa:put = let @\" = ep€kbxpand(\"%\")poDate of Creation: €ýa:put = explore(\"strftime(\"€kb'%c')kJoAuthor: Josiah Tan€kb€kb€kb*/€ýa"
"g	CHAR	0
	i#ifndef €ýa:let @" ex€kb€kb=expand("%")pF.r_viWUviwyo#define €ýapo€ýaG10o€ýao#endif€ýa9k
|3,0,16,0,1,0,1621079858,"i#ifndef €ýa:let @\" ex€kb€kb=expand(\"%\")pF.r_viWUviwyo#define €ýapo€ýaG10o€ýao#endif€ýa9k"
"h	LINE	0
	ggO/*File Name: €ýa:let @l€kb" = expand("%")poDatw€kbe of Cration€kl€kl€kl€kl€kle€ýaA: €ýa:put = strftime('%c')kJoAuthor: Josiah TanDescription: €kb€kb€kb*/€ýa
|3,0,17,1,1,0,1621079188,"ggO/*File Name: €ýa:let @l€kb\" = expand(\"%\")poDatw€kbe of Cration€kl€kl€kl€kl€kle€ýaA: €ýa:put = strftime('%c')kJoAuthor: Josiah TanDescription: €kb€kb€kb*/€ýa"
"i	CHAR	0
	Sfor (int i=0;i<n;i++){€ýaO€ýa
|3,0,18,0,1,0,1620986139,"Sfor (int i=0;i<n;i++){€ýaO€ýa"
"j	CHAR	0
	Sfor (int j=0;j<m;j++){€ýaO€ýa
|3,0,19,0,1,0,1620986173,"Sfor (int j=0;j<m;j++){€ýaO€ýa"
"l	CHAR	0
	f,i: Ar€kb€ýal
|3,0,21,0,1,0,1613564205,"f,i: Ar€kb€ýal"
"m	CHAR	0
	:tabnew Mae€kbkei€kbfiletabnew Makefile:%diall: ./a.outcat 1.in | ./a.ou€kb€kbout./a.out: main.cpp€kb€kbg++ mainc€kb.cp€kb€ýa
|3,0,22,0,1,0,1620986862,":tabnew Mae€kbkei€kbfiletabnew Makefile:%diall: ./a.outcat 1.in | ./a.ou€kb€kbout./a.out: main.cpp€kb€kbg++ mainc€kb.cp€kb€ýa"
"n	LINE	0
	Josiah Tan
|3,0,23,1,1,0,1620984417,"Josiah Tan"
"p	LINE	0
	#include<iostream>
	#include<vector>
	#include<climits>
	
	
	int main(void){
		return 0;
	}
	
|3,0,25,1,9,0,1620959626,"#include<iostream>","#include<vector>","#include<climits>","","","int main(void){","	return 0;","}",""
"q	CHAR	0
	igoodbye world€ýa
|3,0,26,0,1,0,1621002658,"igoodbye world€ýa"
"r	CHAR	0
	:!gcc % && ./a.out
|3,0,27,0,1,0,1621074808,":!gcc % && ./a.out"
"s	CHAR	0
	f,geysiw"f,
|3,0,28,0,1,0,1613478510,"f,geysiw\"f,"
"t	CHAR	0
	othis is supposed to only go in the c file€ýa
|3,0,29,0,1,0,1621058753,"othis is supposed to only go in the c file€ýa"
"u	CHAR	0
	^veUk
|3,0,30,0,1,0,1613212860,"^veUk"
"v@	LINE	0
	:wv! ~/.vim/info/.hinfo.vim
|3,2,31,1,1,0,1621146989,":wv! ~/.vim/info/.hinfo.vim"
"w	CHAR	0
	thii€kbti€kb€kbthis is a program that copies registtakprints what is in register w t€kb€kb€kbq twice€ýa@w@q@q
|3,0,32,0,1,0,1620987224,"thii€kbti€kb€kbthis is a program that copies registtakprints what is in register w t€kb€kb€kbq twice€ýa@w@q@q"
"-	CHAR	0
	main.c
|3,0,36,0,1,0,1621079609,"main.c"

# global variables:

# File marks:
'P  2  20  ~/Desktop/josiah_folder/nand2tetris/projects/07/StackArithmetic/SimpleAdd/SimpleAdd.asm
|4,80,2,20,1613618169,"~/Desktop/josiah_folder/nand2tetris/projects/07/StackArithmetic/SimpleAdd/SimpleAdd.asm"
'V  43  0  ~/.vimrc
|4,86,43,0,1612532244,"~/.vimrc"
'0  12  0  ~/Desktop/josiah_folder/vim/vimvscode/module.h
|4,48,12,0,1621147016,"~/Desktop/josiah_folder/vim/vimvscode/module.h"
'1  13  0  ~/Desktop/josiah_folder/vim/vimvscode/module.h
|4,49,13,0,1621146992,"~/Desktop/josiah_folder/vim/vimvscode/module.h"
'2  13  0  ~/Desktop/josiah_folder/vim/vimvscode/module.h
|4,50,13,0,1621146992,"~/Desktop/josiah_folder/vim/vimvscode/module.h"
'3  2  0  ~/Desktop/josiah_folder/vim/vimvscode/main.c
|4,51,2,0,1621146846,"~/Desktop/josiah_folder/vim/vimvscode/main.c"
'4  2  0  ~/Desktop/josiah_folder/vim/vimvscode/main.c
|4,52,2,0,1621146846,"~/Desktop/josiah_folder/vim/vimvscode/main.c"
'5  1  0  ~/Desktop/josiah_folder/vim/vimvscode/mian.c
|4,53,1,0,1621146831,"~/Desktop/josiah_folder/vim/vimvscode/mian.c"
'6  1  0  ~/Desktop/josiah_folder/vim/vimvscode/mian.c
|4,54,1,0,1621146831,"~/Desktop/josiah_folder/vim/vimvscode/mian.c"
'7  2  0  ~/Desktop/josiah_folder/vim/vimvscode/main.c
|4,55,2,0,1621146828,"~/Desktop/josiah_folder/vim/vimvscode/main.c"
'8  2  0  ~/Desktop/josiah_folder/vim/vimvscode/main.c
|4,56,2,0,1621146828,"~/Desktop/josiah_folder/vim/vimvscode/main.c"
'9  69  0  ~/.vim/vimrc
|4,57,69,0,1621146794,"~/.vim/vimrc"

# Jumplist (newest first):
-'  12  0  ~/Desktop/josiah_folder/vim/vimvscode/module.h
|4,39,12,0,1621147016,"~/Desktop/josiah_folder/vim/vimvscode/module.h"
-'  1  0  ~/Desktop/josiah_folder/vim/vimvscode/main.py
|4,39,1,0,1621147014,"~/Desktop/josiah_folder/vim/vimvscode/main.py"
-'  13  0  ~/Desktop/josiah_folder/vim/vimvscode/module.h
|4,39,13,0,1621146992,"~/Desktop/josiah_folder/vim/vimvscode/module.h"
-'  1  0  ~/Desktop/josiah_folder/vim/vimvscode/module.h
|4,39,1,0,1621146915,"~/Desktop/josiah_folder/vim/vimvscode/module.h"
-'  22  0  ~/Desktop/josiah_folder/vim/vimvscode/module.h
|4,39,22,0,1621146913,"~/Desktop/josiah_folder/vim/vimvscode/module.h"
-'  23  21  ~/Desktop/josiah_folder/vim/vimvscode/main.py
|4,39,23,21,1621146898,"~/Desktop/josiah_folder/vim/vimvscode/main.py"
-'  27  0  ~/Desktop/josiah_folder/vim/vimvscode/main.c
|4,39,27,0,1621146894,"~/Desktop/josiah_folder/vim/vimvscode/main.c"
-'  2  0  ~/Desktop/josiah_folder/vim/vimvscode/main.c
|4,39,2,0,1621146848,"~/Desktop/josiah_folder/vim/vimvscode/main.c"
-'  1  0  ~/Desktop/josiah_folder/vim/vimvscode/mian.c
|4,39,1,0,1621146831,"~/Desktop/josiah_folder/vim/vimvscode/mian.c"
-'  23  3  ~/Desktop/josiah_folder/vim/vimvscode/main.c
|4,39,23,3,1621146812,"~/Desktop/josiah_folder/vim/vimvscode/main.c"
-'  1  0  ~/Desktop/josiah_folder/vim/vimvscode/main.c
|4,39,1,0,1621146811,"~/Desktop/josiah_folder/vim/vimvscode/main.c"
-'  22  4  ~/Desktop/josiah_folder/vim/vimvscode/main.c
|4,39,22,4,1621146811,"~/Desktop/josiah_folder/vim/vimvscode/main.c"
-'  21  5  ~/Desktop/josiah_folder/vim/vimvscode/main.c
|4,39,21,5,1621146808,"~/Desktop/josiah_folder/vim/vimvscode/main.c"
-'  69  0  ~/.vim/vimrc
|4,39,69,0,1621146794,"~/.vim/vimrc"
-'  59  0  ~/.vim/vimrc
|4,39,59,0,1621146785,"~/.vim/vimrc"
-'  1  0  ~/.vim/vimrc
|4,39,1,0,1621146743,"~/.vim/vimrc"
-'  14  10  ~/Desktop/josiah_folder/vim/vimvscode/main.py
|4,39,14,10,1621125859,"~/Desktop/josiah_folder/vim/vimvscode/main.py"
-'  11  0  ~/Desktop/josiah_folder/vim/vimvscode/main.py
|4,39,11,0,1621125838,"~/Desktop/josiah_folder/vim/vimvscode/main.py"
-'  12  0  ~/Desktop/josiah_folder/vim/vimvscode/main.py
|4,39,12,0,1621125838,"~/Desktop/josiah_folder/vim/vimvscode/main.py"
-'  54  0  ~/Desktop/josiah_folder/py3/solve_sim/solve.py
|4,39,54,0,1621081543,"~/Desktop/josiah_folder/py3/solve_sim/solve.py"
-'  54  0  ~/Desktop/josiah_folder/py3/solve_sim/solve.py
|4,39,54,0,1621081543,"~/Desktop/josiah_folder/py3/solve_sim/solve.py"
-'  54  0  ~/Desktop/josiah_folder/py3/solve_sim/solve.py
|4,39,54,0,1621081543,"~/Desktop/josiah_folder/py3/solve_sim/solve.py"
-'  51  37  ~/Desktop/josiah_folder/py3/solve_sim/solve.py
|4,39,51,37,1621081430,"~/Desktop/josiah_folder/py3/solve_sim/solve.py"
-'  51  37  ~/Desktop/josiah_folder/py3/solve_sim/solve.py
|4,39,51,37,1621081430,"~/Desktop/josiah_folder/py3/solve_sim/solve.py"
-'  51  37  ~/Desktop/josiah_folder/py3/solve_sim/solve.py
|4,39,51,37,1621081430,"~/Desktop/josiah_folder/py3/solve_sim/solve.py"
-'  1  0  ~/Desktop/josiah_folder/py3/solve_sim/solve.py
|4,39,1,0,1621081352,"~/Desktop/josiah_folder/py3/solve_sim/solve.py"
-'  1  0  ~/Desktop/josiah_folder/py3/solve_sim/solve.py
|4,39,1,0,1621081352,"~/Desktop/josiah_folder/py3/solve_sim/solve.py"
-'  1  0  ~/Desktop/josiah_folder/py3/solve_sim/solve.py
|4,39,1,0,1621081352,"~/Desktop/josiah_folder/py3/solve_sim/solve.py"
-'  21  0  ~/Desktop/josiah_folder/py3/solve_sim/main.c
|4,39,21,0,1621081346,"~/Desktop/josiah_folder/py3/solve_sim/main.c"
-'  21  0  ~/Desktop/josiah_folder/py3/solve_sim/main.c
|4,39,21,0,1621081346,"~/Desktop/josiah_folder/py3/solve_sim/main.c"
-'  21  0  ~/Desktop/josiah_folder/py3/solve_sim/main.c
|4,39,21,0,1621081346,"~/Desktop/josiah_folder/py3/solve_sim/main.c"
-'  26  9  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,26,9,1621081331,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  26  9  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,26,9,1621081331,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  26  9  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,26,9,1621081331,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  25  1  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,25,1,1621081328,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  25  1  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,25,1,1621081328,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  25  1  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,25,1,1621081328,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  23  23  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,23,23,1621081280,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  23  23  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,23,23,1621081280,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  23  23  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,23,23,1621081280,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  8  0  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,8,0,1621081184,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  21  5  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,21,5,1621081184,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  8  0  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,8,0,1621081184,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  21  5  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,21,5,1621081184,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  8  0  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,8,0,1621081184,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  21  5  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,21,5,1621081184,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  9  0  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,9,0,1621081175,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  9  0  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,9,0,1621081175,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  9  0  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,9,0,1621081175,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  32  15  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,32,15,1621081162,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  32  15  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,32,15,1621081162,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  32  15  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,32,15,1621081162,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  16  0  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,16,0,1621081118,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  38  26  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,38,26,1621081118,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  16  0  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,16,0,1621081118,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  38  26  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,38,26,1621081118,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  16  0  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,16,0,1621081118,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  38  26  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,38,26,1621081118,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  31  5  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,31,5,1621081115,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  31  5  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,31,5,1621081115,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  31  5  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,31,5,1621081115,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  1  0  ~/.cppinfo.vim
|4,39,1,0,1621081108,"~/.cppinfo.vim"
-'  1  0  ~/.cppinfo.vim
|4,39,1,0,1621081108,"~/.cppinfo.vim"
-'  1  0  ~/.cppinfo.vim
|4,39,1,0,1621081108,"~/.cppinfo.vim"
-'  52  0  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,52,0,1621081095,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  52  0  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,52,0,1621081095,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  52  0  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,52,0,1621081095,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  17  0  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,17,0,1621081067,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  17  0  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,17,0,1621081067,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  17  0  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,17,0,1621081067,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  44  0  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,44,0,1621081060,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  30  0  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,30,0,1621081060,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  44  0  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,44,0,1621081060,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  30  0  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,30,0,1621081060,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  44  0  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,44,0,1621081060,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  30  0  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,30,0,1621081060,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  58  40  ~/.vimrc
|4,39,58,40,1621080664,"~/.vimrc"
-'  58  40  ~/.vimrc
|4,39,58,40,1621080664,"~/.vimrc"
-'  58  40  ~/.vimrc
|4,39,58,40,1621080664,"~/.vimrc"
-'  22  0  ~/Desktop/josiah_folder/py3/solve_sim/main.c
|4,39,22,0,1621080362,"~/Desktop/josiah_folder/py3/solve_sim/main.c"
-'  22  0  ~/Desktop/josiah_folder/py3/solve_sim/main.c
|4,39,22,0,1621080362,"~/Desktop/josiah_folder/py3/solve_sim/main.c"
-'  22  0  ~/Desktop/josiah_folder/py3/solve_sim/main.c
|4,39,22,0,1621080362,"~/Desktop/josiah_folder/py3/solve_sim/main.c"
-'  17  0  ~/Desktop/josiah_folder/py3/solve_sim/main.c
|4,39,17,0,1621080296,"~/Desktop/josiah_folder/py3/solve_sim/main.c"

# History of marks within files (newest to oldest):

> ~/Desktop/josiah_folder/vim/vimvscode/main.c
	*	1621146886	0
	"	27	0
	.	1	0
	+	26	9
	+	16	0
	+	7	0
	+	16	17
	+	17	23
	+	18	24
	+	19	25
	+	20	26
	+	21	0
	+	20	0
	+	21	27
	+	1	0

> ~/Desktop/josiah_folder/vim/vimvscode/main.py
	*	1621147011	0
	"	1	0
	.	1	0
	+	10	0
	+	15	9
	+	14	10
	+	18	4
	+	18	21
	+	20	16
	+	21	0
	+	23	4
	+	23	21
	+	1	0

> ~/Desktop/josiah_folder/vim/vimvscode/module.h
	*	1621147016	0
	"	12	0
	.	13	0
	+	1	8
	+	1	5
	+	1	0
	+	1	8
	+	1	0
	+	13	0
	+	1	8
	+	1	5
	+	1	0
	+	1	8
	+	1	0
	+	13	0
