# This viminfo file was generated by Vim 8.1.
# You may edit it if you are careful!

# Viminfo version
|1,4

# Value of 'encoding' when this file was written
*encoding=utf-8


# hlsearch on (H) or off (h):
~h
# Last Search Pattern:
~MSle0~/eqns

# Last Substitute Search Pattern:
~MSle0&eqns

# Last Substitute String:
$eqs

# Command Line History (newest to oldest):
:tabf main.py
|2,0,1621147172,,"tabf main.py"
:tabnew mod.h
|2,0,1621147172,,"tabnew mod.h"
:s/\<j\>/k/g
|2,0,1621147172,,"s/\\<j\\>/k/g"
:vsplit main.c
|2,0,1621147172,,"vsplit main.c"
:%s/hello/goodbye/g
|2,0,1621147172,,"%s/hello/goodbye/g"
:vsplit intro.txt
|2,0,1621147172,,"vsplit intro.txt"
:s/\<b\>/cd/g
|2,0,1621147172,,"s/\\<b\\>/cd/g"
:s/a/ab/g
|2,0,1621147172,,"s/a/ab/g"
:s/\<cd\>/b/g
|2,0,1621147172,,"s/\\<cd\\>/b/g"
:s/\<ab\>/a/g
|2,0,1621147172,,"s/\\<ab\\>/a/g"
:let @" =expand("%")
|2,0,1621147172,,"let @\" =expand(\"%\")"
:tabm2
|2,0,1621147172,,"tabm2"
:%d
|2,0,1621147172,,"%d"
:reg d
|2,0,1621147172,,"reg d"
:wv! ~/.hinfo.vim
|2,0,1621147172,,"wv! ~/.hinfo.vim"
:s/hey/Hey/g
|2,0,1621147172,,"s/hey/Hey/g"
:wv ~/.pyinfo.vim
|2,0,1621147172,,"wv ~/.pyinfo.vim"
:!python3 %
|2,0,1621147172,,"!python3 %"
:help Session
|2,0,1621147172,,"help Session"
:python3 %
|2,0,1621147172,,"python3 %"
:scripnames
|2,0,1621147172,,"scripnames"
:%y*
|2,0,1621147172,,"%y*"
:checkhealth
|2,0,1621147172,,"checkhealth"
:Helptags
|2,0,1621147172,,"Helptags"
:tabnew first_vim.py
|2,0,1621147172,,"tabnew first_vim.py"
:version
|2,0,1621147172,,"version"
:set wrap
|2,0,1621147172,,"set wrap"
:set breakindent
|2,0,1621147172,,"set breakindent"
:set formatoptions=l
|2,0,1621147172,,"set formatoptions=l"
:set lbr
|2,0,1621147172,,"set lbr"
:foldmethod=syntax
|2,0,1621147172,,"foldmethod=syntax"
:set foldmethod=syntax
|2,0,1621147172,,"set foldmethod=syntax"
:help folding
|2,0,1621147172,,"help folding"
:w !python
|2,0,1621147172,,"w !python"
:w !python3
|2,0,1621147172,,"w !python3"
:tabnew subscriber_member_function2.cpp
|2,0,1621147172,,"tabnew subscriber_member_function2.cpp"
:tabf ../
|2,0,1621147172,,"tabf ../"
:tabf ../CMakeLists.txt
|2,0,1621147172,,"tabf ../CMakeLists.txt"
:h find
|2,0,1621147172,,"h find"
:h expandtab
|2,0,1621147172,,"h expandtab"
:set expandtab 2
|2,0,1621147172,,"set expandtab 2"
:set expandtab=2
|2,0,1621147172,,"set expandtab=2"
:vim ~/.vimrc
|2,0,1621147172,,"vim ~/.vimrc"
:set shiftwidth=4
|2,0,1621147172,,"set shiftwidth=4"
:h tabstop
|2,0,1621147172,,"h tabstop"
:h shiftwidth()
|2,0,1621147172,,"h shiftwidth()"
:h shiftwidth
|2,0,1621147172,,"h shiftwidth"
:findf ~/.vimrc
|2,0,1621147172,,"findf ~/.vimrc"
:tabf CMakeLists.txt
|2,0,1621147172,,"tabf CMakeLists.txt"
:tabf ..
|2,0,1621147172,,"tabf .."
:tabnew src/publish_address_book.cpp
|2,0,1621147172,,"tabnew src/publish_address_book.cpp"
:tabf package.xml
|2,0,1621147172,,"tabf package.xml"
:tabf msg/AddressBook.msg
|2,0,1621147172,,"tabf msg/AddressBook.msg"
:tabf src/publish_address_book.cpp
|2,0,1621147172,,"tabf src/publish_address_book.cpp"
:s/MAX/MIN/g
|2,0,1621147172,,"s/MAX/MIN/g"
:set tabstop=4
|2,0,1621147172,,"set tabstop=4"
:set tabstop=2
|2,0,1621147172,,"set tabstop=2"
:set shiftwidth=2
|2,0,1621147172,,"set shiftwidth=2"
:tabf ../*4/*.cpp
|2,0,1621147172,,"tabf ../*4/*.cpp"
:%s/R/
|2,0,1621147172,,"%s/R/"
:%s/R/v/gc
|2,0,1621147172,,"%s/R/v/gc"
:set nopaste
|2,0,1621147172,,"set nopaste"
:s/v/root/g
|2,0,1621147172,,"s/v/root/g"
:s/v/T->root/g
|2,0,1621147172,,"s/v/T->root/g"
:tabf ../4_set_range_sum/set_range_sum.cpp
|2,0,1621147172,,"tabf ../4_set_range_sum/set_range_sum.cpp"
:%s/vector<list/list<list/gc
|2,0,1621147172,,"%s/vector<list/list<list/gc"
:wqwa
|2,0,1621147172,,"wqwa"
:Wq
|2,0,1621147172,,"Wq"
:s/std::pair<long long, int>/ipair/gc
|2,0,1621147172,,"s/std::pair<long long, int>/ipair/gc"
:scriptnames
|2,0,1621147172,,"scriptnames"
:wq!
|2,0,1621147172,,"wq!"
:w!
|2,0,1621147172,,"w!"
:tabf /usr/share/vim/vimrc
|2,0,1621147172,,"tabf /usr/share/vim/vimrc"
:h next
|2,0,1621147172,,"h next"
:mksession sess.vim
|2,0,1621147172,,"mksession sess.vim"
:tabf ./sess.vim
|2,0,1621147172,,"tabf ./sess.vim"
:Vtabnew hello.cpp
|2,0,1621147172,,"Vtabnew hello.cpp"
:split file2
|2,0,1621147172,,"split file2"
:hsplit hello.cpp
|2,0,1621147172,,"hsplit hello.cpp"
:vsplit yo.cpp
|2,0,1621147172,,"vsplit yo.cpp"
:!man cout
|2,0,1621147172,,"!man cout"
:!man std::cout 
|2,0,1621147172,,"!man std::cout "
:!man vim
|2,0,1621147172,,"!man vim"
:tabf ~/.vim/
|2,0,1621147172,,"tabf ~/.vim/"
:tabf /etc/vim/vimrc
|2,0,1621147172,,"tabf /etc/vim/vimrc"
:tabf make
|2,0,1621147172,,"tabf make"
:make test2
|2,0,1621147172,,"make test2"
:make test3
|2,0,1621147172,,"make test3"
:mkae
|2,0,1621147172,,"mkae"
:%s/c/
|2,0,1621147172,,"%s/c/"
:source
|2,0,1621147172,,"source"
:make test
|2,0,1621147172,,"make test"
:male
|2,0,1621147172,,"male"
:mae
|2,0,1621147172,,"mae"
:ake
|2,0,1621147172,,"ake"
:s/i/x/gc
|2,0,1621147172,,"s/i/x/gc"
:tabnew 3.in
|2,0,1621147172,,"tabnew 3.in"
:make 3
|2,0,1621147172,,"make 3"
:tabnew 4.in
|2,0,1621147172,,"tabnew 4.in"
:make 4
|2,0,1621147172,,"make 4"
:tabnew 5.in
|2,0,1621147172,,"tabnew 5.in"
:make 5
|2,0,1621147172,,"make 5"
:source S
|2,0,1621147172,,"source S"
:tabnew 1.in Makefile -p
|2,0,1621147172,,"tabnew 1.in Makefile -p"
:make1
|2,0,1621147172,,"make1"
:tabf Session.vim
|2,0,1621147172,,"tabf Session.vim"
:ls
|2,0,1621147172,,"ls"
:cd ..
|2,0,1621147172,,"cd .."
:time
|2,0,1621147172,,"time"
:type -a time
|2,0,1621147172,,"type -a time"
:mksession prim.vim
|2,0,1621147172,,"mksession prim.vim"
:tabf 1.in 2.in
|2,0,1621147172,,"tabf 1.in 2.in"
:source prim.vim
|2,0,1621147172,,"source prim.vim"
:make all
|2,0,1621147172,,"make all"
:%s/\\/ /gc
|2,0,1621147172,,"%s/\\\\/ /gc"
:make prim
|2,0,1621147172,,"make prim"
:amke
|2,0,1621147172,,"amke"
:%s/bfs/dfs/gc
|2,0,1621147172,,"%s/bfs/dfs/gc"
:! HardwareSimulator And.tst
|2,0,1621147172,,"! HardwareSimulator And.tst"
:tabf Not.hdl
|2,0,1621147172,,"tabf Not.hdl"
:! HardwareSimulator Or.tst
|2,0,1621147172,,"! HardwareSimulator Or.tst"
:! HardwareSimulator Xor.tst
|2,0,1621147172,,"! HardwareSimulator Xor.tst"
:s/s/sel/g
|2,0,1621147172,,"s/s/sel/g"
:! HardwareSimulator Mux.tst
|2,0,1621147172,,"! HardwareSimulator Mux.tst"
:s/sel/in/g
|2,0,1621147172,,"s/sel/in/g"
:! HardwareSimulator DMux.tst
|2,0,1621147172,,"! HardwareSimulator DMux.tst"
:! HardwareSimulator Not16.tst
|2,0,1621147172,,"! HardwareSimulator Not16.tst"
:!HardwareSimulator And.tst
|2,0,1621147172,,"!HardwareSimulator And.tst"
:!HardwareSimulator Or16.tst
|2,0,1621147172,,"!HardwareSimulator Or16.tst"
:!HardwareSimulator And16.tst
|2,0,1621147172,,"!HardwareSimulator And16.tst"
:tabf Mux.hdl
|2,0,1621147172,,"tabf Mux.hdl"
:!HardwareSimulator Mux16.tst
|2,0,1621147172,,"!HardwareSimulator Mux16.tst"
:tabf Or.hdl
|2,0,1621147172,,"tabf Or.hdl"
:find
|2,0,1621147172,,"find"
:! HardwareSimulator Mux16.tst
|2,0,1621147172,,"! HardwareSimulator Mux16.tst"
:tabf Mux16.hdl
|2,0,1621147172,,"tabf Mux16.hdl"
:tabf Mux4Way16.cmp
|2,0,1621147172,,"tabf Mux4Way16.cmp"
:tabf Mux4Way16.out
|2,0,1621147172,,"tabf Mux4Way16.out"
:! HardwareSimulator Mux4Way16.tst
|2,0,1621147172,,"! HardwareSimulator Mux4Way16.tst"
:! HardwareSimulator Mux8Way16.tst
|2,0,1621147172,,"! HardwareSimulator Mux8Way16.tst"
:! HardwareSimulator DMux4Way.tst
|2,0,1621147172,,"! HardwareSimulator DMux4Way.tst"
:tabf Mux8Way16.hdl
|2,0,1621147172,,"tabf Mux8Way16.hdl"
:tabnew Xor16.hdl
|2,0,1621147172,,"tabnew Xor16.hdl"
:%s/And/Xor/gc
|2,0,1621147172,,"%s/And/Xor/gc"
:! HardwareSimulator DMux8Way.tst
|2,0,1621147172,,"! HardwareSimulator DMux8Way.tst"
:s/x/y/g
|2,0,1621147172,,"s/x/y/g"
:s/zx/f/g
|2,0,1621147172,,"s/zx/f/g"
:tabf Add16.hdl
|2,0,1621147172,,"tabf Add16.hdl"
:! HardwareSimulator Add16.hdl
|2,0,1621147172,,"! HardwareSimulator Add16.hdl"
:! HardwareSimulator Add16.tst
|2,0,1621147172,,"! HardwareSimulator Add16.tst"
:! HardwareSimulator Or8Way.hdl
|2,0,1621147172,,"! HardwareSimulator Or8Way.hdl"
:! HardwareSimulator Or8Way.tst
|2,0,1621147172,,"! HardwareSimulator Or8Way.tst"
:! HardwareSimulator ALU.tst
|2,0,1621147172,,"! HardwareSimulator ALU.tst"
:edit main.cpp
|2,0,1621147172,,"edit main.cpp"
:make 1
|2,0,1621147172,,"make 1"
:source Makefile
|2,0,1621147172,,"source Makefile"
:make 1.ini
|2,0,1621147172,,"make 1.ini"
:%s/size/sz/gc
|2,0,1621147172,,"%s/size/sz/gc"
:make !.in
|2,0,1621147172,,"make !.in"
:%s/SortedHeap/sortedHeap/g
|2,0,1621147172,,"%s/SortedHeap/sortedHeap/g"
:make 1.n
|2,0,1621147172,,"make 1.n"
:tabnew reading.cpp
|2,0,1621147172,,"tabnew reading.cpp"
:tabf values.h
|2,0,1621147172,,"tabf values.h"
:tabf reading.cpp
|2,0,1621147172,,"tabf reading.cpp"
:! g++ reading.cpp && cat 1.in | ./a.out
|2,0,1621147172,,"! g++ reading.cpp && cat 1.in | ./a.out"
:%s/visited/dist/g/c
|2,0,1621147172,,"%s/visited/dist/g/c"
:%s/visited/dist/gc
|2,0,1621147172,,"%s/visited/dist/gc"
:! g++ main.cpp && cat 1.in | ./a.out
|2,0,1621147172,,"! g++ main.cpp && cat 1.in | ./a.out"
:! HardwareSimulator Bit.hdl
|2,0,1621147172,,"! HardwareSimulator Bit.hdl"
:! HardwareSimulator Bit.tst
|2,0,1621147172,,"! HardwareSimulator Bit.tst"
:! HardwareSimulator Register.tst
|2,0,1621147172,,"! HardwareSimulator Register.tst"
:! HardwareSimulator RAM8.tst
|2,0,1621147172,,"! HardwareSimulator RAM8.tst"
:tabf Register.hdl
|2,0,1621147172,,"tabf Register.hdl"
:tabf Bit.cmp
|2,0,1621147172,,"tabf Bit.cmp"
:tabf Bit.hdl
|2,0,1621147172,,"tabf Bit.hdl"
:ta
|2,0,1621147172,,"ta"
:tabf RAM64.hdl
|2,0,1621147172,,"tabf RAM64.hdl"
:! HardwareSimulator RAM64.tst
|2,0,1621147172,,"! HardwareSimulator RAM64.tst"
:tab ~/.vimrc
|2,0,1621147172,,"tab ~/.vimrc"
:! HardwareSimulator RAM512.tst
|2,0,1621147172,,"! HardwareSimulator RAM512.tst"
:tabf RAM4K.hdl
|2,0,1621147172,,"tabf RAM4K.hdl"
:! HardwareSimulator RAM4K.tst
|2,0,1621147172,,"! HardwareSimulator RAM4K.tst"
:tabf RAM16K.hdl
|2,0,1621147172,,"tabf RAM16K.hdl"
:! HardwareSimulator RAM16K.tst
|2,0,1621147172,,"! HardwareSimulator RAM16K.tst"
:tabf .
|2,0,1621147172,,"tabf ."
:! HardwareSimulator PC.tst
|2,0,1621147172,,"! HardwareSimulator PC.tst"
:tabf Fill.tst
|2,0,1621147172,,"tabf Fill.tst"
:tabf *.tst
|2,0,1621147172,,"tabf *.tst"
:tabf FillAutomatic.tst
|2,0,1621147172,,"tabf FillAutomatic.tst"
:Q!
|2,0,1621147172,,"Q!"
:! HardwareSimulator CPU.tst
|2,0,1621147172,,"! HardwareSimulator CPU.tst"
:! HardwareSimulator Memory.tst
|2,0,1621147172,,"! HardwareSimulator Memory.tst"
:tabf CPU.hdl
|2,0,1621147172,,"tabf CPU.hdl"
:tabf Memory.hdl
|2,0,1621147172,,"tabf Memory.hdl"
:! HardwareSimulator Computer.tst
|2,0,1621147172,,"! HardwareSimulator Computer.tst"
:! HardwareSimulator
|2,0,1621147172,,"! HardwareSimulator"
:%s/Hash/HashTable/gc
|2,0,1621147172,,"%s/Hash/HashTable/gc"
:! HardwareSimulator Mult.tst
|2,0,1621147172,,"! HardwareSimulator Mult.tst"
:make 2.in
|2,0,1621147172,,"make 2.in"
:! g++ main.cpp && cat 2.in | ./a.out
|2,0,1621147172,,"! g++ main.cpp && cat 2.in | ./a.out"
:! g++ main.cpp && ./a.out
|2,0,1621147172,,"! g++ main.cpp && ./a.out"
:! python3 Assembler.py
|2,0,1621147172,,"! python3 Assembler.py"
:find Makefile
|2,0,1621147172,,"find Makefile"
:mks
|2,0,1621147172,,"mks"
:make pong.asm
|2,0,1621147172,,"make pong.asm"
:make add.asm
|2,0,1621147172,,"make add.asm"
:make max
|2,0,1621147172,,"make max"
:make rect
|2,0,1621147172,,"make rect"
:ma
|2,0,1621147172,,"ma"
:make sum
|2,0,1621147172,,"make sum"
:make pong
|2,0,1621147172,,"make pong"
:! ls -la
|2,0,1621147172,,"! ls -la"
:! make rect
|2,0,1621147172,,"! make rect"
:tabf rect/Rect.hack
|2,0,1621147172,,"tabf rect/Rect.hack"
:tabf rect/cmp.hack
|2,0,1621147172,,"tabf rect/cmp.hack"
:tabnew rect/cmp.hack
|2,0,1621147172,,"tabnew rect/cmp.hack"
:! diff rect/Rect.hack rect/cmp.hack
|2,0,1621147172,,"! diff rect/Rect.hack rect/cmp.hack"
:tabf add/Add.hack
|2,0,1621147172,,"tabf add/Add.hack"
:tabnew add/cmp.hack
|2,0,1621147172,,"tabnew add/cmp.hack"
:! diff add/Add.hack add/cmp.hack
|2,0,1621147172,,"! diff add/Add.hack add/cmp.hack"
:! make max
|2,0,1621147172,,"! make max"
:tabf max/Max.hack
|2,0,1621147172,,"tabf max/Max.hack"
:tabnew max/cmp.hack
|2,0,1621147172,,"tabnew max/cmp.hack"
:! diff max/Max.hack max/cmp.hack
|2,0,1621147172,,"! diff max/Max.hack max/cmp.hack"
:! make pong
|2,0,1621147172,,"! make pong"
:tabnew pong/cmp.hack
|2,0,1621147172,,"tabnew pong/cmp.hack"
:! wget https://github.com/jtdowney/nand2tetris/blob/master/06/pong/Pong.hack
|2,0,1621147172,,"! wget https://github.com/jtdowney/nand2tetris/blob/master/06/pong/Pong.hack"
:! mv Pong.hack cmp.hack
|2,0,1621147172,,"! mv Pong.hack cmp.hack"
:mv cmp.hack pong/
|2,0,1621147172,,"mv cmp.hack pong/"
:! mv cmp.hack pong/
|2,0,1621147172,,"! mv cmp.hack pong/"
:! diff pong/Pong.hack pong/cmp.hack
|2,0,1621147172,,"! diff pong/Pong.hack pong/cmp.hack"
:tabf ./pong/cmp.hack
|2,0,1621147172,,"tabf ./pong/cmp.hack"
:! g++ main.cpp -fsanitize=address
|2,0,1621147172,,"! g++ main.cpp -fsanitize=address"
:! cat 1.in | ./a.out
|2,0,1621147172,,"! cat 1.in | ./a.out"
:m!
|2,0,1621147172,,"m!"
:make 1.in
|2,0,1621147172,,"make 1.in"
:! make 1.in
|2,0,1621147172,,"! make 1.in"
:!make 1.in
|2,0,1621147172,,"!make 1.in"
:! python3 integers.py
|2,0,1621147172,,"! python3 integers.py"
:tabf ../StackTest/StackTest.vm
|2,0,1621147172,,"tabf ../StackTest/StackTest.vm"
:tabf ./StackArithmetic/*/*.vm
|2,0,1621147172,,"tabf ./StackArithmetic/*/*.vm"
:args ./StackArithmetic/*/*.vm
|2,0,1621147172,,"args ./StackArithmetic/*/*.vm"
:tabf *.py
|2,0,1621147172,,"tabf *.py"
:mak
|2,0,1621147172,,"mak"
:! python
|2,0,1621147172,,"! python"
:%s/sp/SP/gc
|2,0,1621147172,,"%s/sp/SP/gc"
:tabf ./StackArithmetic/SimpleAdd/SimpleAdd.asm
|2,0,1621147172,,"tabf ./StackArithmetic/SimpleAdd/SimpleAdd.asm"
:makr
|2,0,1621147172,,"makr"
:mark
|2,0,1621147172,,"mark"
:makrs
|2,0,1621147172,,"makrs"
:m
|2,0,1621147172,,"m"
:! make 
|2,0,1621147172,,"! make "
:! make add
|2,0,1621147172,,"! make add"
:tabf pulse/
|2,0,1621147172,,"tabf pulse/"
:! VMEmulator
|2,0,1621147172,,"! VMEmulator"
:explore
|2,0,1621147172,,"explore"
:!py
|2,0,1621147172,,"!py"
:! man split
|2,0,1621147172,,"! man split"
:! make nested
|2,0,1621147172,,"! make nested"
:!ad
|2,0,1621147172,,"!ad"
:! 	. VMTranslator/bin/activate && \	python3 VMTranslator.py FunctionCalls/StaticsTest/Class1.vm && \	deactivate
|2,0,1621147172,,"! 	. VMTranslator/bin/activate && \\	python3 VMTranslator.py FunctionCalls/StaticsTest/Class1.vm && \\	deactivate"
:!. VMTranslator/bin/activate && python3 VMTranslator.py FunctionCalls/StaticsTest/Class1.vm &&  deactivate
|2,0,1621147172,,"!. VMTranslator/bin/activate && python3 VMTranslator.py FunctionCalls/StaticsTest/Class1.vm &&  deactivate"
:tabf ProgramFlow/BasicLoop/BasicLoop.vm
|2,0,1621147172,,"tabf ProgramFlow/BasicLoop/BasicLoop.vm"
:! make basic
|2,0,1621147172,,"! make basic"
:tabf ./ProgramFlow/BasicLoop/BasicLoop.asm
|2,0,1621147172,,"tabf ./ProgramFlow/BasicLoop/BasicLoop.asm"
:tabf ProgramFlow/BasicLoop/*.asm
|2,0,1621147172,,"tabf ProgramFlow/BasicLoop/*.asm"
:! CPUEmulator ./StackArithmetic/SimpleAdd/SimpleAdd.tst
|2,0,1621147172,,"! CPUEmulator ./StackArithmetic/SimpleAdd/SimpleAdd.tst"
:source Session.vim
|2,0,1621147172,,"source Session.vim"
:tabf ../08/VMTranslator.py
|2,0,1621147172,,"tabf ../08/VMTranslator.py"
:!CPUEmulator
|2,0,1621147172,,"!CPUEmulator"
:tabf ./MemoryAccess/PointerTest/PointerTest.asm
|2,0,1621147172,,"tabf ./MemoryAccess/PointerTest/PointerTest.asm"
:!make poiniter
|2,0,1621147172,,"!make poiniter"
:! make stack
|2,0,1621147172,,"! make stack"
:! make all
|2,0,1621147172,,"! make all"
:tabf ../07/VMTranslator.py
|2,0,1621147172,,"tabf ../07/VMTranslator.py"
:foldmethod
|2,0,1621147172,,"foldmethod"
:set foldmethod
|2,0,1621147172,,"set foldmethod"
:help foldmethod
|2,0,1621147172,,"help foldmethod"
:marks
|2,0,1621147172,,"marks"
:! vim ~/.vimrc
|2,0,1621147172,,"! vim ~/.vimrc"
:set foldmethod=manual
|2,0,1621147172,,"set foldmethod=manual"
:18,8fo
|2,0,1621147172,,"18,8fo"
:set codefolding?
|2,0,1621147172,,"set codefolding?"
:set codefold?
|2,0,1621147172,,"set codefold?"
:set foldmethod?
|2,0,1621147172,,"set foldmethod?"
:set foldmethod=expr
|2,0,1621147172,,"set foldmethod=expr"
:18,26fo
|2,0,1621147172,,"18,26fo"
:tabf ./*/*/*.vm
|2,0,1621147172,,"tabf ./*/*/*.vm"
:n ./*/*/*.vm
|2,0,1621147172,,"n ./*/*/*.vm"
:help tab
|2,0,1621147172,,"help tab"
:next ./*/*/*.vm
|2,0,1621147172,,"next ./*/*/*.vm"
:args ./*/*/*.vm
|2,0,1621147172,,"args ./*/*/*.vm"
:tab all
|2,0,1621147172,,"tab all"
:find ./ProgramFlow/
|2,0,1621147172,,"find ./ProgramFlow/"
:! CPUEmulator
|2,0,1621147172,,"! CPUEmulator"
:tabf ./ProgramFlow/BasicLoop/BasicLoop.vm
|2,0,1621147172,,"tabf ./ProgramFlow/BasicLoop/BasicLoop.vm"
:! make fibs
|2,0,1621147172,,"! make fibs"
:tabf ProgramFlow/FibonacciSeries/FibonacciSeries.tst
|2,0,1621147172,,"tabf ProgramFlow/FibonacciSeries/FibonacciSeries.tst"
:tabf ProgramFlow/FibonacciSeries/FibonacciSeries.tst
|2,0,1621147172,,"tabf ProgramFlow/FibonacciSeries/FibonacciSeries.tst"
:tabf FibonacciSeries.asm
|2,0,1621147172,,"tabf FibonacciSeries.asm"
:! python3
|2,0,1621147172,,"! python3"
:make 
|2,0,1621147172,,"make "
:make add
|2,0,1621147172,,"make add"
:make stack
|2,0,1621147172,,"make stack"
:make pointer
|2,0,1621147172,,"make pointer"
:make static
|2,0,1621147172,,"make static"
:! ls
|2,0,1621147172,,"! ls"
:find ./VMTranslator.py
|2,0,1621147172,,"find ./VMTranslator.py"
:! make fibe
|2,0,1621147172,,"! make fibe"
:make basic
|2,0,1621147172,,"make basic"
:tabf ./VMTranslator/
|2,0,1621147172,,"tabf ./VMTranslator/"
:tabf ./FunctionCalls/FibonacciElement/Main.vm
|2,0,1621147172,,"tabf ./FunctionCalls/FibonacciElement/Main.vm"
:make fibs
|2,0,1621147172,,"make fibs"
::q
|2,0,1621147172,,":q"
:tabf ./FunctionCalls/FibonacciElement/FibonacciElement.asm
|2,0,1621147172,,"tabf ./FunctionCalls/FibonacciElement/FibonacciElement.asm"
:tabf ./ProgramFlow/FibonacciSeries/FibonacciSeries.vm
|2,0,1621147172,,"tabf ./ProgramFlow/FibonacciSeries/FibonacciSeries.vm"
:make fibe
|2,0,1621147172,,"make fibe"
:make simple
|2,0,1621147172,,"make simple"
:tabf 
|2,0,1621147172,,"tabf "
:tabf ./FunctionCalls/
|2,0,1621147172,,"tabf ./FunctionCalls/"
:tabf ./FunctionCalls/NestedCall/Sys.vm
|2,0,1621147172,,"tabf ./FunctionCalls/NestedCall/Sys.vm"
:make nest
|2,0,1621147172,,"make nest"
:make nested
|2,0,1621147172,,"make nested"
:make statics
|2,0,1621147172,,"make statics"
:tabf ./FunctionCalls/StaticsTest/Class1.asm
|2,0,1621147172,,"tabf ./FunctionCalls/StaticsTest/Class1.asm"
:tabf ./FunctionCalls/StaticsTest/StaticsTest.asm
|2,0,1621147172,,"tabf ./FunctionCalls/StaticsTest/StaticsTest.asm"
:Explore 
|2,0,1621147172,,"Explore "
:!VMEmulator
|2,0,1621147172,,"!VMEmulator"
:!make statics
|2,0,1621147172,,"!make statics"
:!make fibe
|2,0,1621147172,,"!make fibe"
:!make nested
|2,0,1621147172,,"!make nested"
:!make simple
|2,0,1621147172,,"!make simple"
:!make fibs
|2,0,1621147172,,"!make fibs"
:!make basic
|2,0,1621147172,,"!make basic"
:!make pointer
|2,0,1621147172,,"!make pointer"
:!make static
|2,0,1621147172,,"!make static"
:!make stack
|2,0,1621147172,,"!make stack"
:!make add
|2,0,1621147172,,"!make add"
:'<,'>!
|2,0,1621147172,,"'<,'>!"
:tabnew 1.in
|2,0,1621147172,,"tabnew 1.in"
:W
|2,0,1621147172,,"W"
:1
|2,0,1621147172,,"1"
:Qa
|2,0,1621147172,,"Qa"
::::::::::!
|2,0,1621147172,,":::::::::!"
:tabnew Main.jack
|2,0,1621147172,,"tabnew Main.jack"
:!tabf ../HelloWorld/Main.jack
|2,0,1621147172,,"!tabf ../HelloWorld/Main.jack"
:!JackCompiler ../
|2,0,1621147172,,"!JackCompiler ../"
:tabf ../HelloWorld/Main.jack
|2,0,1621147172,,"tabf ../HelloWorld/Main.jack"
:tabf ../Fraction/Main.jack
|2,0,1621147172,,"tabf ../Fraction/Main.jack"
:tabf ../Average/Main.jack
|2,0,1621147172,,"tabf ../Average/Main.jack"
:tabf ../Fraction/Fraction.jack
|2,0,1621147172,,"tabf ../Fraction/Fraction.jack"
:%s/circle/circle2/gc
|2,0,1621147172,,"%s/circle/circle2/gc"
:tabnew Empty.jack
|2,0,1621147172,,"tabnew Empty.jack"
:tabnew Cross.jack
|2,0,1621147172,,"tabnew Cross.jack"
:tabnew White.jack
|2,0,1621147172,,"tabnew White.jack"
:mksession Session.vim
|2,0,1621147172,,"mksession Session.vim"
::w
|2,0,1621147172,,":w"
:tabnew Cell.jack
|2,0,1621147172,,"tabnew Cell.jack"
:tabnew State.jack
|2,0,1621147172,,"tabnew State.jack"
:Wa
|2,0,1621147172,,"Wa"
:tabf Cell.jack
|2,0,1621147172,,"tabf Cell.jack"
:tabf State.jack
|2,0,1621147172,,"tabf State.jack"
:tabnew TicTac.jack
|2,0,1621147172,,"tabnew TicTac.jack"
:tabnew KeyListener.jack
|2,0,1621147172,,"tabnew KeyListener.jack"
:tabf ./KeyListener.jack
|2,0,1621147172,,"tabf ./KeyListener.jack"
:tabnew GameState.jack
|2,0,1621147172,,"tabnew GameState.jack"
:s/0/2/g
|2,0,1621147172,,"s/0/2/g"
:tabf GameState.jack
|2,0,1621147172,,"tabf GameState.jack"
:! python3 password.py
|2,0,1621147172,,"! python3 password.py"
:qs
|2,0,1621147172,,"qs"
:%s/string/hello/g
|2,0,1621147172,,"%s/string/hello/g"
:tabnew output.txt
|2,0,1621147172,,"tabnew output.txt"
:!make py
|2,0,1621147172,,"!make py"
:ret
|2,0,1621147172,,"ret"
:tabf ~/.vimrc
|2,0,1621147172,,"tabf ~/.vimrc"
:retab!
|2,0,1621147172,,"retab!"
:!autopep8
|2,0,1621147172,,"!autopep8"
:!pip3 install autopep8
|2,0,1621147172,,"!pip3 install autopep8"
:tabm 4
|2,0,1621147172,,"tabm 4"
:!autopep8 -i main.py
|2,0,1621147172,,"!autopep8 -i main.py"
:! make py
|2,0,1621147172,,"! make py"
:! g++ main.c
|2,0,1621147172,,"! g++ main.c"
:tabnew binary_tree.cpp
|2,0,1621147172,,"tabnew binary_tree.cpp"
:tabnew binary_tree.h
|2,0,1621147172,,"tabnew binary_tree.h"
:tabnew parser.h
|2,0,1621147172,,"tabnew parser.h"
:%s/var/val/g
|2,0,1621147172,,"%s/var/val/g"
:tabf ../guess/1.in
|2,0,1621147172,,"tabf ../guess/1.in"
:! xdg-open ../
|2,0,1621147172,,"! xdg-open ../"
:!make i.in
|2,0,1621147172,,"!make i.in"
:! python3 main.py
|2,0,1621147172,,"! python3 main.py"
:!xdg-open .
|2,0,1621147172,,"!xdg-open ."
:s/0/1/g
|2,0,1621147172,,"s/0/1/g"
:s/1/0/g
|2,0,1621147172,,"s/1/0/g"
:.,.+1!
|2,0,1621147172,,".,.+1!"
:! make i.in
|2,0,1621147172,,"! make i.in"
:tabf d.in
|2,0,1621147172,,"tabf d.in"
:tabnew d.in
|2,0,1621147172,,"tabnew d.in"
:! make d.in
|2,0,1621147172,,"! make d.in"
:python3 JackAnalyser.py
|2,0,1621147172,,"python3 JackAnalyser.py"
:!python3 JackAnalyser.py
|2,0,1621147172,,"!python3 JackAnalyser.py"
:! source ./JackAnalyser/bin/activate
|2,0,1621147172,,"! source ./JackAnalyser/bin/activate"
:tabe 
|2,0,1621147172,,"tabe "
:tabf ./ExpressionLessSquare/Main.jack
|2,0,1621147172,,"tabf ./ExpressionLessSquare/Main.jack"
:Explore
|2,0,1621147172,,"Explore"
:! pwd
|2,0,1621147172,,"! pwd"
:!make express
|2,0,1621147172,,"!make express"
:tabnew CodeReader.py
|2,0,1621147172,,"tabnew CodeReader.py"
:tabf jack_tokenizer.py
|2,0,1621147172,,"tabf jack_tokenizer.py"
:!make jack_tokenizer
|2,0,1621147172,,"!make jack_tokenizer"
:tabf ./ExpressionLessSquare/Square.xml
|2,0,1621147172,,"tabf ./ExpressionLessSquare/Square.xml"
:tabf SquareGameT.xml
|2,0,1621147172,,"tabf SquareGameT.xml"
:! diff SquareGameT.JT.xml SquareGameT.xml
|2,0,1621147172,,"! diff SquareGameT.JT.xml SquareGameT.xml"
:! TextComparer
|2,0,1621147172,,"! TextComparer"
:! TextComparer SquareGameT.JT.xml SquareGameT.xml
|2,0,1621147172,,"! TextComparer SquareGameT.JT.xml SquareGameT.xml"
:! TextCompare
|2,0,1621147172,,"! TextCompare"
:tabm 0
|2,0,1621147172,,"tabm 0"
:tabf Square.xml
|2,0,1621147172,,"tabf Square.xml"
:tabf Main.jack
|2,0,1621147172,,"tabf Main.jack"
:g++ lims.cpp && ./a.out
|2,0,1621147172,,"g++ lims.cpp && ./a.out"
:! g++ lims.cpp && ./a.out
|2,0,1621147172,,"! g++ lims.cpp && ./a.out"
:s/a/b/g
|2,0,1621147172,,"s/a/b/g"
:!g++ --version
|2,0,1621147172,,"!g++ --version"
:%/long long/unsigned long long/g
|2,0,1621147172,,"%/long long/unsigned long long/g"
:%s/long long/unsigned long long/g
|2,0,1621147172,,"%s/long long/unsigned long long/g"
:tabf ~
|2,0,1621147172,,"tabf ~"
:%s/long long/int/g
|2,0,1621147172,,"%s/long long/int/g"
:e
|2,0,1621147172,,"e"
:%s/[nx][ny]/[ny][nx]/gc
|2,0,1621147172,,"%s/[nx][ny]/[ny][nx]/gc"
:!g++ main.cpp && cat 1.in | ./a.out
|2,0,1621147172,,"!g++ main.cpp && cat 1.in | ./a.out"
:!g++ main.cpp -fsanitize=address && cat 1.in | ./a.out
|2,0,1621147172,,"!g++ main.cpp -fsanitize=address && cat 1.in | ./a.out"
:!python3 roman.py
|2,0,1621147172,,"!python3 roman.py"
:%/>>/<</g
|2,0,1621147172,,"%/>>/<</g"
:s/>>/<</g
|2,0,1621147172,,"s/>>/<</g"
:tabf
|2,0,1621147172,,"tabf"
:tabnew 2.out
|2,0,1621147172,,"tabnew 2.out"
:!make 2.in
|2,0,1621147172,,"!make 2.in"
:! make 2
|2,0,1621147172,,"! make 2"
:! make
|2,0,1621147172,,"! make"
:tab
|2,0,1621147172,,"tab"
:color industry
|2,0,1621147172,,"color industry"
:color desert
|2,0,1621147172,,"color desert"
:%/ull/ll/g
|2,0,1621147172,,"%/ull/ll/g"
:%s/ull/ll/g
|2,0,1621147172,,"%s/ull/ll/g"
:python
|2,0,1621147172,,"python"
:!cat 1.in | python3 main.py
|2,0,1621147172,,"!cat 1.in | python3 main.py"
:5y
|2,0,1621147172,,"5y"
:tabm 3
|2,0,1621147172,,"tabm 3"
:s/i/t
|2,0,1621147172,,"s/i/t"
:s/i/t/g
|2,0,1621147172,,"s/i/t/g"
:s/ //g
|2,0,1621147172,,"s/ //g"
:!g++ hello_world.cpp && ./a.out
|2,0,1621147172,,"!g++ hello_world.cpp && ./a.out"
:!./a.out
|2,0,1621147172,,"!./a.out"
:s/3/ /g
|2,0,1621147172,,"s/3/ /g"
:s/_3//g
|2,0,1621147172,,"s/_3//g"
:%dp+
|2,0,1621147172,,"%dp+"
:%p+
|2,0,1621147172,,"%p+"
:s/M/j/g
|2,0,1621147172,,"s/M/j/g"
:%v
|2,0,1621147172,,"%v"
:%s/char * str/string str/gc
|2,0,1621147172,,"%s/char * str/string str/gc"
:s/str[i]/c/g
|2,0,1621147172,,"s/str[i]/c/g"
:s/str\[i\]/c/g
|2,0,1621147172,,"s/str\\[i\\]/c/g"
:%s/&str/str/gc
|2,0,1621147172,,"%s/&str/str/gc"
:%s/void/string/gc
|2,0,1621147172,,"%s/void/string/gc"
:k
|2,0,1621147172,,"k"
:!python3 inter
|2,0,1621147172,,"!python3 inter"
:!python3 interleavings.py
|2,0,1621147172,,"!python3 interleavings.py"
:!python3 interleavings.py > output.txt
|2,0,1621147172,,"!python3 interleavings.py > output.txt"
:tabf output.txt
|2,0,1621147172,,"tabf output.txt"
:!python
|2,0,1621147172,,"!python"
:tabf 2.in
|2,0,1621147172,,"tabf 2.in"
:%s/2//gc
|2,0,1621147172,,"%s/2//gc"
:!make 1 && make 2
|2,0,1621147172,,"!make 1 && make 2"
:tabf 2.out
|2,0,1621147172,,"tabf 2.out"
:%s/./a.out/main
|2,0,1621147172,,"%s/./a.out/main"
:%s/.\/a.out/main.g
|2,0,1621147172,,"%s/.\\/a.out/main.g"
:%s/.\/a.out/main/g
|2,0,1621147172,,"%s/.\\/a.out/main/g"
:tabf main.cpp
|2,0,1621147172,,"tabf main.cpp"
:mks Session.vim
|2,0,1621147172,,"mks Session.vim"
:tabf ./shapecolour.p
|2,0,1621147172,,"tabf ./shapecolour.p"
:Wqa
|2,0,1621147172,,"Wqa"
:s/,//g
|2,0,1621147172,,"s/,//g"
:tabf ./main2.cpp
|2,0,1621147172,,"tabf ./main2.cpp"
:!mawke
|2,0,1621147172,,"!mawke"
:!make 
|2,0,1621147172,,"!make "
:!make all
|2,0,1621147172,,"!make all"
:%s/big/b/g
|2,0,1621147172,,"%s/big/b/g"
:%s/small/s/g
|2,0,1621147172,,"%s/small/s/g"
:%s/'/"/g
|2,0,1621147172,,"%s/'/\"/g"
:%s/\'/\"/g
|2,0,1621147172,,"%s/\\'/\\\"/g"
:%s/\â€˜/\'/g
|2,0,1621147172,,"%s/\\â€˜/\\'/g"
:%s/â€˜/'/g
|2,0,1621147172,,"%s/â€˜/'/g"
:%/â€™/'/g
|2,0,1621147172,,"%/â€™/'/g"
:%s/â€™/'/g
|2,0,1621147172,,"%s/â€™/'/g"
:%s/convert/str2int/gc
|2,0,1621147172,,"%s/convert/str2int/gc"
:ewqa
|2,0,1621147172,,"ewqa"
:s/makepair/make_pair/g
|2,0,1621147172,,"s/makepair/make_pair/g"
:%s/\.\/a\.out/main/g
|2,0,1621147172,,"%s/\\.\\/a\\.out/main/g"
:!mks
|2,0,1621147172,,"!mks"
:mks!
|2,0,1621147172,,"mks!"
:!ma
|2,0,1621147172,,"!ma"
:tabf 1.cm
|2,0,1621147172,,"tabf 1.cm"
:! diff
|2,0,1621147172,,"! diff"
:! diff 1.out 1.cmp
|2,0,1621147172,,"! diff 1.out 1.cmp"
:%y
|2,0,1621147172,,"%y"
:tabf main2.cpp
|2,0,1621147172,,"tabf main2.cpp"
:!rm ./a.out
|2,0,1621147172,,"!rm ./a.out"
:!make krusk
|2,0,1621147172,,"!make krusk"
:!mke
|2,0,1621147172,,"!mke"
:s/\<count\>/countP/g
|2,0,1621147172,,"s/\\<count\\>/countP/g"
:s/j/n/g
|2,0,1621147172,,"s/j/n/g"
:tabnew main2.cpp
|2,0,1621147172,,"tabnew main2.cpp"
:s/i/j/g
|2,0,1621147172,,"s/i/j/g"
:!mkae
|2,0,1621147172,,"!mkae"
:'<,'>
|2,0,1621147172,,"'<,'>"
:%s/\<n\>/N/gc
|2,0,1621147172,,"%s/\\<n\\>/N/gc"
:tabnew 1.out
|2,0,1621147172,,"tabnew 1.out"
:tabf 1.cmp
|2,0,1621147172,,"tabf 1.cmp"
:tabm 1
|2,0,1621147172,,"tabm 1"
:tabf 1.in
|2,0,1621147172,,"tabf 1.in"
:tabf ../1/main.cpp
|2,0,1621147172,,"tabf ../1/main.cpp"
:s/prims/Prims/g
|2,0,1621147172,,"s/prims/Prims/g"
:tabnew 2.in
|2,0,1621147172,,"tabnew 2.in"
:make 2
|2,0,1621147172,,"make 2"
:%s/Prims/Prim's/gc
|2,0,1621147172,,"%s/Prims/Prim's/gc"
:!make 2
|2,0,1621147172,,"!make 2"
:!make 2cp
|2,0,1621147172,,"!make 2cp"
:!make 1
|2,0,1621147172,,"!make 1"
:make cp
|2,0,1621147172,,"make cp"
:make 1cp
|2,0,1621147172,,"make 1cp"
:!make cp
|2,0,1621147172,,"!make cp"
:mks Session.vim 
|2,0,1621147172,,"mks Session.vim "
:wqaa
|2,0,1621147172,,"wqaa"
:.!
|2,0,1621147172,,".!"
:tabm 2
|2,0,1621147172,,"tabm 2"
:%s/queue/deque/gc
|2,0,1621147172,,"%s/queue/deque/gc"
:tabnew 1.cmp
|2,0,1621147172,,"tabnew 1.cmp"
:!make 1cp
|2,0,1621147172,,"!make 1cp"
:s/1/2/g
|2,0,1621147172,,"s/1/2/g"
:!make 1out
|2,0,1621147172,,"!make 1out"
:!mae
|2,0,1621147172,,"!mae"
:!mak
|2,0,1621147172,,"!mak"
:!mk
|2,0,1621147172,,"!mk"
:~
|2,0,1621147172,,"~"
:tabf 1.out
|2,0,1621147172,,"tabf 1.out"
:!python3 main.py
|2,0,1621147172,,"!python3 main.py"
:python3 acronym	
|2,0,1621147172,,"python3 acronym	"
:!pythond3 acronym.py
|2,0,1621147172,,"!pythond3 acronym.py"
:!python3 acronym.py1
|2,0,1621147172,,"!python3 acronym.py1"
:!python3 acronym.py
|2,0,1621147172,,"!python3 acronym.py"
:!python3
|2,0,1621147172,,"!python3"
:!python3 longest_distance.py
|2,0,1621147172,,"!python3 longest_distance.py"
:wq
|2,0,1621147172,,"wq"
:%s/data/d/g
|2,0,1621147172,,"%s/data/d/g"
:! g++ 
|2,0,1621147172,,"! g++ "
:!python3 lucky.py
|2,0,1621147172,,"!python3 lucky.py"
:wqa
|2,0,1621147172,,"wqa"
:!m
|2,0,1621147172,,"!m"
:split
|2,0,1621147172,,"split"
:%yC
|2,0,1621147172,,"%yC"
:re
|2,0,1621147172,,"re"
:%yp
|2,0,1621147172,,"%yp"
:%y"p
|2,0,1621147172,,"%y\"p"
:%"py
|2,0,1621147172,,"%\"py"
:%py
|2,0,1621147172,,"%py"
:s/\<i\>/kg
|2,0,1621147172,,"s/\\<i\\>/kg"
:s/\<i\>/k/g
|2,0,1621147172,,"s/\\<i\\>/k/g"
:%=
|2,0,1621147172,,"%="
:s/\<i\>/j/g
|2,0,1621147172,,"s/\\<i\\>/j/g"
:%cy
|2,0,1621147172,,"%cy"
:%yc
|2,0,1621147172,,"%yc"
:%"cy
|2,0,1621147172,,"%\"cy"
:tabf module.c module.h
|2,0,1621147172,,"tabf module.c module.h"
:help tabnew
|2,0,1621147172,,"help tabnew"
:%s/\<.\>/./g
|2,0,1621147172,,"%s/\\<.\\>/./g"
:%s/\<.\>/\<_\>/g
|2,0,1621147172,,"%s/\\<.\\>/\\<_\\>/g"
:%s/\<.\>/_/g
|2,0,1621147172,,"%s/\\<.\\>/_/g"
:%s/./_/g
|2,0,1621147172,,"%s/./_/g"
:let "@ = expand("%")
|2,0,1621147172,,"let \"@ = expand(\"%\")"
:let @" = explore("%")
|2,0,1621147172,,"let @\" = explore(\"%\")"
:tabnew module_2.h
|2,0,1621147172,,"tabnew module_2.h"
:v
|2,0,1621147172,,"v"
:s
|2,0,1621147172,,"s"
:split ter
|2,0,1621147172,,"split ter"
:s/\<j\>/k/
|2,0,1621147172,,"s/\\<j\\>/k/"
:tabnew hello.h
|2,0,1621147172,,"tabnew hello.h"
:put expand("%")
|2,0,1621147172,,"put expand(\"%\")"
:put =expand("%")
|2,0,1621147172,,"put =expand(\"%\")"
:put strftime('%c')
|2,0,1621147172,,"put strftime('%c')"
:put =strftime('%c')
|2,0,1621147172,,"put =strftime('%c')"
:let = expand("%")
|2,0,1621147172,,"let = expand(\"%\")"
:p
|2,0,1621147172,,"p"
:%
|2,0,1621147172,,"%"
:let @"=expand("%")
|2,0,1621147172,,"let @\"=expand(\"%\")"
:tabf hello.h
|2,0,1621147172,,"tabf hello.h"
:tabnew module.h
|2,0,1621147172,,"tabnew module.h"
:tabnew
|2,0,1621147172,,"tabnew"
:tabf Makefile
|2,0,1621147172,,"tabf Makefile"
:wa
|2,0,1621147172,,"wa"
:!rm Makefile
|2,0,1621147172,,"!rm Makefile"
:!ls
|2,0,1621147172,,"!ls"
:1make
|2,0,1621147172,,"1make"
:tabnew Makefile
|2,0,1621147172,,"tabnew Makefile"
:tabe
|2,0,1621147172,,"tabe"
:E
|2,0,1621147172,,"E"
:make
|2,0,1621147172,,"make"
:help mksession
|2,0,1621147172,,"help mksession"
:vsplit
|2,0,1621147172,,"vsplit"
:help
|2,0,1621147172,,"help"
:close
|2,0,1621147172,,"close"
:help autocmd
|2,0,1621147172,,"help autocmd"
:endfor
|2,0,1621147172,,"endfor"
:elseif
|2,0,1621147172,,"elseif"
:tabf ~/.viminfo
|2,0,1621147172,,"tabf ~/.viminfo"
:!make
|2,0,1621147172,,"!make"
:wv cinfo.vim
|2,0,1621147172,,"wv cinfo.vim"
:%y+
|2,0,1621147172,,"%y+"
:tabf main.c
|2,0,1621147172,,"tabf main.c"
:tabnew main2.py
|2,0,1621147172,,"tabnew main2.py"
:set @" = expand("%")
|2,0,1621147172,,"set @\" = expand(\"%\")"
:let @" = expand("%")
|2,0,1621147172,,"let @\" = expand(\"%\")"
:put = strftime('%c')
|2,0,1621147172,,"put = strftime('%c')"
:wv pyinfo.vim
|2,0,1621147172,,"wv pyinfo.vim"
:qa!
|2,0,1621147172,,"qa!"
:tab ter
|2,0,1621147172,,"tab ter"
:rv cinfo.vim
|2,0,1621147172,,"rv cinfo.vim"
:q!
|2,0,1621147172,,"q!"
:tabf pyinfo.vim
|2,0,1621147172,,"tabf pyinfo.vim"
:tabf cinfo.vim
|2,0,1621147172,,"tabf cinfo.vim"
:help rv
|2,0,1621147172,,"help rv"
:help session
|2,0,1621147172,,"help session"
:qa
|2,0,1621147172,,"qa"
:set paste
|2,0,1621147172,,"set paste"
:!python3 sol
|2,0,1621147172,,"!python3 sol"
:q
|2,0,1621147172,,"q"
:!pip3 install sympy
|2,0,1621147172,,"!pip3 install sympy"
:[
|2,0,1621147172,,"["
:s/eqns/eqs/g
|2,0,1621147172,,"s/eqns/eqs/g"
:!
|2,0,1621147172,,"!"
:w
|2,0,1621147172,,"w"
:!python3 solve.py
|2,0,1621147172,,"!python3 solve.py"
:tabnew main.py
|2,0,1621147172,,"tabnew main.py"
:rv pyinfo.vim
|2,0,1621147172,,"rv pyinfo.vim"
:wv! pyinfo.vim
|2,0,1621147172,,"wv! pyinfo.vim"
:tabf ~/.pyinfo.vim
|2,0,1621147172,,"tabf ~/.pyinfo.vim"
:wv! ~/.cinfo.vim
|2,0,1621147172,,"wv! ~/.cinfo.vim"
:wv!
|2,0,1621147172,,"wv!"
:wv ~/.cinfo.vim
|2,0,1621147172,,"wv ~/.cinfo.vim"
:tabf ~/.cinfo.vim
|2,0,1621147172,,"tabf ~/.cinfo.vim"
:rv! ~/.cinfo.vim
|2,0,1621147172,,"rv! ~/.cinfo.vim"
:!rv ~/.cinfo.vim
|2,0,1621147172,,"!rv ~/.cinfo.vim"
:erg
|2,0,1621147172,,"erg"
:tabnew main.c
|2,0,1621147172,,"tabnew main.c"
:ter
|2,0,1621147172,,"ter"
:set relativenumber
|2,0,1621147172,,"set relativenumber"
:tabnew 
|2,0,1621147172,,"tabnew "
:help viminfo
|2,0,1621147172,,"help viminfo"
:rv! pyinfo.vim
|2,0,1621147172,,"rv! pyinfo.vim"
:!rv pyinfo.vim
|2,0,1621147172,,"!rv pyinfo.vim"
:scripname
|2,0,1621147172,,"scripname"
:rv! ../../c/zeev/cinfo.vim
|2,0,1621147172,,"rv! ../../c/zeev/cinfo.vim"
:%s/\<k\>/e/g
|2,0,1621147172,,"%s/\\<k\\>/e/g"
:reg 
|2,0,1621147172,,"reg "
:t
|2,0,1621147172,,"t"
:tabf module.h
|2,0,1621147172,,"tabf module.h"
:! cp ~/.cinfo.vim ~/.hinfo.vim
|2,0,1621147172,,"! cp ~/.cinfo.vim ~/.hinfo.vim"
:tabf ~./
|2,0,1621147172,,"tabf ~./"
:help tabf
|2,0,1621147172,,"help tabf"
:help buffer
|2,0,1621147172,,"help buffer"
:help BufnewFile
|2,0,1621147172,,"help BufnewFile"
:help beffer
|2,0,1621147172,,"help beffer"
:tabf solve.py
|2,0,1621147172,,"tabf solve.py"
:tabf solver.py
|2,0,1621147172,,"tabf solver.py"
:tab solve.py
|2,0,1621147172,,"tab solve.py"
:rv! ~/.pyinfo.vim
|2,0,1621147172,,"rv! ~/.pyinfo.vim"
:!g++ % && ./a.out
|2,0,1621147172,,"!g++ % && ./a.out"
:!make % && ./a.out
|2,0,1621147172,,"!make % && ./a.out"
:!gcc main.c
|2,0,1621147172,,"!gcc main.c"
:!gcc % && ./a.out
|2,0,1621147172,,"!gcc % && ./a.out"
:wv! ~/.pyinfo.vim
|2,0,1621147172,,"wv! ~/.pyinfo.vim"
:rege
|2,0,1621147172,,"rege"
:reg
|2,0,1621147172,,"reg"
:! cp ~/.cinfo.vim ~/.cppinfo.vim
|2,0,1621147172,,"! cp ~/.cinfo.vim ~/.cppinfo.vim"
:%s/;/,/gc
|2,0,1621147172,,"%s/;/,/gc"

# Search String History (newest to oldest):
? \<j\>
|2,1,1621147172,,"\\<j\\>"
? \<main\>
|2,1,1621147172,,"\\<main\\>"
? hello
|2,1,1621147172,,"hello"
?/hello
|2,1,1621147172,47,"hello"
? \<b\>
|2,1,1621147172,,"\\<b\\>"
? \<cd\>
|2,1,1621147172,,"\\<cd\\>"
? \<ab\>
|2,1,1621147172,,"\\<ab\\>"
? hey
|2,1,1621147172,,"hey"
??filetype
|2,1,1621147172,63,"filetype"
??plugin
|2,1,1621147172,63,"plugin"
? \<w\>
|2,1,1621147172,,"\\<w\\>"
??add_exe
|2,1,1621147172,63,"add_exe"
??memory
|2,1,1621147172,63,"memory"
??AddTwoInts
|2,1,1621147172,63,"AddTwoInts"
??Add
|2,1,1621147172,63,"Add"
??add_execu
|2,1,1621147172,63,"add_execu"
??add_executable
|2,1,1621147172,63,"add_executable"
??request
|2,1,1621147172,63,"request"
??install
|2,1,1621147172,63,"install"
??build_depend
|2,1,1621147172,63,"build_depend"
??timer_call
|2,1,1621147172,63,"timer_call"
??find_package
|2,1,1621147172,63,"find_package"
??turt
|2,1,1621147172,63,"turt"
??subscription
|2,1,1621147172,63,"subscription"
??private
|2,1,1621147172,63,"private"
??String
|2,1,1621147172,63,"String"
??tur
|2,1,1621147172,63,"tur"
??kkkk
|2,1,1621147172,63,"kkkk"
??std::m
|2,1,1621147172,63,"std::m"
??std_msgs
|2,1,1621147172,63,"std_msgs"
??std_
|2,1,1621147172,63,"std_"
? \<add_newdoc_ufunc\>
|2,1,1621147172,,"\\<add_newdoc_ufunc\\>"
??def Settings
|2,1,1621147172,63,"def Settings"
??setting
|2,1,1621147172,63,"setting"
??set
|2,1,1621147172,63,"set"
? \<flags\>
|2,1,1621147172,,"\\<flags\\>"
??family
|2,1,1621147172,63,"family"
??plugged
|2,1,1621147172,63,"plugged"
??shiftwidth
|2,1,1621147172,63,"shiftwidth"
??find_package(rosidl_default_generators R
|2,1,1621147172,63,"find_package(rosidl_default_generators R"
??set(msg_files
|2,1,1621147172,63,"set(msg_files"
??"msg/AddressBook.msg
|2,1,1621147172,63,"\"msg/AddressBook.msg"
??rosidl_generate_interfaces(${PROJECT_NAME}
|2,1,1621147172,63,"rosidl_generate_interfaces(${PROJECT_NAME}"
??ament_export_dependencies(rosidl_default_runtime)
|2,1,1621147172,63,"ament_export_dependencies(rosidl_default_runtime)"
? MAX
|2,1,1621147172,,"MAX"
??root
|2,1,1621147172,63,"root"
? \<small_rotation\>
|2,1,1621147172,,"\\<small_rotation\\>"
? \<update\>
|2,1,1621147172,,"\\<update\\>"
??Vertex
|2,1,1621147172,63,"Vertex"
? >
|2,1,1621147172,,">"
??printf
|2,1,1621147172,63,"printf"
? \<Makes\>
|2,1,1621147172,,"\\<Makes\\>"
?/root
|2,1,1621147172,47,"root"
? R
|2,1,1621147172,,"R"
? \<new\>
|2,1,1621147172,,"\\<new\\>"
? v
|2,1,1621147172,,"v"
? \<fromString\>
|2,1,1621147172,,"\\<fromString\\>"
??size()
|2,1,1621147172,63,"size()"
? \<debugger\>
|2,1,1621147172,,"\\<debugger\\>"
??fromSt
|2,1,1621147172,63,"fromSt"
? \<cassert\>
|2,1,1621147172,,"\\<cassert\\>"
??split19k
|2,1,1621147172,63,"split19k"
? \<orderStats\>
|2,1,1621147172,,"\\<orderStats\\>"
??left
|2,1,1621147172,63,"left"
??left->in
|2,1,1621147172,63,"left->in"
??SplayTree
|2,1,1621147172,63,"SplayTree"
??inOrder
|2,1,1621147172,63,"inOrder"
??merged
|2,1,1621147172,63,"merged"
??process
|2,1,1621147172,63,"process"
??end
|2,1,1621147172,63,"end"
??merge
|2,1,1621147172,63,"merge"
??splay
|2,1,1621147172,63,"splay"
??fn
|2,1,1621147172,63,"fn"
??orderStats
|2,1,1621147172,63,"orderStats"
??T
|2,1,1621147172,63,"T"
??fromString
|2,1,1621147172,63,"fromString"
? \<SplayTree\>
|2,1,1621147172,,"\\<SplayTree\\>"
??delete
|2,1,1621147172,63,"delete"
??split
|2,1,1621147172,63,"split"
? \<split\>
|2,1,1621147172,,"\\<split\\>"
??delete(this)
|2,1,1621147172,63,"delete(this)"
??delete this
|2,1,1621147172,63,"delete this"
??DFS
|2,1,1621147172,63,"DFS"
? \<explore\>
|2,1,1621147172,,"\\<explore\\>"
??vector<list
|2,1,1621147172,63,"vector<list"
? vector<list
|2,1,1621147172,,"vector<list"
??explore
|2,1,1621147172,63,"explore"
??push_back
|2,1,1621147172,63,"push_back"
??filter
|2,1,1621147172,63,"filter"
? \<filter\>
|2,1,1621147172,,"\\<filter\\>"
? std::pair<long long, int>
|2,1,1621147172,,"std::pair<long long, int>"
??std::pair
|2,1,1621147172,63,"std::pair"
??continue
|2,1,1621147172,63,"continue"
?/h
|2,1,1621147172,47,"h"
?/incremen
|2,1,1621147172,47,"incremen"
? \<:Next\>
|2,1,1621147172,,"\\<:Next\\>"
? \<:next\>
|2,1,1621147172,,"\\<:next\\>"
? ;
|2,1,1621147172,,";"
??back
|2,1,1621147172,63,"back"
??int
|2,1,1621147172,63,"int"
??new
|2,1,1621147172,63,"new"
? \<back\>
|2,1,1621147172,,"\\<back\\>"
? \<tail\>
|2,1,1621147172,,"\\<tail\\>"
??Enter
|2,1,1621147172,63,"Enter"
? \<s\>
|2,1,1621147172,,"\\<s\\>"
??const
|2,1,1621147172,63,"const"
? \<sort\>
|2,1,1621147172,,"\\<sort\\>"
??key
|2,1,1621147172,63,"key"
? \<partition\>
|2,1,1621147172,,"\\<partition\\>"
??assert
|2,1,1621147172,63,"assert"
? \<swap\>
|2,1,1621147172,,"\\<swap\\>"
??std::cout 
|2,1,1621147172,63,"std::cout "
??partition
|2,1,1621147172,63,"partition"
??yo
|2,1,1621147172,63,"yo"
??sort
|2,1,1621147172,63,"sort"
??loop
|2,1,1621147172,63,"loop"
??9
|2,1,1621147172,63,"9"
??counter
|2,1,1621147172,63,"counter"
??parti
|2,1,1621147172,63,"parti"
??swap
|2,1,1621147172,63,"swap"
??data
|2,1,1621147172,63,"data"
??std::cout
|2,1,1621147172,63,"std::cout"
? \<clustering\>
|2,1,1621147172,,"\\<clustering\\>"
? \\
|2,1,1621147172,,"\\\\"
??D2
|2,1,1621147172,63,"D2"
? bfs
|2,1,1621147172,,"bfs"
??export
|2,1,1621147172,63,"export"
? s
|2,1,1621147172,,"s"
? sel
|2,1,1621147172,,"sel"
? And
|2,1,1621147172,,"And"
? x
|2,1,1621147172,,"x"
? zx
|2,1,1621147172,,"zx"
??Add16
|2,1,1621147172,63,"Add16"
? \<ng\>
|2,1,1621147172,,"\\<ng\\>"
? a.out: main.cpp
|2,1,1621147172,,"a.out: main.cpp"
??size_t
|2,1,1621147172,63,"size_t"
? \<Heap\>
|2,1,1621147172,,"\\<Heap\\>"
? \<heap\>
|2,1,1621147172,,"\\<heap\\>"
? \<getInput\>
|2,1,1621147172,,"\\<getInput\\>"
? \<verbose\>
|2,1,1621147172,,"\\<verbose\\>"
? size
|2,1,1621147172,,"size"
? SortedHeap
|2,1,1621147172,,"SortedHeap"
??size
|2,1,1621147172,63,"size"
??heapn
|2,1,1621147172,63,"heapn"
??heap
|2,1,1621147172,63,"heap"
??sifDown
|2,1,1621147172,63,"sifDown"
??siftDown
|2,1,1621147172,63,"siftDown"
??siftup
|2,1,1621147172,63,"siftup"
??debugger
|2,1,1621147172,63,"debugger"
??ChangePr
|2,1,1621147172,63,"ChangePr"
?/main
|2,1,1621147172,47,"main"
??visited
|2,1,1621147172,63,"visited"
? visited
|2,1,1621147172,,"visited"
? \<ChangePriority\>
|2,1,1621147172,,"\\<ChangePriority\\>"
? \<changePriority\>
|2,1,1621147172,,"\\<changePriority\\>"
??debugg
|2,1,1621147172,63,"debugg"
??deb
|2,1,1621147172,63,"deb"
??de
|2,1,1621147172,63,"de"
??max
|2,1,1621147172,63,"max"
??extract
|2,1,1621147172,63,"extract"
? \<pc\>
|2,1,1621147172,,"\\<pc\\>"
? \<PC\>
|2,1,1621147172,,"\\<PC\\>"
??loadA
|2,1,1621147172,63,"loadA"
??loadD
|2,1,1621147172,63,"loadD"
??jtl
|2,1,1621147172,63,"jtl"
? Hash
|2,1,1621147172,,"Hash"
??<
|2,1,1621147172,63,"<"
??>=
|2,1,1621147172,63,">="
??s
|2,1,1621147172,63,"s"
?/hash
|2,1,1621147172,47,"hash"
? \<hashtable\>
|2,1,1621147172,,"\\<hashtable\\>"
? \<HashTable\>
|2,1,1621147172,,"\\<HashTable\\>"
??class Hash
|2,1,1621147172,63,"class Hash"
??hash(
|2,1,1621147172,63,"hash("
? \<precompute\>
|2,1,1621147172,,"\\<precompute\\>"
??precompute
|2,1,1621147172,63,"precompute"
??ez_l
|2,1,1621147172,63,"ez_l"
??ez-life
|2,1,1621147172,63,"ez-life"
??file_list
|2,1,1621147172,63,"file_list"
? \<ConvertSymbols\>
|2,1,1621147172,,"\\<ConvertSymbols\\>"
??"M"
|2,1,1621147172,63,"\"M\""
??[1]
|2,1,1621147172,63,"[1]"
? \<file_name\>
|2,1,1621147172,,"\\<file_name\\>"
??hack
|2,1,1621147172,63,"hack"
??Handle
|2,1,1621147172,63,"Handle"
??hash
|2,1,1621147172,63,"hash"
??x_l
|2,1,1621147172,63,"x_l"
??getPow
|2,1,1621147172,63,"getPow"
? \<getPow\>
|2,1,1621147172,,"\\<getPow\\>"
??getHash
|2,1,1621147172,63,"getHash"
??Command
|2,1,1621147172,63,"Command"
? sp
|2,1,1621147172,,"sp"
??__init__
|2,1,1621147172,63,"__init__"
? \<write\>
|2,1,1621147172,,"\\<write\\>"
??else if
|2,1,1621147172,63,"else if"
??Aritm
|2,1,1621147172,63,"Aritm"
??PopCon
|2,1,1621147172,63,"PopCon"
?/temp
|2,1,1621147172,47,"temp"
??push
|2,1,1621147172,63,"push"
??main
|2,1,1621147172,63,"main"
??input_file_name
|2,1,1621147172,63,"input_file_name"
??os
|2,1,1621147172,63,"os"
??parser.
|2,1,1621147172,63,"parser."
??parser\.
|2,1,1621147172,63,"parser\\."
??commands
|2,1,1621147172,63,"commands"
? \<CommandPreprocessor\>
|2,1,1621147172,,"\\<CommandPreprocessor\\>"
? \<line\>
|2,1,1621147172,,"\\<line\\>"
??self.parser
|2,1,1621147172,63,"self.parser"
??current_file_full
|2,1,1621147172,63,"current_file_full"
??cmd2type
|2,1,1621147172,63,"cmd2type"
??current_filename
|2,1,1621147172,63,"current_filename"
??Parse
|2,1,1621147172,63,"Parse"
??directory
|2,1,1621147172,63,"directory"
??full_directory_
|2,1,1621147172,63,"full_directory_"
??rsplit
|2,1,1621147172,63,"rsplit"
??full_directory_path
|2,1,1621147172,63,"full_directory_path"
??full_path
|2,1,1621147172,63,"full_path"
??path_is_file
|2,1,1621147172,63,"path_is_file"
??full_out_filename
|2,1,1621147172,63,"full_out_filename"
??self.full_directory
|2,1,1621147172,63,"self.full_directory"
? \<cmd2type\>
|2,1,1621147172,,"\\<cmd2type\\>"
??'r'
|2,1,1621147172,63,"'r'"
??tst
|2,1,1621147172,63,"tst"
? \<full_file_path\>
|2,1,1621147172,,"\\<full_file_path\\>"
? \<commands\>
|2,1,1621147172,,"\\<commands\\>"
??po
|2,1,1621147172,63,"po"
??classmethod
|2,1,1621147172,63,"classmethod"
??foo
|2,1,1621147172,63,"foo"
??writePush
|2,1,1621147172,63,"writePush"
??write
|2,1,1621147172,63,"write"
??foldmethod
|2,1,1621147172,63,"foldmethod"
??Ad12
|2,1,1621147172,63,"Ad12"
??add12
|2,1,1621147172,63,"add12"
??call
|2,1,1621147172,63,"call"
? \<BasicLoop\>
|2,1,1621147172,,"\\<BasicLoop\\>"
??function
|2,1,1621147172,63,"function"
??Arith
|2,1,1621147172,63,"Arith"
??temp
|2,1,1621147172,63,"temp"
??this.func
|2,1,1621147172,63,"this.func"
? \<writeGoto\>
|2,1,1621147172,,"\\<writeGoto\\>"
??convertLabel
|2,1,1621147172,63,"convertLabel"
? \<convertLabel\>
|2,1,1621147172,,"\\<convertLabel\\>"
? \<convertIf\>
|2,1,1621147172,,"\\<convertIf\\>"
? \<convertGoto\>
|2,1,1621147172,,"\\<convertGoto\\>"
??rect
|2,1,1621147172,63,"rect"
??ret
|2,1,1621147172,63,"ret"
? \<return_address\>
|2,1,1621147172,,"\\<return_address\\>"
??Return
|2,1,1621147172,63,"Return"
??convertReturn
|2,1,1621147172,63,"convertReturn"
??Branch
|2,1,1621147172,63,"Branch"
??n_var
|2,1,1621147172,63,"n_var"
??Sys
|2,1,1621147172,63,"Sys"
??{
|2,1,1621147172,63,"{"
??}
|2,1,1621147172,63,"}"
??push n
|2,1,1621147172,63,"push n"
??/#
|2,1,1621147172,63,"/#"
??argument
|2,1,1621147172,63,"argument"
??Sys.init
|2,1,1621147172,63,"Sys.init"
??sys
|2,1,1621147172,63,"sys"
??function Sys.init 0
|2,1,1621147172,63,"function Sys.init 0"
??goto while
|2,1,1621147172,63,"goto while"
?/function sys
|2,1,1621147172,47,"function sys"
??0;JMP
|2,1,1621147172,63,"0;JMP"
??label
|2,1,1621147172,63,"label"
??pop
|2,1,1621147172,63,"pop"
?//
|2,1,1621147172,47,"/"
??convertCall
|2,1,1621147172,63,"convertCall"
? \<convertCall\>
|2,1,1621147172,,"\\<convertCall\\>"
? \<writeBootStrap\>
|2,1,1621147172,,"\\<writeBootStrap\\>"
?/sys.init$ret
|2,1,1621147172,47,"sys.init$ret"
??@sysinit
|2,1,1621147172,63,"@sysinit"
??sys.init
|2,1,1621147172,63,"sys.init"
? \<init\>
|2,1,1621147172,,"\\<init\\>"
? \<sys\>
|2,1,1621147172,,"\\<sys\\>"
? \<Sys\>
|2,1,1621147172,,"\\<Sys\\>"
??4
|2,1,1621147172,63,"4"
??Main.fibonacci
|2,1,1621147172,63,"Main.fibonacci"
??@Main.fibonacci$IF
|2,1,1621147172,63,"@Main.fibonacci$IF"
??@Main.fibonacci$IF_F
|2,1,1621147172,63,"@Main.fibonacci$IF_F"
??IF_FALSE
|2,1,1621147172,63,"IF_FALSE"
??.pop()
|2,1,1621147172,63,".pop()"
? \<fromCmd\>
|2,1,1621147172,,"\\<fromCmd\\>"
? \<CodeWriter\>
|2,1,1621147172,,"\\<CodeWriter\\>"
? circle
|2,1,1621147172,,"circle"
??static
|2,1,1621147172,63,"static"
??10
|2,1,1621147172,63,"10"
??100
|2,1,1621147172,63,"100"
??state
|2,1,1621147172,63,"state"
??initArray
|2,1,1621147172,63,"initArray"
?/setState
|2,1,1621147172,47,"setState"
??draw()
|2,1,1621147172,63,"draw()"
? \<setPos\>
|2,1,1621147172,,"\\<setPos\\>"
??changePos
|2,1,1621147172,63,"changePos"
? \<changePos\>
|2,1,1621147172,,"\\<changePos\\>"
??fill
|2,1,1621147172,63,"fill"
??get
|2,1,1621147172,63,"get"
??setPos
|2,1,1621147172,63,"setPos"
??getState
|2,1,1621147172,63,"getState"
??clear()
|2,1,1621147172,63,"clear()"
??clear
|2,1,1621147172,63,"clear"
??reset
|2,1,1621147172,63,"reset"
??checkSolved
|2,1,1621147172,63,"checkSolved"
? \<iostream\>
|2,1,1621147172,,"\\<iostream\\>"
? string
|2,1,1621147172,,"string"
?/string
|2,1,1621147172,47,"string"
??comp
|2,1,1621147172,63,"comp"
??ans
|2,1,1621147172,63,"ans"
??hou
|2,1,1621147172,63,"hou"
? \<comp\>
|2,1,1621147172,,"\\<comp\\>"
? var
|2,1,1621147172,,"var"
??Parser
|2,1,1621147172,63,"Parser"
??Node
|2,1,1621147172,63,"Node"
? \<inNode\>
|2,1,1621147172,,"\\<inNode\\>"
??top
|2,1,1621147172,63,"top"
??revers
|2,1,1621147172,63,"revers"
??store
|2,1,1621147172,63,"store"
? 0
|2,1,1621147172,,"0"
? \<bfs\>
|2,1,1621147172,,"\\<bfs\\>"
??q.end()
|2,1,1621147172,63,"q.end()"
??dfs
|2,1,1621147172,63,"dfs"
??parent
|2,1,1621147172,63,"parent"
??inNode
|2,1,1621147172,63,"inNode"
??disp
|2,1,1621147172,63,"disp"
? \<next\>
|2,1,1621147172,,"\\<next\\>"
??right
|2,1,1621147172,63,"right"
??find
|2,1,1621147172,63,"find"
??bfs
|2,1,1621147172,63,"bfs"
??insert
|2,1,1621147172,63,"insert"
??m
|2,1,1621147172,63,"m"
??game
|2,1,1621147172,63,"game"
??input
|2,1,1621147172,63,"input"
??string constant
|2,1,1621147172,63,"string constant"
??&lt
|2,1,1621147172,63,"&lt"
??let length
|2,1,1621147172,63,"let length"
? a
|2,1,1621147172,,"a"
??solve
|2,1,1621147172,63,"solve"
??\a
|2,1,1621147172,63,"\\a"
??list
|2,1,1621147172,63,"list"
??ipair
|2,1,1621147172,63,"ipair"
??wh
|2,1,1621147172,63,"wh"
??who
|2,1,1621147172,63,"who"
? long long
|2,1,1621147172,,"long long"
??long long
|2,1,1621147172,63,"long long"
??cout 
|2,1,1621147172,63,"cout "
??auto
|2,1,1621147172,63,"auto"
??open
|2,1,1621147172,63,"open"
? [nx][ny]
|2,1,1621147172,,"[nx][ny]"
? >>
|2,1,1621147172,,">>"
? ull
|2,1,1621147172,,"ull"
? \<comb\>
|2,1,1621147172,,"\\<comb\\>"
? );
|2,1,1621147172,,");"
? \<power\>
|2,1,1621147172,,"\\<power\\>"
?  
|2,1,1621147172,," "
??C
|2,1,1621147172,63,"C"
? 3
|2,1,1621147172,,"3"
? _3
|2,1,1621147172,,"_3"
? M
|2,1,1621147172,,"M"
??modInverse
|2,1,1621147172,63,"modInverse"
??comb
|2,1,1621147172,63,"comb"
??min
|2,1,1621147172,63,"min"
??eval
|2,1,1621147172,63,"eval"
? \<eval\>
|2,1,1621147172,,"\\<eval\\>"
? char * str
|2,1,1621147172,,"char * str"
? \<lower\>
|2,1,1621147172,,"\\<lower\\>"
? str[i]
|2,1,1621147172,,"str[i]"
? str\[i\]
|2,1,1621147172,,"str\\[i\\]"
??&str
|2,1,1621147172,63,"&str"
? &str
|2,1,1621147172,,"&str"
? void
|2,1,1621147172,,"void"
??origin
|2,1,1621147172,63,"origin"
??cout
|2,1,1621147172,63,"cout"
? 2
|2,1,1621147172,,"2"
? .\/a.out
|2,1,1621147172,,".\\/a.out"
? \<solve\>
|2,1,1621147172,,"\\<solve\\>"
? \<c\>
|2,1,1621147172,,"\\<c\\>"
? \<disp\>
|2,1,1621147172,,"\\<disp\\>"
? ,
|2,1,1621147172,,","
? big
|2,1,1621147172,,"big"
? small
|2,1,1621147172,,"small"
? '
|2,1,1621147172,,"'"
? \'
|2,1,1621147172,,"\\'"
? \â€˜
|2,1,1621147172,,"\\â€˜"
? â€˜
|2,1,1621147172,,"â€˜"
? â€™
|2,1,1621147172,,"â€™"
? convert
|2,1,1621147172,,"convert"
? \<convert\>
|2,1,1621147172,,"\\<convert\\>"
??print
|2,1,1621147172,63,"print"
? \<include\>
|2,1,1621147172,,"\\<include\\>"
? makepair
|2,1,1621147172,,"makepair"
? \<ull\>
|2,1,1621147172,,"\\<ull\\>"
? \.\/a\.out
|2,1,1621147172,,"\\.\\/a\\.out"
??emplace
|2,1,1621147172,63,"emplace"
? \<extractMin\>
|2,1,1621147172,,"\\<extractMin\\>"
??t
|2,1,1621147172,63,"t"
? \<array\>
|2,1,1621147172,,"\\<array\\>"
? \<find\>
|2,1,1621147172,,"\\<find\\>"
? \<count\>
|2,1,1621147172,,"\\<count\\>"
? j
|2,1,1621147172,,"j"
? \<countP\>
|2,1,1621147172,,"\\<countP\\>"
? i
|2,1,1621147172,,"i"
? \<n\>
|2,1,1621147172,,"\\<n\\>"
? \<quickSort\>
|2,1,1621147172,,"\\<quickSort\\>"
? \<mergeSort\>
|2,1,1621147172,,"\\<mergeSort\\>"
? prims
|2,1,1621147172,,"prims"
? Prims
|2,1,1621147172,,"Prims"
??count
|2,1,1621147172,63,"count"
??for
|2,1,1621147172,63,"for"
??while
|2,1,1621147172,63,"while"
??i++
|2,1,1621147172,63,"i++"
?/++
|2,1,1621147172,47,"++"
??unsigned
|2,1,1621147172,63,"unsigned"
??keywords
|2,1,1621147172,63,"keywords"
??keyword
|2,1,1621147172,63,"keyword"
??return
|2,1,1621147172,63,"return"
??dynamic
|2,1,1621147172,63,"dynamic"
? \<nsol\>
|2,1,1621147172,,"\\<nsol\\>"
? queue
|2,1,1621147172,,"queue"
??aho
|2,1,1621147172,63,"aho"
? 1
|2,1,1621147172,,"1"
? \<cp\>
|2,1,1621147172,,"\\<cp\\>"
? \<f\>
|2,1,1621147172,,"\\<f\\>"
? \<I\>
|2,1,1621147172,,"\\<I\\>"
? \<pow\>
|2,1,1621147172,,"\\<pow\\>"
??cp
|2,1,1621147172,63,"cp"
??exit
|2,1,1621147172,63,"exit"
??Aho-Corasick
|2,1,1621147172,63,"Aho-Corasick"
??>
|2,1,1621147172,63,">"
? data
|2,1,1621147172,,"data"
? \<testRabinKarpPatternSearch\>
|2,1,1621147172,,"\\<testRabinKarpPatternSearch\\>"
? \<parse\>
|2,1,1621147172,,"\\<parse\\>"
? \<i\>
|2,1,1621147172,,"\\<i\\>"
??tabs
|2,1,1621147172,63,"tabs"
??tab
|2,1,1621147172,63,"tab"
? \<.\>
|2,1,1621147172,,"\\<.\\>"
? .
|2,1,1621147172,,"."
?/*
|2,1,1621147172,47,"*"
? @$
|2,1,1621147172,,"@$"
??wv
|2,1,1621147172,63,"wv"
? \<:autocmd\>
|2,1,1621147172,,"\\<:autocmd\\>"
??jkkkkkkkkkk
|2,1,1621147172,63,"jkkkkkkkkkk"
??registers
|2,1,1621147172,63,"registers"
??:rv
|2,1,1621147172,63,":rv"
? eqns
|2,1,1621147172,,"eqns"
??-rv
|2,1,1621147172,63,"-rv"
??rv
|2,1,1621147172,63,"rv"
? \<-rv\>
|2,1,1621147172,,"\\<-rv\\>"
??bufnew
|2,1,1621147172,63,"bufnew"
??buff
|2,1,1621147172,63,"buff"
? \<viminfo-file\>
|2,1,1621147172,,"\\<viminfo-file\\>"
? \<session-file\>
|2,1,1621147172,,"\\<session-file\\>"
? \<k\>
|2,1,1621147172,,"\\<k\\>"
??help tabf
|2,1,1621147172,63,"help tabf"
??buffer
|2,1,1621147172,63,"buffer"
? \<ans\>
|2,1,1621147172,,"\\<ans\\>"
? \<world\>
|2,1,1621147172,,"\\<world\\>"

# Expression History (newest to oldest):
=100 * 50 + 10
|2,2,1621147172,,"100 * 50 + 10"
=100 * 50 + 20
|2,2,1621147172,,"100 * 50 + 20"
=10 * 20 + 5
|2,2,1621147172,,"10 * 20 + 5"
=p
|2,2,1621147172,,"p"

# Input Line History (newest to oldest):
@printf
|2,3,1621147172,,"printf"
@p class = root>
|2,3,1621147172,,"p class = root>"
@print
|2,3,1621147172,,"print"
@p class="hello world">
|2,3,1621147172,,"p class=\"hello world\">"
@depend
|2,3,1621147172,,"depend"
@build_depend>
|2,3,1621147172,,"build_depend>"
@exev_depend>
|2,3,1621147172,,"exev_depend>"
@depend>
|2,3,1621147172,,"depend>"
@buildtool_depend>
|2,3,1621147172,,"buildtool_depend>"
@exec_depend>
|2,3,1621147172,,"exec_depend>"
@member_of_group>
|2,3,1621147172,,"member_of_group>"
@p>
|2,3,1621147172,,"p>"
@[{y(es)},n(o),a(ll),q(uit)] y
|2,3,1621147172,,"[{y(es)},n(o),a(ll),q(uit)] y"
@dict
|2,3,1621147172,,"dict"
@list
|2,3,1621147172,,"list"

# Debug Line History (newest to oldest):

# Registers:
"0	CHAR	0
	solve.py
|3,0,0,0,1,0,1621079992,"solve.py"
""1	LINE	0
	:wv! ~/.vim/info/.pyinfo.vim
|3,1,1,1,1,0,1621147161,":wv! ~/.vim/info/.pyinfo.vim"
"2	LINE	0
	
|3,0,2,1,1,0,1621081530,""
"3	LINE	0
	print(f"hello = {hello}");
|3,0,3,1,1,0,1621081526,"print(f\"hello = {hello}\");"
"4	LINE	0
	print(f"this  = {this }");
|3,0,4,1,1,0,1621081525,"print(f\"this  = {this }\");"
"5	LINE	0
	print(f"very = {very}");
|3,0,5,1,1,0,1621081524,"print(f\"very = {very}\");"
"6	LINE	0
	^d$aprint(f"€ýapa = {€ýapf)i"€ýaA;€ýa
|3,0,6,1,1,0,1621081522,"^d$aprint(f\"€ýapa = {€ýapf)i\"€ýaA;€ýa"
"7	LINE	0
	print(f"hello world = {hello world}");
	print(f"hello world = {hello world}");
|3,0,7,1,2,0,1621081433,"print(f\"hello world = {hello world}\");","print(f\"hello world = {hello world}\");"
"8	LINE	0
	^d$aprint(f"€ýapa = {€ýapf)i"€ýaA;€ýaj
|3,0,8,1,1,0,1621081416,"^d$aprint(f\"€ýapa = {€ýapf)i\"€ýaA;€ýaj"
"9	LINE	0
	print(f"hello = {hello}");
|3,0,9,1,1,0,1621081388,"print(f\"hello = {hello}\");"
"a	CHAR	0
	i €ýak
|3,0,10,0,1,0,1612342066,"i €ýak"
"b	CHAR	0
	oif __name__ == '__main__':
|3,0,11,0,1,0,1621077500,"oif __name__ == '__main__':"
"c	LINE	0
	#include<stdio.h>
	#include<stdlib.h>
	#include<limits.h>
	
	
	int main(void){
		return 0;
	}
	
	
|3,0,12,1,10,0,1620963634,"#include<stdio.h>","#include<stdlib.h>","#include<limits.h>","","","int main(void){","	return 0;","}","",""
"d	CHAR	0
	@b€ýa@t
|3,0,13,0,1,0,1621078122,"@b€ýa@t"
"e	CHAR	0
	$i&&€ýa
|3,0,14,0,1,0,1614340553,"$i&&€ýa"
"f	CHAR	0
	ggO/*File AneName: €ýa:put = let @" = ep€kbxpand("%")poDate of Creation: €ýa:put = explore("strftime("€kb'%c')kJoAuthor: Josiah Tan€kb€kb€kb*/€ýa
|3,0,15,0,1,0,1620986375,"ggO/*File AneName: €ýa:put = let @\" = ep€kbxpand(\"%\")poDate of Creation: €ýa:put = explore(\"strftime(\"€kb'%c')kJoAuthor: Josiah Tan€kb€kb€kb*/€ýa"
"g	CHAR	0
	i#ifndef €ýa:let @" ex€kb€kb=expand("%")pF.r_viWUviwyo#define €ýapo€ýaG10o€ýao#endif€ýa9k
|3,0,16,0,1,0,1621079858,"i#ifndef €ýa:let @\" ex€kb€kb=expand(\"%\")pF.r_viWUviwyo#define €ýapo€ýaG10o€ýao#endif€ýa9k"
"h	LINE	0
	385
<ggO# ++€kb€kb=======================================================€kb€kb# File€ýaO€ýajki#€ýajA Name: €ýa:let %€kb@" = expand("%")po#d€kb Date of Creation: €ýa:put = defstrtimefstrtftimstrftime("€kb'%c')kJo# Author: Josiah Tan# Description:3€kb€kb## =====================================================# =====================================================€ýa
|3,0,17,1,1,0,1621079975,"ggO# ++€kb€kb=======================================================€kb€kb# File€ýaO€ýajki#€ýajA Name: €ýa:let %€kb@\" = expand(\"%\")po#d€kb Date of Creation: €ýa:put = defstrtimefstrtftimstrftime(\"€kb'%c')kJo# Author: Josiah Tan# Description:3€kb€kb## =====================================================# =====================================================€ýa"
"i	CHAR	0
	Sfor (int i=0;i<n;i++){€ýaO€ýa
|3,0,18,0,1,0,1620986139,"Sfor (int i=0;i<n;i++){€ýaO€ýa"
"j	CHAR	0
	Sfor (int j=0;j<m;j++){€ýaO€ýa
|3,0,19,0,1,0,1620986173,"Sfor (int j=0;j<m;j++){€ýaO€ýa"
"l	CHAR	0
	f,i: Ar€kb€ýal
|3,0,21,0,1,0,1613564205,"f,i: Ar€kb€ýal"
"m	CHAR	0
	:tabnew Mae€kbkei€kbfiletabnew Makefile:%diall: ./a.outcat 1.in | ./a.ou€kb€kbout./a.out: main.cpp€kb€kbg++ mainc€kb.cp€kb€ýa
|3,0,22,0,1,0,1620986862,":tabnew Mae€kbkei€kbfiletabnew Makefile:%diall: ./a.outcat 1.in | ./a.ou€kb€kbout./a.out: main.cpp€kb€kbg++ mainc€kb.cp€kb€ýa"
"n	LINE	0
	Josiah Tan
|3,0,23,1,1,0,1620984417,"Josiah Tan"
"p	LINE	0
	^d$aprint(f"€ýapa = {€ýapf)i"€ýaA;€ýa
|3,0,25,1,1,0,1621081520,"^d$aprint(f\"€ýapa = {€ýapf)i\"€ýaA;€ýa"
"q	CHAR	0
	ihello wol€kbrld€ýa
|3,0,26,0,1,0,1621046993,"ihello wol€kbrld€ýa"
"r	CHAR	0
	:!python3 %
|3,0,27,0,1,0,1621074930,":!python3 %"
"s	CHAR	0
	f,geysiw"f,
|3,0,28,0,1,0,1613478510,"f,geysiw\"f,"
"t	LINE	0
	385
<ggO# ++€kb€kb=======================================================€kb€kb# File€ýaO€ýajki#€ýajA Name: €ýa:let %€kb@" = expand("%")po#d€kb Date of Creation: €ýa:put = defstrtimefstrtftimstrftime("€kb'%c')kJo# Author: Josiah Tan# Description:3€kb€kb## =====================================================# =====================================================€ýa
|3,0,29,1,1,0,1621072651,"ggO# ++€kb€kb=======================================================€kb€kb# File€ýaO€ýajki#€ýajA Name: €ýa:let %€kb@\" = expand(\"%\")po#d€kb Date of Creation: €ýa:put = defstrtimefstrtftimstrftime(\"€kb'%c')kJo# Author: Josiah Tan# Description:3€kb€kb## =====================================================# =====================================================€ýa"
"u	CHAR	0
	^veUk
|3,0,30,0,1,0,1613212860,"^veUk"
"v@	LINE	0
	:wv! ~/.vim/info/.pyinfo.vim
|3,2,31,1,1,0,1621147158,":wv! ~/.vim/info/.pyinfo.vim"
"w	CHAR	0
	thii€kbti€kb€kbthis is a program that copies registtakprints what is in register w t€kb€kb€kbq twice€ýa@w@q@q
|3,0,32,0,1,0,1620987224,"thii€kbti€kb€kbthis is a program that copies registtakprints what is in register w t€kb€kb€kbq twice€ýa@w@q@q"
"-	CHAR	0
	nice
|3,0,36,0,1,0,1621081538,"nice"

# global variables:

# File marks:
'P  2  20  ~/Desktop/josiah_folder/nand2tetris/projects/07/StackArithmetic/SimpleAdd/SimpleAdd.asm
|4,80,2,20,1613618169,"~/Desktop/josiah_folder/nand2tetris/projects/07/StackArithmetic/SimpleAdd/SimpleAdd.asm"
'V  43  0  ~/.vimrc
|4,86,43,0,1612532244,"~/.vimrc"
'0  1  0  ~/Desktop/josiah_folder/vim/vimvscode/main.py
|4,48,1,0,1621147175,"~/Desktop/josiah_folder/vim/vimvscode/main.py"
'1  27  0  ~/Desktop/josiah_folder/vim/vimvscode/main.py
|4,49,27,0,1621147164,"~/Desktop/josiah_folder/vim/vimvscode/main.py"
'2  27  0  ~/Desktop/josiah_folder/vim/vimvscode/main.py
|4,50,27,0,1621147164,"~/Desktop/josiah_folder/vim/vimvscode/main.py"
'3  12  0  ~/Desktop/josiah_folder/vim/vimvscode/module.h
|4,51,12,0,1621147016,"~/Desktop/josiah_folder/vim/vimvscode/module.h"
'4  12  0  ~/Desktop/josiah_folder/vim/vimvscode/module.h
|4,52,12,0,1621147016,"~/Desktop/josiah_folder/vim/vimvscode/module.h"
'5  13  0  ~/Desktop/josiah_folder/vim/vimvscode/module.h
|4,53,13,0,1621146992,"~/Desktop/josiah_folder/vim/vimvscode/module.h"
'6  13  0  ~/Desktop/josiah_folder/vim/vimvscode/module.h
|4,54,13,0,1621146992,"~/Desktop/josiah_folder/vim/vimvscode/module.h"
'7  13  0  ~/Desktop/josiah_folder/vim/vimvscode/module.h
|4,55,13,0,1621146992,"~/Desktop/josiah_folder/vim/vimvscode/module.h"
'8  13  0  ~/Desktop/josiah_folder/vim/vimvscode/module.h
|4,56,13,0,1621146992,"~/Desktop/josiah_folder/vim/vimvscode/module.h"
'9  2  0  ~/Desktop/josiah_folder/vim/vimvscode/main.c
|4,57,2,0,1621146846,"~/Desktop/josiah_folder/vim/vimvscode/main.c"

# Jumplist (newest first):
-'  1  0  ~/Desktop/josiah_folder/vim/vimvscode/main.py
|4,39,1,0,1621147175,"~/Desktop/josiah_folder/vim/vimvscode/main.py"
-'  27  0  ~/Desktop/josiah_folder/vim/vimvscode/main.c
|4,39,27,0,1621147172,"~/Desktop/josiah_folder/vim/vimvscode/main.c"
-'  27  0  ~/Desktop/josiah_folder/vim/vimvscode/main.py
|4,39,27,0,1621147164,"~/Desktop/josiah_folder/vim/vimvscode/main.py"
-'  28  0  ~/Desktop/josiah_folder/vim/vimvscode/main.py
|4,39,28,0,1621147132,"~/Desktop/josiah_folder/vim/vimvscode/main.py"
-'  2  0  ~/Desktop/josiah_folder/vim/vimvscode/main.py
|4,39,2,0,1621147115,"~/Desktop/josiah_folder/vim/vimvscode/main.py"
-'  23  21  ~/Desktop/josiah_folder/vim/vimvscode/main.py
|4,39,23,21,1621146898,"~/Desktop/josiah_folder/vim/vimvscode/main.py"
-'  2  0  ~/Desktop/josiah_folder/vim/vimvscode/main.c
|4,39,2,0,1621146848,"~/Desktop/josiah_folder/vim/vimvscode/main.c"
-'  1  0  ~/Desktop/josiah_folder/vim/vimvscode/mian.c
|4,39,1,0,1621146831,"~/Desktop/josiah_folder/vim/vimvscode/mian.c"
-'  23  3  ~/Desktop/josiah_folder/vim/vimvscode/main.c
|4,39,23,3,1621146812,"~/Desktop/josiah_folder/vim/vimvscode/main.c"
-'  1  0  ~/Desktop/josiah_folder/vim/vimvscode/main.c
|4,39,1,0,1621146811,"~/Desktop/josiah_folder/vim/vimvscode/main.c"
-'  22  4  ~/Desktop/josiah_folder/vim/vimvscode/main.c
|4,39,22,4,1621146811,"~/Desktop/josiah_folder/vim/vimvscode/main.c"
-'  21  5  ~/Desktop/josiah_folder/vim/vimvscode/main.c
|4,39,21,5,1621146808,"~/Desktop/josiah_folder/vim/vimvscode/main.c"
-'  69  0  ~/.vim/vimrc
|4,39,69,0,1621146794,"~/.vim/vimrc"
-'  59  0  ~/.vim/vimrc
|4,39,59,0,1621146785,"~/.vim/vimrc"
-'  1  0  ~/.vim/vimrc
|4,39,1,0,1621146743,"~/.vim/vimrc"
-'  14  10  ~/Desktop/josiah_folder/vim/vimvscode/main.py
|4,39,14,10,1621125859,"~/Desktop/josiah_folder/vim/vimvscode/main.py"

# History of marks within files (newest to oldest):

> ~/Desktop/josiah_folder/vim/vimvscode/main.c
	*	1621147169	0
	"	27	0
	.	1	0
	+	26	9
	+	16	0
	+	7	0
	+	16	17
	+	17	23
	+	18	24
	+	19	25
	+	20	26
	+	21	0
	+	20	0
	+	21	27
	+	1	0

> ~/Desktop/josiah_folder/vim/vimvscode/main.py
	*	1621147175	0
	"	1	0
	.	28	0
	+	10	0
	+	15	9
	+	14	10
	+	18	4
	+	18	21
	+	20	16
	+	21	0
	+	23	4
	+	23	21
	+	1	0
	+	26	0
	+	28	0
	+	10	0
	+	15	9
	+	14	10
	+	18	4
	+	18	21
	+	20	16
	+	21	0
	+	23	4
	+	23	21
	+	1	0
	+	26	0
	+	28	0

> ~/Desktop/josiah_folder/vim/vimvscode/module.h
	*	1621147020	0
	"	13	0
	.	13	0
	+	1	8
	+	1	5
	+	1	0
	+	1	8
	+	1	0
	+	13	0
	+	1	8
	+	1	5
	+	1	0
	+	1	8
	+	1	0
	+	13	0
