# This viminfo file was generated by Vim 8.1.
# You may edit it if you are careful!

# Viminfo version
|1,4

# Value of 'encoding' when this file was written
*encoding=utf-8


# hlsearch on (H) or off (h):
~h
# Last Search Pattern:
~MSle0~/eqns

# Last Substitute Search Pattern:
~MSle0&eqns

# Last Substitute String:
$eqs

# Command Line History (newest to oldest):
:%d
|2,0,1621163882,,"%d"
:%s/;/,/gc
|2,0,1621163878,,"%s/;/,/gc"
:! cp ~/.cinfo.vim ~/.cppinfo.vim
|2,0,1621163878,,"! cp ~/.cinfo.vim ~/.cppinfo.vim"
:reg
|2,0,1621163878,,"reg"
:rege
|2,0,1621163878,,"rege"
:wv! ~/.pyinfo.vim
|2,0,1621163878,,"wv! ~/.pyinfo.vim"
:!gcc % && ./a.out
|2,0,1621163878,,"!gcc % && ./a.out"
:!gcc main.c
|2,0,1621163878,,"!gcc main.c"
:!make % && ./a.out
|2,0,1621163878,,"!make % && ./a.out"
:!g++ % && ./a.out
|2,0,1621163878,,"!g++ % && ./a.out"
:rv! ~/.pyinfo.vim
|2,0,1621163878,,"rv! ~/.pyinfo.vim"
:tab solve.py
|2,0,1621163878,,"tab solve.py"
:tabf solver.py
|2,0,1621163878,,"tabf solver.py"
:tabf solve.py
|2,0,1621163878,,"tabf solve.py"
:help beffer
|2,0,1621163878,,"help beffer"
:help BufnewFile
|2,0,1621163878,,"help BufnewFile"
:help buffer
|2,0,1621163878,,"help buffer"
:help tabf
|2,0,1621163878,,"help tabf"
:tabf ~./
|2,0,1621163878,,"tabf ~./"
:! cp ~/.cinfo.vim ~/.hinfo.vim
|2,0,1621163878,,"! cp ~/.cinfo.vim ~/.hinfo.vim"
:tabf module.h
|2,0,1621163878,,"tabf module.h"
:t
|2,0,1621163878,,"t"
:reg 
|2,0,1621163878,,"reg "
:%s/\<k\>/e/g
|2,0,1621163878,,"%s/\\<k\\>/e/g"
:rv! ../../c/zeev/cinfo.vim
|2,0,1621163878,,"rv! ../../c/zeev/cinfo.vim"
:scripname
|2,0,1621163878,,"scripname"
:!rv pyinfo.vim
|2,0,1621163878,,"!rv pyinfo.vim"
:rv! pyinfo.vim
|2,0,1621163878,,"rv! pyinfo.vim"
:help viminfo
|2,0,1621163878,,"help viminfo"
:tabnew 
|2,0,1621163878,,"tabnew "
:set relativenumber
|2,0,1621163878,,"set relativenumber"
:ter
|2,0,1621163878,,"ter"
:tabnew main.c
|2,0,1621163878,,"tabnew main.c"
:erg
|2,0,1621163878,,"erg"
:!rv ~/.cinfo.vim
|2,0,1621163878,,"!rv ~/.cinfo.vim"
:rv! ~/.cinfo.vim
|2,0,1621163878,,"rv! ~/.cinfo.vim"
:tabf ~/.cinfo.vim
|2,0,1621163878,,"tabf ~/.cinfo.vim"
:wv ~/.cinfo.vim
|2,0,1621163878,,"wv ~/.cinfo.vim"
:wv!
|2,0,1621163878,,"wv!"
:wv! ~/.cinfo.vim
|2,0,1621163878,,"wv! ~/.cinfo.vim"
:tabf ~/.pyinfo.vim
|2,0,1621163878,,"tabf ~/.pyinfo.vim"
:wv! pyinfo.vim
|2,0,1621163878,,"wv! pyinfo.vim"
:rv pyinfo.vim
|2,0,1621163878,,"rv pyinfo.vim"
:tabnew main.py
|2,0,1621163878,,"tabnew main.py"
:!python3 solve.py
|2,0,1621163878,,"!python3 solve.py"
:w
|2,0,1621163878,,"w"
:!
|2,0,1621163878,,"!"
:s/eqns/eqs/g
|2,0,1621163878,,"s/eqns/eqs/g"
:[
|2,0,1621163878,,"["
:!pip3 install sympy
|2,0,1621163878,,"!pip3 install sympy"
:q
|2,0,1621163878,,"q"
:!python3 sol
|2,0,1621163878,,"!python3 sol"
:set paste
|2,0,1621163878,,"set paste"
:qa
|2,0,1621163878,,"qa"
:help session
|2,0,1621163878,,"help session"
:help rv
|2,0,1621163878,,"help rv"
:tabf cinfo.vim
|2,0,1621163878,,"tabf cinfo.vim"
:tabf pyinfo.vim
|2,0,1621163878,,"tabf pyinfo.vim"
:q!
|2,0,1621163878,,"q!"
:rv cinfo.vim
|2,0,1621163878,,"rv cinfo.vim"
:tab ter
|2,0,1621163878,,"tab ter"
:qa!
|2,0,1621163878,,"qa!"
:wv pyinfo.vim
|2,0,1621163878,,"wv pyinfo.vim"
:put = strftime('%c')
|2,0,1621163878,,"put = strftime('%c')"
:let @" = expand("%")
|2,0,1621163878,,"let @\" = expand(\"%\")"
:set @" = expand("%")
|2,0,1621163878,,"set @\" = expand(\"%\")"
:tabnew main2.py
|2,0,1621163878,,"tabnew main2.py"
:tabf main.c
|2,0,1621163878,,"tabf main.c"
:%y+
|2,0,1621163878,,"%y+"
:wv cinfo.vim
|2,0,1621163878,,"wv cinfo.vim"
:!make
|2,0,1621163878,,"!make"
:tabf ~/.viminfo
|2,0,1621163878,,"tabf ~/.viminfo"
:elseif
|2,0,1621163878,,"elseif"
:endfor
|2,0,1621163878,,"endfor"
:help autocmd
|2,0,1621163878,,"help autocmd"
:close
|2,0,1621163878,,"close"
:help
|2,0,1621163878,,"help"
:vsplit
|2,0,1621163878,,"vsplit"
:help mksession
|2,0,1621163878,,"help mksession"
:make
|2,0,1621163878,,"make"
:E
|2,0,1621163878,,"E"
:tabe
|2,0,1621163878,,"tabe"
:tabnew Makefile
|2,0,1621163878,,"tabnew Makefile"
:1make
|2,0,1621163878,,"1make"
:!ls
|2,0,1621163878,,"!ls"
:!rm Makefile
|2,0,1621163878,,"!rm Makefile"
:wa
|2,0,1621163878,,"wa"
:tabf Makefile
|2,0,1621163878,,"tabf Makefile"
:tabnew
|2,0,1621163878,,"tabnew"
:tabnew module.h
|2,0,1621163878,,"tabnew module.h"
:tabf hello.h
|2,0,1621163878,,"tabf hello.h"
:let @"=expand("%")
|2,0,1621163878,,"let @\"=expand(\"%\")"
:%
|2,0,1621163878,,"%"
:p
|2,0,1621163878,,"p"
:let = expand("%")
|2,0,1621163878,,"let = expand(\"%\")"
:put =strftime('%c')
|2,0,1621163878,,"put =strftime('%c')"
:put strftime('%c')
|2,0,1621163878,,"put strftime('%c')"
:put =expand("%")
|2,0,1621163878,,"put =expand(\"%\")"
:put expand("%")
|2,0,1621163878,,"put expand(\"%\")"
:tabnew hello.h
|2,0,1621163878,,"tabnew hello.h"
:s/\<j\>/k/
|2,0,1621163878,,"s/\\<j\\>/k/"
:split ter
|2,0,1621163878,,"split ter"
:s
|2,0,1621163878,,"s"
:v
|2,0,1621163878,,"v"
:tabnew module_2.h
|2,0,1621163878,,"tabnew module_2.h"
:let @" = explore("%")
|2,0,1621163878,,"let @\" = explore(\"%\")"
:let "@ = expand("%")
|2,0,1621163878,,"let \"@ = expand(\"%\")"
:%s/./_/g
|2,0,1621163878,,"%s/./_/g"
:%s/\<.\>/_/g
|2,0,1621163878,,"%s/\\<.\\>/_/g"
:%s/\<.\>/\<_\>/g
|2,0,1621163878,,"%s/\\<.\\>/\\<_\\>/g"
:%s/\<.\>/./g
|2,0,1621163878,,"%s/\\<.\\>/./g"
:help tabnew
|2,0,1621163878,,"help tabnew"
:tabf module.c module.h
|2,0,1621163878,,"tabf module.c module.h"
:%"cy
|2,0,1621163878,,"%\"cy"
:%yc
|2,0,1621163878,,"%yc"
:%cy
|2,0,1621163878,,"%cy"
:s/\<i\>/j/g
|2,0,1621163878,,"s/\\<i\\>/j/g"
:%=
|2,0,1621163878,,"%="
:s/\<i\>/k/g
|2,0,1621163878,,"s/\\<i\\>/k/g"
:s/\<i\>/kg
|2,0,1621163878,,"s/\\<i\\>/kg"
:%py
|2,0,1621163878,,"%py"
:%"py
|2,0,1621163878,,"%\"py"
:%y"p
|2,0,1621163878,,"%y\"p"
:%yp
|2,0,1621163878,,"%yp"
:re
|2,0,1621163878,,"re"
:%yC
|2,0,1621163878,,"%yC"
:split
|2,0,1621163878,,"split"
:!m
|2,0,1621163878,,"!m"
:wqa
|2,0,1621163878,,"wqa"
:!python3 lucky.py
|2,0,1621163878,,"!python3 lucky.py"
:! g++ 
|2,0,1621163878,,"! g++ "
:%s/data/d/g
|2,0,1621163878,,"%s/data/d/g"
:wq
|2,0,1621163878,,"wq"
:!python3 longest_distance.py
|2,0,1621163878,,"!python3 longest_distance.py"
:!python3
|2,0,1621163878,,"!python3"
:!python3 acronym.py
|2,0,1621163878,,"!python3 acronym.py"
:!python3 acronym.py1
|2,0,1621163878,,"!python3 acronym.py1"
:!pythond3 acronym.py
|2,0,1621163878,,"!pythond3 acronym.py"
:python3 acronym	
|2,0,1621163878,,"python3 acronym	"
:!python3 main.py
|2,0,1621163878,,"!python3 main.py"
:tabf 1.out
|2,0,1621163878,,"tabf 1.out"
:~
|2,0,1621163878,,"~"
:!mk
|2,0,1621163878,,"!mk"
:!mak
|2,0,1621163878,,"!mak"
:!mae
|2,0,1621163878,,"!mae"
:!make 1out
|2,0,1621163878,,"!make 1out"
:s/1/2/g
|2,0,1621163878,,"s/1/2/g"
:!make 1cp
|2,0,1621163878,,"!make 1cp"
:tabnew 1.cmp
|2,0,1621163878,,"tabnew 1.cmp"
:%s/queue/deque/gc
|2,0,1621163878,,"%s/queue/deque/gc"
:tabm 2
|2,0,1621163878,,"tabm 2"
:.!
|2,0,1621163878,,".!"
:wqaa
|2,0,1621163878,,"wqaa"
:mks Session.vim 
|2,0,1621163878,,"mks Session.vim "
:!make cp
|2,0,1621163878,,"!make cp"
:make 1cp
|2,0,1621163878,,"make 1cp"
:make cp
|2,0,1621163878,,"make cp"
:!make 1
|2,0,1621163878,,"!make 1"
:!make 2cp
|2,0,1621163878,,"!make 2cp"
:!make 2
|2,0,1621163878,,"!make 2"
:%s/Prims/Prim's/gc
|2,0,1621163878,,"%s/Prims/Prim's/gc"
:make 2
|2,0,1621163878,,"make 2"
:tabnew 2.in
|2,0,1621163878,,"tabnew 2.in"
:s/prims/Prims/g
|2,0,1621163878,,"s/prims/Prims/g"
:tabf ../1/main.cpp
|2,0,1621163878,,"tabf ../1/main.cpp"
:tabf 1.in
|2,0,1621163878,,"tabf 1.in"
:tabm 1
|2,0,1621163878,,"tabm 1"
:tabf 1.cmp
|2,0,1621163878,,"tabf 1.cmp"
:tabnew 1.out
|2,0,1621163878,,"tabnew 1.out"
:%s/\<n\>/N/gc
|2,0,1621163878,,"%s/\\<n\\>/N/gc"
:'<,'>
|2,0,1621163878,,"'<,'>"
:!mkae
|2,0,1621163878,,"!mkae"
:s/i/j/g
|2,0,1621163878,,"s/i/j/g"
:tabnew main2.cpp
|2,0,1621163878,,"tabnew main2.cpp"
:s/j/n/g
|2,0,1621163878,,"s/j/n/g"
:s/\<count\>/countP/g
|2,0,1621163878,,"s/\\<count\\>/countP/g"
:!mke
|2,0,1621163878,,"!mke"
:!make krusk
|2,0,1621163878,,"!make krusk"
:!rm ./a.out
|2,0,1621163878,,"!rm ./a.out"
:tabf main2.cpp
|2,0,1621163878,,"tabf main2.cpp"
:%y
|2,0,1621163878,,"%y"
:! diff 1.out 1.cmp
|2,0,1621163878,,"! diff 1.out 1.cmp"
:! diff
|2,0,1621163878,,"! diff"
:tabf 1.cm
|2,0,1621163878,,"tabf 1.cm"
:!ma
|2,0,1621163878,,"!ma"
:mks!
|2,0,1621163878,,"mks!"
:!mks
|2,0,1621163878,,"!mks"
:%s/\.\/a\.out/main/g
|2,0,1621163878,,"%s/\\.\\/a\\.out/main/g"
:s/makepair/make_pair/g
|2,0,1621163878,,"s/makepair/make_pair/g"
:ewqa
|2,0,1621163878,,"ewqa"
:%s/convert/str2int/gc
|2,0,1621163878,,"%s/convert/str2int/gc"
:%s/â€™/'/g
|2,0,1621163878,,"%s/â€™/'/g"
:%/â€™/'/g
|2,0,1621163878,,"%/â€™/'/g"
:%s/â€˜/'/g
|2,0,1621163878,,"%s/â€˜/'/g"
:%s/\â€˜/\'/g
|2,0,1621163878,,"%s/\\â€˜/\\'/g"
:%s/\'/\"/g
|2,0,1621163878,,"%s/\\'/\\\"/g"
:%s/'/"/g
|2,0,1621163878,,"%s/'/\"/g"
:%s/small/s/g
|2,0,1621163878,,"%s/small/s/g"
:%s/big/b/g
|2,0,1621163878,,"%s/big/b/g"
:!make all
|2,0,1621163878,,"!make all"
:!make 
|2,0,1621163878,,"!make "
:!mawke
|2,0,1621163878,,"!mawke"
:tabf ./main2.cpp
|2,0,1621163878,,"tabf ./main2.cpp"
:s/,//g
|2,0,1621163878,,"s/,//g"
:Wqa
|2,0,1621163878,,"Wqa"
:tabf ./shapecolour.p
|2,0,1621163878,,"tabf ./shapecolour.p"
:mks Session.vim
|2,0,1621163878,,"mks Session.vim"
:tabf main.cpp
|2,0,1621163878,,"tabf main.cpp"
:%s/.\/a.out/main/g
|2,0,1621163878,,"%s/.\\/a.out/main/g"
:%s/.\/a.out/main.g
|2,0,1621163878,,"%s/.\\/a.out/main.g"
:%s/./a.out/main
|2,0,1621163878,,"%s/./a.out/main"
:tabf 2.out
|2,0,1621163878,,"tabf 2.out"
:!make 1 && make 2
|2,0,1621163878,,"!make 1 && make 2"
:%s/2//gc
|2,0,1621163878,,"%s/2//gc"
:tabf 2.in
|2,0,1621163878,,"tabf 2.in"
:!python
|2,0,1621163878,,"!python"
:tabf output.txt
|2,0,1621163878,,"tabf output.txt"
:!python3 interleavings.py > output.txt
|2,0,1621163878,,"!python3 interleavings.py > output.txt"
:!python3 interleavings.py
|2,0,1621163878,,"!python3 interleavings.py"
:!python3 inter
|2,0,1621163878,,"!python3 inter"
:k
|2,0,1621163878,,"k"
:%s/void/string/gc
|2,0,1621163878,,"%s/void/string/gc"
:%s/&str/str/gc
|2,0,1621163878,,"%s/&str/str/gc"
:s/str\[i\]/c/g
|2,0,1621163878,,"s/str\\[i\\]/c/g"
:s/str[i]/c/g
|2,0,1621163878,,"s/str[i]/c/g"
:%s/char * str/string str/gc
|2,0,1621163878,,"%s/char * str/string str/gc"
:%v
|2,0,1621163878,,"%v"
:s/M/j/g
|2,0,1621163878,,"s/M/j/g"
:%p+
|2,0,1621163878,,"%p+"
:%dp+
|2,0,1621163878,,"%dp+"
:s/_3//g
|2,0,1621163878,,"s/_3//g"
:s/3/ /g
|2,0,1621163878,,"s/3/ /g"
:!./a.out
|2,0,1621163878,,"!./a.out"
:!g++ hello_world.cpp && ./a.out
|2,0,1621163878,,"!g++ hello_world.cpp && ./a.out"
:s/ //g
|2,0,1621163878,,"s/ //g"
:s/i/t/g
|2,0,1621163878,,"s/i/t/g"
:s/i/t
|2,0,1621163878,,"s/i/t"
:tabm 3
|2,0,1621163878,,"tabm 3"
:5y
|2,0,1621163878,,"5y"
:!cat 1.in | python3 main.py
|2,0,1621163878,,"!cat 1.in | python3 main.py"
:python
|2,0,1621163878,,"python"
:%s/ull/ll/g
|2,0,1621163878,,"%s/ull/ll/g"
:%/ull/ll/g
|2,0,1621163878,,"%/ull/ll/g"
:color desert
|2,0,1621163878,,"color desert"
:color industry
|2,0,1621163878,,"color industry"
:tab
|2,0,1621163878,,"tab"
:! make
|2,0,1621163878,,"! make"
:! make 2
|2,0,1621163878,,"! make 2"
:!make 2.in
|2,0,1621163878,,"!make 2.in"
:tabnew 2.out
|2,0,1621163878,,"tabnew 2.out"
:tabf
|2,0,1621163878,,"tabf"
:s/>>/<</g
|2,0,1621163878,,"s/>>/<</g"
:%/>>/<</g
|2,0,1621163878,,"%/>>/<</g"
:!python3 roman.py
|2,0,1621163878,,"!python3 roman.py"
:!g++ main.cpp -fsanitize=address && cat 1.in | ./a.out
|2,0,1621163878,,"!g++ main.cpp -fsanitize=address && cat 1.in | ./a.out"
:!g++ main.cpp && cat 1.in | ./a.out
|2,0,1621163878,,"!g++ main.cpp && cat 1.in | ./a.out"
:%s/[nx][ny]/[ny][nx]/gc
|2,0,1621163878,,"%s/[nx][ny]/[ny][nx]/gc"
:e
|2,0,1621163878,,"e"
:%s/long long/int/g
|2,0,1621163878,,"%s/long long/int/g"
:tabf ~
|2,0,1621163878,,"tabf ~"
:%s/long long/unsigned long long/g
|2,0,1621163878,,"%s/long long/unsigned long long/g"
:%/long long/unsigned long long/g
|2,0,1621163878,,"%/long long/unsigned long long/g"
:!g++ --version
|2,0,1621163878,,"!g++ --version"
:s/a/b/g
|2,0,1621163878,,"s/a/b/g"
:! g++ lims.cpp && ./a.out
|2,0,1621163878,,"! g++ lims.cpp && ./a.out"
:g++ lims.cpp && ./a.out
|2,0,1621163878,,"g++ lims.cpp && ./a.out"
:tabf Main.jack
|2,0,1621163878,,"tabf Main.jack"
:tabf Square.xml
|2,0,1621163878,,"tabf Square.xml"
:tabm 0
|2,0,1621163878,,"tabm 0"
:! TextCompare
|2,0,1621163878,,"! TextCompare"
:! TextComparer SquareGameT.JT.xml SquareGameT.xml
|2,0,1621163878,,"! TextComparer SquareGameT.JT.xml SquareGameT.xml"
:! TextComparer
|2,0,1621163878,,"! TextComparer"
:! diff SquareGameT.JT.xml SquareGameT.xml
|2,0,1621163878,,"! diff SquareGameT.JT.xml SquareGameT.xml"
:tabf SquareGameT.xml
|2,0,1621163878,,"tabf SquareGameT.xml"
:tabf ./ExpressionLessSquare/Square.xml
|2,0,1621163878,,"tabf ./ExpressionLessSquare/Square.xml"
:!make jack_tokenizer
|2,0,1621163878,,"!make jack_tokenizer"
:tabf jack_tokenizer.py
|2,0,1621163878,,"tabf jack_tokenizer.py"
:tabnew CodeReader.py
|2,0,1621163878,,"tabnew CodeReader.py"
:!make express
|2,0,1621163878,,"!make express"
:! pwd
|2,0,1621163878,,"! pwd"
:Explore
|2,0,1621163878,,"Explore"
:tabf ./ExpressionLessSquare/Main.jack
|2,0,1621163878,,"tabf ./ExpressionLessSquare/Main.jack"
:tabe 
|2,0,1621163878,,"tabe "
:! source ./JackAnalyser/bin/activate
|2,0,1621163878,,"! source ./JackAnalyser/bin/activate"
:!python3 JackAnalyser.py
|2,0,1621163878,,"!python3 JackAnalyser.py"
:python3 JackAnalyser.py
|2,0,1621163878,,"python3 JackAnalyser.py"
:! make d.in
|2,0,1621163878,,"! make d.in"
:tabnew d.in
|2,0,1621163878,,"tabnew d.in"
:tabf d.in
|2,0,1621163878,,"tabf d.in"
:! make i.in
|2,0,1621163878,,"! make i.in"
:.,.+1!
|2,0,1621163878,,".,.+1!"
:s/1/0/g
|2,0,1621163878,,"s/1/0/g"
:s/0/1/g
|2,0,1621163878,,"s/0/1/g"
:!xdg-open .
|2,0,1621163878,,"!xdg-open ."
:! python3 main.py
|2,0,1621163878,,"! python3 main.py"
:!make i.in
|2,0,1621163878,,"!make i.in"
:! xdg-open ../
|2,0,1621163878,,"! xdg-open ../"
:tabf ../guess/1.in
|2,0,1621163878,,"tabf ../guess/1.in"
:%s/var/val/g
|2,0,1621163878,,"%s/var/val/g"
:tabnew parser.h
|2,0,1621163878,,"tabnew parser.h"
:tabnew binary_tree.h
|2,0,1621163878,,"tabnew binary_tree.h"
:tabnew binary_tree.cpp
|2,0,1621163878,,"tabnew binary_tree.cpp"
:! g++ main.c
|2,0,1621163878,,"! g++ main.c"
:! make py
|2,0,1621163878,,"! make py"
:!autopep8 -i main.py
|2,0,1621163878,,"!autopep8 -i main.py"
:tabm 4
|2,0,1621163878,,"tabm 4"
:!pip3 install autopep8
|2,0,1621163878,,"!pip3 install autopep8"
:!autopep8
|2,0,1621163878,,"!autopep8"
:retab!
|2,0,1621163878,,"retab!"
:tabf ~/.vimrc
|2,0,1621163878,,"tabf ~/.vimrc"
:ret
|2,0,1621163878,,"ret"
:!make py
|2,0,1621163878,,"!make py"
:tabnew output.txt
|2,0,1621163878,,"tabnew output.txt"
:%s/string/hello/g
|2,0,1621163878,,"%s/string/hello/g"
:qs
|2,0,1621163878,,"qs"
:! python3 password.py
|2,0,1621163878,,"! python3 password.py"
:tabf GameState.jack
|2,0,1621163878,,"tabf GameState.jack"
:s/0/2/g
|2,0,1621163878,,"s/0/2/g"
:tabnew GameState.jack
|2,0,1621163878,,"tabnew GameState.jack"
:tabf ./KeyListener.jack
|2,0,1621163878,,"tabf ./KeyListener.jack"
:tabnew KeyListener.jack
|2,0,1621163878,,"tabnew KeyListener.jack"
:tabnew TicTac.jack
|2,0,1621163878,,"tabnew TicTac.jack"
:tabf State.jack
|2,0,1621163878,,"tabf State.jack"
:tabf Cell.jack
|2,0,1621163878,,"tabf Cell.jack"
:Wa
|2,0,1621163878,,"Wa"
:tabnew State.jack
|2,0,1621163878,,"tabnew State.jack"
:tabnew Cell.jack
|2,0,1621163878,,"tabnew Cell.jack"
::w
|2,0,1621163878,,":w"
:mksession Session.vim
|2,0,1621163878,,"mksession Session.vim"
:tabnew White.jack
|2,0,1621163878,,"tabnew White.jack"
:tabnew Cross.jack
|2,0,1621163878,,"tabnew Cross.jack"
:tabnew Empty.jack
|2,0,1621163878,,"tabnew Empty.jack"
:%s/circle/circle2/gc
|2,0,1621163878,,"%s/circle/circle2/gc"
:tabf ../Fraction/Fraction.jack
|2,0,1621163878,,"tabf ../Fraction/Fraction.jack"
:tabf ../Average/Main.jack
|2,0,1621163878,,"tabf ../Average/Main.jack"
:tabf ../Fraction/Main.jack
|2,0,1621163878,,"tabf ../Fraction/Main.jack"
:tabf ../HelloWorld/Main.jack
|2,0,1621163878,,"tabf ../HelloWorld/Main.jack"
:!JackCompiler ../
|2,0,1621163878,,"!JackCompiler ../"
:!tabf ../HelloWorld/Main.jack
|2,0,1621163878,,"!tabf ../HelloWorld/Main.jack"
:tabnew Main.jack
|2,0,1621163878,,"tabnew Main.jack"
::::::::::!
|2,0,1621163878,,":::::::::!"
:Qa
|2,0,1621163878,,"Qa"
:1
|2,0,1621163878,,"1"
:W
|2,0,1621163878,,"W"
:tabnew 1.in
|2,0,1621163878,,"tabnew 1.in"
:'<,'>!
|2,0,1621163878,,"'<,'>!"
:!make add
|2,0,1621163878,,"!make add"
:!make stack
|2,0,1621163878,,"!make stack"
:!make static
|2,0,1621163878,,"!make static"
:!make pointer
|2,0,1621163878,,"!make pointer"
:!make basic
|2,0,1621163878,,"!make basic"
:!make fibs
|2,0,1621163878,,"!make fibs"
:!make simple
|2,0,1621163878,,"!make simple"
:!make nested
|2,0,1621163878,,"!make nested"
:!make fibe
|2,0,1621163878,,"!make fibe"
:!make statics
|2,0,1621163878,,"!make statics"
:!VMEmulator
|2,0,1621163878,,"!VMEmulator"
:Explore 
|2,0,1621163878,,"Explore "
:tabf ./FunctionCalls/StaticsTest/StaticsTest.asm
|2,0,1621163878,,"tabf ./FunctionCalls/StaticsTest/StaticsTest.asm"
:tabf ./FunctionCalls/StaticsTest/Class1.asm
|2,0,1621163878,,"tabf ./FunctionCalls/StaticsTest/Class1.asm"
:make statics
|2,0,1621163878,,"make statics"
:make nested
|2,0,1621163878,,"make nested"
:make nest
|2,0,1621163878,,"make nest"
:tabf ./FunctionCalls/NestedCall/Sys.vm
|2,0,1621163878,,"tabf ./FunctionCalls/NestedCall/Sys.vm"
:tabf ./FunctionCalls/
|2,0,1621163878,,"tabf ./FunctionCalls/"
:tabf 
|2,0,1621163878,,"tabf "
:make simple
|2,0,1621163878,,"make simple"
:make fibe
|2,0,1621163878,,"make fibe"
:tabf ./ProgramFlow/FibonacciSeries/FibonacciSeries.vm
|2,0,1621163878,,"tabf ./ProgramFlow/FibonacciSeries/FibonacciSeries.vm"
:tabf ./FunctionCalls/FibonacciElement/FibonacciElement.asm
|2,0,1621163878,,"tabf ./FunctionCalls/FibonacciElement/FibonacciElement.asm"
::q
|2,0,1621163878,,":q"
:make fibs
|2,0,1621163878,,"make fibs"
:tabf ./FunctionCalls/FibonacciElement/Main.vm
|2,0,1621163878,,"tabf ./FunctionCalls/FibonacciElement/Main.vm"
:tabf ./VMTranslator/
|2,0,1621163878,,"tabf ./VMTranslator/"
:make basic
|2,0,1621163878,,"make basic"
:! make fibe
|2,0,1621163878,,"! make fibe"
:find ./VMTranslator.py
|2,0,1621163878,,"find ./VMTranslator.py"
:! ls
|2,0,1621163878,,"! ls"
:make static
|2,0,1621163878,,"make static"
:make pointer
|2,0,1621163878,,"make pointer"
:make stack
|2,0,1621163878,,"make stack"
:make add
|2,0,1621163878,,"make add"
:make 
|2,0,1621163878,,"make "
:! python3
|2,0,1621163878,,"! python3"
:tabf FibonacciSeries.asm
|2,0,1621163878,,"tabf FibonacciSeries.asm"
:tabf ProgramFlow/FibonacciSeries/FibonacciSeries.tst
|2,0,1621163878,,"tabf ProgramFlow/FibonacciSeries/FibonacciSeries.tst"
:tabf ProgramFlow/FibonacciSeries/FibonacciSeries.tst
|2,0,1621163878,,"tabf ProgramFlow/FibonacciSeries/FibonacciSeries.tst"
:! make fibs
|2,0,1621163878,,"! make fibs"
:tabf ./ProgramFlow/BasicLoop/BasicLoop.vm
|2,0,1621163878,,"tabf ./ProgramFlow/BasicLoop/BasicLoop.vm"
:! CPUEmulator
|2,0,1621163878,,"! CPUEmulator"
:find ./ProgramFlow/
|2,0,1621163878,,"find ./ProgramFlow/"
:tab all
|2,0,1621163878,,"tab all"
:args ./*/*/*.vm
|2,0,1621163878,,"args ./*/*/*.vm"
:next ./*/*/*.vm
|2,0,1621163878,,"next ./*/*/*.vm"
:help tab
|2,0,1621163878,,"help tab"
:n ./*/*/*.vm
|2,0,1621163878,,"n ./*/*/*.vm"
:tabf ./*/*/*.vm
|2,0,1621163878,,"tabf ./*/*/*.vm"
:18,26fo
|2,0,1621163878,,"18,26fo"
:set foldmethod=expr
|2,0,1621163878,,"set foldmethod=expr"
:set foldmethod?
|2,0,1621163878,,"set foldmethod?"
:set codefold?
|2,0,1621163878,,"set codefold?"
:set codefolding?
|2,0,1621163878,,"set codefolding?"
:18,8fo
|2,0,1621163878,,"18,8fo"
:set foldmethod=manual
|2,0,1621163878,,"set foldmethod=manual"
:! vim ~/.vimrc
|2,0,1621163878,,"! vim ~/.vimrc"
:marks
|2,0,1621163878,,"marks"
:help foldmethod
|2,0,1621163878,,"help foldmethod"
:set foldmethod
|2,0,1621163878,,"set foldmethod"
:foldmethod
|2,0,1621163878,,"foldmethod"
:tabf ../07/VMTranslator.py
|2,0,1621163878,,"tabf ../07/VMTranslator.py"
:! make all
|2,0,1621163878,,"! make all"
:! make stack
|2,0,1621163878,,"! make stack"
:!make poiniter
|2,0,1621163878,,"!make poiniter"
:tabf ./MemoryAccess/PointerTest/PointerTest.asm
|2,0,1621163878,,"tabf ./MemoryAccess/PointerTest/PointerTest.asm"
:!CPUEmulator
|2,0,1621163878,,"!CPUEmulator"
:tabf ../08/VMTranslator.py
|2,0,1621163878,,"tabf ../08/VMTranslator.py"
:source Session.vim
|2,0,1621163878,,"source Session.vim"
:! CPUEmulator ./StackArithmetic/SimpleAdd/SimpleAdd.tst
|2,0,1621163878,,"! CPUEmulator ./StackArithmetic/SimpleAdd/SimpleAdd.tst"
:tabf ProgramFlow/BasicLoop/*.asm
|2,0,1621163878,,"tabf ProgramFlow/BasicLoop/*.asm"
:tabf ./ProgramFlow/BasicLoop/BasicLoop.asm
|2,0,1621163878,,"tabf ./ProgramFlow/BasicLoop/BasicLoop.asm"
:! make basic
|2,0,1621163878,,"! make basic"
:tabf ProgramFlow/BasicLoop/BasicLoop.vm
|2,0,1621163878,,"tabf ProgramFlow/BasicLoop/BasicLoop.vm"
:!. VMTranslator/bin/activate && python3 VMTranslator.py FunctionCalls/StaticsTest/Class1.vm &&  deactivate
|2,0,1621163878,,"!. VMTranslator/bin/activate && python3 VMTranslator.py FunctionCalls/StaticsTest/Class1.vm &&  deactivate"
:! 	. VMTranslator/bin/activate && \	python3 VMTranslator.py FunctionCalls/StaticsTest/Class1.vm && \	deactivate
|2,0,1621163878,,"! 	. VMTranslator/bin/activate && \\	python3 VMTranslator.py FunctionCalls/StaticsTest/Class1.vm && \\	deactivate"
:!ad
|2,0,1621163878,,"!ad"
:! make nested
|2,0,1621163878,,"! make nested"
:! man split
|2,0,1621163878,,"! man split"
:!py
|2,0,1621163878,,"!py"
:explore
|2,0,1621163878,,"explore"
:! VMEmulator
|2,0,1621163878,,"! VMEmulator"
:tabf pulse/
|2,0,1621163878,,"tabf pulse/"
:! make add
|2,0,1621163878,,"! make add"
:! make 
|2,0,1621163878,,"! make "
:m
|2,0,1621163878,,"m"
:makrs
|2,0,1621163878,,"makrs"
:mark
|2,0,1621163878,,"mark"
:makr
|2,0,1621163878,,"makr"
:tabf ./StackArithmetic/SimpleAdd/SimpleAdd.asm
|2,0,1621163878,,"tabf ./StackArithmetic/SimpleAdd/SimpleAdd.asm"
:%s/sp/SP/gc
|2,0,1621163878,,"%s/sp/SP/gc"
:! python
|2,0,1621163878,,"! python"
:mak
|2,0,1621163878,,"mak"
:tabf *.py
|2,0,1621163878,,"tabf *.py"
:args ./StackArithmetic/*/*.vm
|2,0,1621163878,,"args ./StackArithmetic/*/*.vm"
:tabf ./StackArithmetic/*/*.vm
|2,0,1621163878,,"tabf ./StackArithmetic/*/*.vm"
:tabf ../StackTest/StackTest.vm
|2,0,1621163878,,"tabf ../StackTest/StackTest.vm"
:! python3 integers.py
|2,0,1621163878,,"! python3 integers.py"
:!make 1.in
|2,0,1621163878,,"!make 1.in"
:! make 1.in
|2,0,1621163878,,"! make 1.in"
:make 1.in
|2,0,1621163878,,"make 1.in"
:m!
|2,0,1621163878,,"m!"
:! cat 1.in | ./a.out
|2,0,1621163878,,"! cat 1.in | ./a.out"
:! g++ main.cpp -fsanitize=address
|2,0,1621163878,,"! g++ main.cpp -fsanitize=address"
:tabf ./pong/cmp.hack
|2,0,1621163878,,"tabf ./pong/cmp.hack"
:! diff pong/Pong.hack pong/cmp.hack
|2,0,1621163878,,"! diff pong/Pong.hack pong/cmp.hack"
:! mv cmp.hack pong/
|2,0,1621163878,,"! mv cmp.hack pong/"
:mv cmp.hack pong/
|2,0,1621163878,,"mv cmp.hack pong/"
:! mv Pong.hack cmp.hack
|2,0,1621163878,,"! mv Pong.hack cmp.hack"
:! wget https://github.com/jtdowney/nand2tetris/blob/master/06/pong/Pong.hack
|2,0,1621163878,,"! wget https://github.com/jtdowney/nand2tetris/blob/master/06/pong/Pong.hack"
:tabnew pong/cmp.hack
|2,0,1621163878,,"tabnew pong/cmp.hack"
:! make pong
|2,0,1621163878,,"! make pong"
:! diff max/Max.hack max/cmp.hack
|2,0,1621163878,,"! diff max/Max.hack max/cmp.hack"
:tabnew max/cmp.hack
|2,0,1621163878,,"tabnew max/cmp.hack"
:tabf max/Max.hack
|2,0,1621163878,,"tabf max/Max.hack"
:! make max
|2,0,1621163878,,"! make max"
:! diff add/Add.hack add/cmp.hack
|2,0,1621163878,,"! diff add/Add.hack add/cmp.hack"
:tabnew add/cmp.hack
|2,0,1621163878,,"tabnew add/cmp.hack"
:tabf add/Add.hack
|2,0,1621163878,,"tabf add/Add.hack"
:! diff rect/Rect.hack rect/cmp.hack
|2,0,1621163878,,"! diff rect/Rect.hack rect/cmp.hack"
:tabnew rect/cmp.hack
|2,0,1621163878,,"tabnew rect/cmp.hack"
:tabf rect/cmp.hack
|2,0,1621163878,,"tabf rect/cmp.hack"
:tabf rect/Rect.hack
|2,0,1621163878,,"tabf rect/Rect.hack"
:! make rect
|2,0,1621163878,,"! make rect"
:! ls -la
|2,0,1621163878,,"! ls -la"
:make pong
|2,0,1621163878,,"make pong"
:make sum
|2,0,1621163878,,"make sum"
:ma
|2,0,1621163878,,"ma"
:make rect
|2,0,1621163878,,"make rect"
:make max
|2,0,1621163878,,"make max"
:make add.asm
|2,0,1621163878,,"make add.asm"
:make pong.asm
|2,0,1621163878,,"make pong.asm"
:mks
|2,0,1621163878,,"mks"
:find Makefile
|2,0,1621163878,,"find Makefile"
:! python3 Assembler.py
|2,0,1621163878,,"! python3 Assembler.py"
:! g++ main.cpp && ./a.out
|2,0,1621163878,,"! g++ main.cpp && ./a.out"
:! g++ main.cpp && cat 2.in | ./a.out
|2,0,1621163878,,"! g++ main.cpp && cat 2.in | ./a.out"
:make 2.in
|2,0,1621163878,,"make 2.in"
:! HardwareSimulator Mult.tst
|2,0,1621163878,,"! HardwareSimulator Mult.tst"
:%s/Hash/HashTable/gc
|2,0,1621163878,,"%s/Hash/HashTable/gc"
:! HardwareSimulator
|2,0,1621163878,,"! HardwareSimulator"
:! HardwareSimulator Computer.tst
|2,0,1621163878,,"! HardwareSimulator Computer.tst"
:tabf Memory.hdl
|2,0,1621163878,,"tabf Memory.hdl"
:tabf CPU.hdl
|2,0,1621163878,,"tabf CPU.hdl"
:! HardwareSimulator Memory.tst
|2,0,1621163878,,"! HardwareSimulator Memory.tst"
:! HardwareSimulator CPU.tst
|2,0,1621163878,,"! HardwareSimulator CPU.tst"
:Q!
|2,0,1621163878,,"Q!"
:tabf FillAutomatic.tst
|2,0,1621163878,,"tabf FillAutomatic.tst"
:tabf *.tst
|2,0,1621163878,,"tabf *.tst"
:tabf Fill.tst
|2,0,1621163878,,"tabf Fill.tst"
:! HardwareSimulator PC.tst
|2,0,1621163878,,"! HardwareSimulator PC.tst"
:tabf .
|2,0,1621163878,,"tabf ."
:! HardwareSimulator RAM16K.tst
|2,0,1621163878,,"! HardwareSimulator RAM16K.tst"
:tabf RAM16K.hdl
|2,0,1621163878,,"tabf RAM16K.hdl"
:! HardwareSimulator RAM4K.tst
|2,0,1621163878,,"! HardwareSimulator RAM4K.tst"
:tabf RAM4K.hdl
|2,0,1621163878,,"tabf RAM4K.hdl"
:! HardwareSimulator RAM512.tst
|2,0,1621163878,,"! HardwareSimulator RAM512.tst"
:tab ~/.vimrc
|2,0,1621163878,,"tab ~/.vimrc"
:! HardwareSimulator RAM64.tst
|2,0,1621163878,,"! HardwareSimulator RAM64.tst"
:tabf RAM64.hdl
|2,0,1621163878,,"tabf RAM64.hdl"
:ta
|2,0,1621163878,,"ta"
:tabf Bit.hdl
|2,0,1621163878,,"tabf Bit.hdl"
:tabf Bit.cmp
|2,0,1621163878,,"tabf Bit.cmp"
:tabf Register.hdl
|2,0,1621163878,,"tabf Register.hdl"
:! HardwareSimulator RAM8.tst
|2,0,1621163878,,"! HardwareSimulator RAM8.tst"
:! HardwareSimulator Register.tst
|2,0,1621163878,,"! HardwareSimulator Register.tst"
:! HardwareSimulator Bit.tst
|2,0,1621163878,,"! HardwareSimulator Bit.tst"
:! HardwareSimulator Bit.hdl
|2,0,1621163878,,"! HardwareSimulator Bit.hdl"
:! g++ main.cpp && cat 1.in | ./a.out
|2,0,1621163878,,"! g++ main.cpp && cat 1.in | ./a.out"
:%s/visited/dist/gc
|2,0,1621163878,,"%s/visited/dist/gc"
:%s/visited/dist/g/c
|2,0,1621163878,,"%s/visited/dist/g/c"
:! g++ reading.cpp && cat 1.in | ./a.out
|2,0,1621163878,,"! g++ reading.cpp && cat 1.in | ./a.out"
:tabf reading.cpp
|2,0,1621163878,,"tabf reading.cpp"
:tabf values.h
|2,0,1621163878,,"tabf values.h"
:tabnew reading.cpp
|2,0,1621163878,,"tabnew reading.cpp"
:make 1.n
|2,0,1621163878,,"make 1.n"
:%s/SortedHeap/sortedHeap/g
|2,0,1621163878,,"%s/SortedHeap/sortedHeap/g"
:make !.in
|2,0,1621163878,,"make !.in"
:%s/size/sz/gc
|2,0,1621163878,,"%s/size/sz/gc"
:make 1.ini
|2,0,1621163878,,"make 1.ini"
:source Makefile
|2,0,1621163878,,"source Makefile"
:make 1
|2,0,1621163878,,"make 1"
:edit main.cpp
|2,0,1621163878,,"edit main.cpp"
:! HardwareSimulator ALU.tst
|2,0,1621163878,,"! HardwareSimulator ALU.tst"
:! HardwareSimulator Or8Way.tst
|2,0,1621163878,,"! HardwareSimulator Or8Way.tst"
:! HardwareSimulator Or8Way.hdl
|2,0,1621163878,,"! HardwareSimulator Or8Way.hdl"
:! HardwareSimulator Add16.tst
|2,0,1621163878,,"! HardwareSimulator Add16.tst"
:! HardwareSimulator Add16.hdl
|2,0,1621163878,,"! HardwareSimulator Add16.hdl"
:tabf Add16.hdl
|2,0,1621163878,,"tabf Add16.hdl"
:s/zx/f/g
|2,0,1621163878,,"s/zx/f/g"
:s/x/y/g
|2,0,1621163878,,"s/x/y/g"
:! HardwareSimulator DMux8Way.tst
|2,0,1621163878,,"! HardwareSimulator DMux8Way.tst"
:%s/And/Xor/gc
|2,0,1621163878,,"%s/And/Xor/gc"
:tabnew Xor16.hdl
|2,0,1621163878,,"tabnew Xor16.hdl"
:tabf Mux8Way16.hdl
|2,0,1621163878,,"tabf Mux8Way16.hdl"
:! HardwareSimulator DMux4Way.tst
|2,0,1621163878,,"! HardwareSimulator DMux4Way.tst"
:! HardwareSimulator Mux8Way16.tst
|2,0,1621163878,,"! HardwareSimulator Mux8Way16.tst"
:! HardwareSimulator Mux4Way16.tst
|2,0,1621163878,,"! HardwareSimulator Mux4Way16.tst"
:tabf Mux4Way16.out
|2,0,1621163878,,"tabf Mux4Way16.out"
:tabf Mux4Way16.cmp
|2,0,1621163878,,"tabf Mux4Way16.cmp"
:tabf Mux16.hdl
|2,0,1621163878,,"tabf Mux16.hdl"
:! HardwareSimulator Mux16.tst
|2,0,1621163878,,"! HardwareSimulator Mux16.tst"
:find
|2,0,1621163878,,"find"
:tabf Or.hdl
|2,0,1621163878,,"tabf Or.hdl"
:!HardwareSimulator Mux16.tst
|2,0,1621163878,,"!HardwareSimulator Mux16.tst"
:tabf Mux.hdl
|2,0,1621163878,,"tabf Mux.hdl"
:!HardwareSimulator And16.tst
|2,0,1621163878,,"!HardwareSimulator And16.tst"
:!HardwareSimulator Or16.tst
|2,0,1621163878,,"!HardwareSimulator Or16.tst"
:!HardwareSimulator And.tst
|2,0,1621163878,,"!HardwareSimulator And.tst"
:! HardwareSimulator Not16.tst
|2,0,1621163878,,"! HardwareSimulator Not16.tst"
:! HardwareSimulator DMux.tst
|2,0,1621163878,,"! HardwareSimulator DMux.tst"
:s/sel/in/g
|2,0,1621163878,,"s/sel/in/g"
:! HardwareSimulator Mux.tst
|2,0,1621163878,,"! HardwareSimulator Mux.tst"
:s/s/sel/g
|2,0,1621163878,,"s/s/sel/g"
:! HardwareSimulator Xor.tst
|2,0,1621163878,,"! HardwareSimulator Xor.tst"
:! HardwareSimulator Or.tst
|2,0,1621163878,,"! HardwareSimulator Or.tst"
:tabf Not.hdl
|2,0,1621163878,,"tabf Not.hdl"
:! HardwareSimulator And.tst
|2,0,1621163878,,"! HardwareSimulator And.tst"
:%s/bfs/dfs/gc
|2,0,1621163878,,"%s/bfs/dfs/gc"
:amke
|2,0,1621163878,,"amke"
:make prim
|2,0,1621163878,,"make prim"
:%s/\\/ /gc
|2,0,1621163878,,"%s/\\\\/ /gc"
:make all
|2,0,1621163878,,"make all"
:source prim.vim
|2,0,1621163878,,"source prim.vim"
:tabf 1.in 2.in
|2,0,1621163878,,"tabf 1.in 2.in"
:mksession prim.vim
|2,0,1621163878,,"mksession prim.vim"
:type -a time
|2,0,1621163878,,"type -a time"
:time
|2,0,1621163878,,"time"
:cd ..
|2,0,1621163878,,"cd .."
:ls
|2,0,1621163878,,"ls"
:tabf Session.vim
|2,0,1621163878,,"tabf Session.vim"
:make1
|2,0,1621163878,,"make1"
:tabnew 1.in Makefile -p
|2,0,1621163878,,"tabnew 1.in Makefile -p"
:source S
|2,0,1621163878,,"source S"
:make 5
|2,0,1621163878,,"make 5"
:tabnew 5.in
|2,0,1621163878,,"tabnew 5.in"
:make 4
|2,0,1621163878,,"make 4"
:tabnew 4.in
|2,0,1621163878,,"tabnew 4.in"
:make 3
|2,0,1621163878,,"make 3"
:tabnew 3.in
|2,0,1621163878,,"tabnew 3.in"
:s/i/x/gc
|2,0,1621163878,,"s/i/x/gc"
:ake
|2,0,1621163878,,"ake"
:mae
|2,0,1621163878,,"mae"
:male
|2,0,1621163878,,"male"
:make test
|2,0,1621163878,,"make test"
:source
|2,0,1621163878,,"source"
:%s/c/
|2,0,1621163878,,"%s/c/"
:mkae
|2,0,1621163878,,"mkae"
:make test3
|2,0,1621163878,,"make test3"
:make test2
|2,0,1621163878,,"make test2"
:tabf make
|2,0,1621163878,,"tabf make"
:tabf /etc/vim/vimrc
|2,0,1621163878,,"tabf /etc/vim/vimrc"
:tabf ~/.vim/
|2,0,1621163878,,"tabf ~/.vim/"
:!man vim
|2,0,1621163878,,"!man vim"
:!man std::cout 
|2,0,1621163878,,"!man std::cout "
:!man cout
|2,0,1621163878,,"!man cout"
:vsplit yo.cpp
|2,0,1621163878,,"vsplit yo.cpp"
:hsplit hello.cpp
|2,0,1621163878,,"hsplit hello.cpp"
:split file2
|2,0,1621163878,,"split file2"
:Vtabnew hello.cpp
|2,0,1621163878,,"Vtabnew hello.cpp"
:tabf ./sess.vim
|2,0,1621163878,,"tabf ./sess.vim"
:mksession sess.vim
|2,0,1621163878,,"mksession sess.vim"
:h next
|2,0,1621163878,,"h next"
:tabf /usr/share/vim/vimrc
|2,0,1621163878,,"tabf /usr/share/vim/vimrc"
:w!
|2,0,1621163878,,"w!"
:wq!
|2,0,1621163878,,"wq!"
:scriptnames
|2,0,1621163878,,"scriptnames"
:s/std::pair<long long, int>/ipair/gc
|2,0,1621163878,,"s/std::pair<long long, int>/ipair/gc"
:Wq
|2,0,1621163878,,"Wq"
:wqwa
|2,0,1621163878,,"wqwa"
:%s/vector<list/list<list/gc
|2,0,1621163878,,"%s/vector<list/list<list/gc"
:tabf ../4_set_range_sum/set_range_sum.cpp
|2,0,1621163878,,"tabf ../4_set_range_sum/set_range_sum.cpp"
:s/v/T->root/g
|2,0,1621163878,,"s/v/T->root/g"
:s/v/root/g
|2,0,1621163878,,"s/v/root/g"
:set nopaste
|2,0,1621163878,,"set nopaste"
:%s/R/v/gc
|2,0,1621163878,,"%s/R/v/gc"
:%s/R/
|2,0,1621163878,,"%s/R/"
:tabf ../*4/*.cpp
|2,0,1621163878,,"tabf ../*4/*.cpp"
:set shiftwidth=2
|2,0,1621163878,,"set shiftwidth=2"
:set tabstop=2
|2,0,1621163878,,"set tabstop=2"
:set tabstop=4
|2,0,1621163878,,"set tabstop=4"
:s/MAX/MIN/g
|2,0,1621163878,,"s/MAX/MIN/g"
:tabf src/publish_address_book.cpp
|2,0,1621163878,,"tabf src/publish_address_book.cpp"
:tabf msg/AddressBook.msg
|2,0,1621163878,,"tabf msg/AddressBook.msg"
:tabf package.xml
|2,0,1621163878,,"tabf package.xml"
:tabnew src/publish_address_book.cpp
|2,0,1621163878,,"tabnew src/publish_address_book.cpp"
:tabf ..
|2,0,1621163878,,"tabf .."
:tabf CMakeLists.txt
|2,0,1621163878,,"tabf CMakeLists.txt"
:findf ~/.vimrc
|2,0,1621163878,,"findf ~/.vimrc"
:h shiftwidth
|2,0,1621163878,,"h shiftwidth"
:h shiftwidth()
|2,0,1621163878,,"h shiftwidth()"
:h tabstop
|2,0,1621163878,,"h tabstop"
:set shiftwidth=4
|2,0,1621163878,,"set shiftwidth=4"
:vim ~/.vimrc
|2,0,1621163878,,"vim ~/.vimrc"
:set expandtab=2
|2,0,1621163878,,"set expandtab=2"
:set expandtab 2
|2,0,1621163878,,"set expandtab 2"
:h expandtab
|2,0,1621163878,,"h expandtab"
:h find
|2,0,1621163878,,"h find"
:tabf ../CMakeLists.txt
|2,0,1621163878,,"tabf ../CMakeLists.txt"
:tabf ../
|2,0,1621163878,,"tabf ../"
:tabnew subscriber_member_function2.cpp
|2,0,1621163878,,"tabnew subscriber_member_function2.cpp"
:w !python3
|2,0,1621163878,,"w !python3"
:w !python
|2,0,1621163878,,"w !python"
:help folding
|2,0,1621163878,,"help folding"
:set foldmethod=syntax
|2,0,1621163878,,"set foldmethod=syntax"
:foldmethod=syntax
|2,0,1621163878,,"foldmethod=syntax"
:set lbr
|2,0,1621163878,,"set lbr"
:set formatoptions=l
|2,0,1621163878,,"set formatoptions=l"
:set breakindent
|2,0,1621163878,,"set breakindent"
:set wrap
|2,0,1621163878,,"set wrap"
:version
|2,0,1621163878,,"version"
:tabnew first_vim.py
|2,0,1621163878,,"tabnew first_vim.py"
:Helptags
|2,0,1621163878,,"Helptags"
:checkhealth
|2,0,1621163878,,"checkhealth"
:%y*
|2,0,1621163878,,"%y*"
:scripnames
|2,0,1621163878,,"scripnames"
:python3 %
|2,0,1621163878,,"python3 %"
:help Session
|2,0,1621163878,,"help Session"
:!python3 %
|2,0,1621163878,,"!python3 %"
:wv ~/.pyinfo.vim
|2,0,1621163878,,"wv ~/.pyinfo.vim"
:s/hey/Hey/g
|2,0,1621163878,,"s/hey/Hey/g"
:wv! ~/.hinfo.vim
|2,0,1621163878,,"wv! ~/.hinfo.vim"
:reg d
|2,0,1621163878,,"reg d"
:tabm2
|2,0,1621163878,,"tabm2"
:let @" =expand("%")
|2,0,1621163878,,"let @\" =expand(\"%\")"
:s/\<ab\>/a/g
|2,0,1621163878,,"s/\\<ab\\>/a/g"
:s/\<cd\>/b/g
|2,0,1621163878,,"s/\\<cd\\>/b/g"
:s/a/ab/g
|2,0,1621163878,,"s/a/ab/g"
:s/\<b\>/cd/g
|2,0,1621163878,,"s/\\<b\\>/cd/g"
:vsplit intro.txt
|2,0,1621163878,,"vsplit intro.txt"
:%s/hello/goodbye/g
|2,0,1621163878,,"%s/hello/goodbye/g"
:vsplit main.c
|2,0,1621163878,,"vsplit main.c"
:s/\<j\>/k/g
|2,0,1621163878,,"s/\\<j\\>/k/g"
:tabnew mod.h
|2,0,1621163878,,"tabnew mod.h"
:tabf main.py
|2,0,1621163878,,"tabf main.py"
:reg v
|2,0,1621163819,,"reg v"
:YcmRestartServer
|2,0,1621163196,,"YcmRestartServer"
:let "+ = expand("%")
|2,0,1621158539,,"let \"+ = expand(\"%\")"
:let +" = expand("%")
|2,0,1621158524,,"let +\" = expand(\"%\")"
:color default
|2,0,1621149882,,"color default"
:!uname
|2,0,1621148729,,"!uname"

# Search String History (newest to oldest):
? \<world\>
|2,1,1621163878,,"\\<world\\>"
? \<ans\>
|2,1,1621163878,,"\\<ans\\>"
??buffer
|2,1,1621163878,63,"buffer"
??help tabf
|2,1,1621163878,63,"help tabf"
? \<k\>
|2,1,1621163878,,"\\<k\\>"
? \<session-file\>
|2,1,1621163878,,"\\<session-file\\>"
? \<viminfo-file\>
|2,1,1621163878,,"\\<viminfo-file\\>"
??buff
|2,1,1621163878,63,"buff"
??bufnew
|2,1,1621163878,63,"bufnew"
? \<-rv\>
|2,1,1621163878,,"\\<-rv\\>"
??rv
|2,1,1621163878,63,"rv"
??-rv
|2,1,1621163878,63,"-rv"
? eqns
|2,1,1621163878,,"eqns"
??:rv
|2,1,1621163878,63,":rv"
??registers
|2,1,1621163878,63,"registers"
??jkkkkkkkkkk
|2,1,1621163878,63,"jkkkkkkkkkk"
? \<:autocmd\>
|2,1,1621163878,,"\\<:autocmd\\>"
??wv
|2,1,1621163878,63,"wv"
? @$
|2,1,1621163878,,"@$"
?/*
|2,1,1621163878,47,"*"
? .
|2,1,1621163878,,"."
? \<.\>
|2,1,1621163878,,"\\<.\\>"
??tab
|2,1,1621163878,63,"tab"
??tabs
|2,1,1621163878,63,"tabs"
? \<i\>
|2,1,1621163878,,"\\<i\\>"
? \<parse\>
|2,1,1621163878,,"\\<parse\\>"
? \<testRabinKarpPatternSearch\>
|2,1,1621163878,,"\\<testRabinKarpPatternSearch\\>"
? data
|2,1,1621163878,,"data"
??>
|2,1,1621163878,63,">"
??Aho-Corasick
|2,1,1621163878,63,"Aho-Corasick"
??exit
|2,1,1621163878,63,"exit"
??cp
|2,1,1621163878,63,"cp"
? \<pow\>
|2,1,1621163878,,"\\<pow\\>"
? \<I\>
|2,1,1621163878,,"\\<I\\>"
? \<f\>
|2,1,1621163878,,"\\<f\\>"
? \<cp\>
|2,1,1621163878,,"\\<cp\\>"
? 1
|2,1,1621163878,,"1"
??aho
|2,1,1621163878,63,"aho"
? queue
|2,1,1621163878,,"queue"
? \<nsol\>
|2,1,1621163878,,"\\<nsol\\>"
??dynamic
|2,1,1621163878,63,"dynamic"
??return
|2,1,1621163878,63,"return"
??keyword
|2,1,1621163878,63,"keyword"
??keywords
|2,1,1621163878,63,"keywords"
??unsigned
|2,1,1621163878,63,"unsigned"
?/++
|2,1,1621163878,47,"++"
??i++
|2,1,1621163878,63,"i++"
??while
|2,1,1621163878,63,"while"
??for
|2,1,1621163878,63,"for"
??count
|2,1,1621163878,63,"count"
? Prims
|2,1,1621163878,,"Prims"
? prims
|2,1,1621163878,,"prims"
? \<mergeSort\>
|2,1,1621163878,,"\\<mergeSort\\>"
? \<quickSort\>
|2,1,1621163878,,"\\<quickSort\\>"
? \<n\>
|2,1,1621163878,,"\\<n\\>"
? i
|2,1,1621163878,,"i"
? \<countP\>
|2,1,1621163878,,"\\<countP\\>"
? j
|2,1,1621163878,,"j"
? \<count\>
|2,1,1621163878,,"\\<count\\>"
? \<find\>
|2,1,1621163878,,"\\<find\\>"
? \<array\>
|2,1,1621163878,,"\\<array\\>"
??t
|2,1,1621163878,63,"t"
? \<extractMin\>
|2,1,1621163878,,"\\<extractMin\\>"
??emplace
|2,1,1621163878,63,"emplace"
? \.\/a\.out
|2,1,1621163878,,"\\.\\/a\\.out"
? \<ull\>
|2,1,1621163878,,"\\<ull\\>"
? makepair
|2,1,1621163878,,"makepair"
? \<include\>
|2,1,1621163878,,"\\<include\\>"
??print
|2,1,1621163878,63,"print"
? \<convert\>
|2,1,1621163878,,"\\<convert\\>"
? convert
|2,1,1621163878,,"convert"
? â€™
|2,1,1621163878,,"â€™"
? â€˜
|2,1,1621163878,,"â€˜"
? \â€˜
|2,1,1621163878,,"\\â€˜"
? \'
|2,1,1621163878,,"\\'"
? '
|2,1,1621163878,,"'"
? small
|2,1,1621163878,,"small"
? big
|2,1,1621163878,,"big"
? ,
|2,1,1621163878,,","
? \<disp\>
|2,1,1621163878,,"\\<disp\\>"
? \<c\>
|2,1,1621163878,,"\\<c\\>"
? \<solve\>
|2,1,1621163878,,"\\<solve\\>"
? .\/a.out
|2,1,1621163878,,".\\/a.out"
? 2
|2,1,1621163878,,"2"
??cout
|2,1,1621163878,63,"cout"
??origin
|2,1,1621163878,63,"origin"
? void
|2,1,1621163878,,"void"
? &str
|2,1,1621163878,,"&str"
??&str
|2,1,1621163878,63,"&str"
? str\[i\]
|2,1,1621163878,,"str\\[i\\]"
? str[i]
|2,1,1621163878,,"str[i]"
? \<lower\>
|2,1,1621163878,,"\\<lower\\>"
? char * str
|2,1,1621163878,,"char * str"
? \<eval\>
|2,1,1621163878,,"\\<eval\\>"
??eval
|2,1,1621163878,63,"eval"
??min
|2,1,1621163878,63,"min"
??comb
|2,1,1621163878,63,"comb"
??modInverse
|2,1,1621163878,63,"modInverse"
? M
|2,1,1621163878,,"M"
? _3
|2,1,1621163878,,"_3"
? 3
|2,1,1621163878,,"3"
??C
|2,1,1621163878,63,"C"
?  
|2,1,1621163878,," "
? \<power\>
|2,1,1621163878,,"\\<power\\>"
? );
|2,1,1621163878,,");"
? \<comb\>
|2,1,1621163878,,"\\<comb\\>"
? ull
|2,1,1621163878,,"ull"
? >>
|2,1,1621163878,,">>"
? [nx][ny]
|2,1,1621163878,,"[nx][ny]"
??open
|2,1,1621163878,63,"open"
??auto
|2,1,1621163878,63,"auto"
??cout 
|2,1,1621163878,63,"cout "
??long long
|2,1,1621163878,63,"long long"
? long long
|2,1,1621163878,,"long long"
??who
|2,1,1621163878,63,"who"
??wh
|2,1,1621163878,63,"wh"
??ipair
|2,1,1621163878,63,"ipair"
??list
|2,1,1621163878,63,"list"
??\a
|2,1,1621163878,63,"\\a"
??solve
|2,1,1621163878,63,"solve"
? a
|2,1,1621163878,,"a"
??let length
|2,1,1621163878,63,"let length"
??&lt
|2,1,1621163878,63,"&lt"
??string constant
|2,1,1621163878,63,"string constant"
??input
|2,1,1621163878,63,"input"
??game
|2,1,1621163878,63,"game"
??m
|2,1,1621163878,63,"m"
??insert
|2,1,1621163878,63,"insert"
??bfs
|2,1,1621163878,63,"bfs"
??find
|2,1,1621163878,63,"find"
??right
|2,1,1621163878,63,"right"
? \<next\>
|2,1,1621163878,,"\\<next\\>"
??disp
|2,1,1621163878,63,"disp"
??inNode
|2,1,1621163878,63,"inNode"
??parent
|2,1,1621163878,63,"parent"
??dfs
|2,1,1621163878,63,"dfs"
??q.end()
|2,1,1621163878,63,"q.end()"
? \<bfs\>
|2,1,1621163878,,"\\<bfs\\>"
? 0
|2,1,1621163878,,"0"
??store
|2,1,1621163878,63,"store"
??revers
|2,1,1621163878,63,"revers"
??top
|2,1,1621163878,63,"top"
? \<inNode\>
|2,1,1621163878,,"\\<inNode\\>"
??Node
|2,1,1621163878,63,"Node"
??Parser
|2,1,1621163878,63,"Parser"
? var
|2,1,1621163878,,"var"
? \<comp\>
|2,1,1621163878,,"\\<comp\\>"
??hou
|2,1,1621163878,63,"hou"
??ans
|2,1,1621163878,63,"ans"
??comp
|2,1,1621163878,63,"comp"
?/string
|2,1,1621163878,47,"string"
? string
|2,1,1621163878,,"string"
? \<iostream\>
|2,1,1621163878,,"\\<iostream\\>"
??checkSolved
|2,1,1621163878,63,"checkSolved"
??reset
|2,1,1621163878,63,"reset"
??clear
|2,1,1621163878,63,"clear"
??clear()
|2,1,1621163878,63,"clear()"
??getState
|2,1,1621163878,63,"getState"
??setPos
|2,1,1621163878,63,"setPos"
??get
|2,1,1621163878,63,"get"
??fill
|2,1,1621163878,63,"fill"
? \<changePos\>
|2,1,1621163878,,"\\<changePos\\>"
??changePos
|2,1,1621163878,63,"changePos"
? \<setPos\>
|2,1,1621163878,,"\\<setPos\\>"
??draw()
|2,1,1621163878,63,"draw()"
?/setState
|2,1,1621163878,47,"setState"
??initArray
|2,1,1621163878,63,"initArray"
??state
|2,1,1621163878,63,"state"
??100
|2,1,1621163878,63,"100"
??10
|2,1,1621163878,63,"10"
??static
|2,1,1621163878,63,"static"
? circle
|2,1,1621163878,,"circle"
? \<CodeWriter\>
|2,1,1621163878,,"\\<CodeWriter\\>"
? \<fromCmd\>
|2,1,1621163878,,"\\<fromCmd\\>"
??.pop()
|2,1,1621163878,63,".pop()"
??IF_FALSE
|2,1,1621163878,63,"IF_FALSE"
??@Main.fibonacci$IF_F
|2,1,1621163878,63,"@Main.fibonacci$IF_F"
??@Main.fibonacci$IF
|2,1,1621163878,63,"@Main.fibonacci$IF"
??Main.fibonacci
|2,1,1621163878,63,"Main.fibonacci"
??4
|2,1,1621163878,63,"4"
? \<Sys\>
|2,1,1621163878,,"\\<Sys\\>"
? \<sys\>
|2,1,1621163878,,"\\<sys\\>"
? \<init\>
|2,1,1621163878,,"\\<init\\>"
??sys.init
|2,1,1621163878,63,"sys.init"
??@sysinit
|2,1,1621163878,63,"@sysinit"
?/sys.init$ret
|2,1,1621163878,47,"sys.init$ret"
? \<writeBootStrap\>
|2,1,1621163878,,"\\<writeBootStrap\\>"
? \<convertCall\>
|2,1,1621163878,,"\\<convertCall\\>"
??convertCall
|2,1,1621163878,63,"convertCall"
?//
|2,1,1621163878,47,"/"
??pop
|2,1,1621163878,63,"pop"
??label
|2,1,1621163878,63,"label"
??0;JMP
|2,1,1621163878,63,"0;JMP"
?/function sys
|2,1,1621163878,47,"function sys"
??goto while
|2,1,1621163878,63,"goto while"
??function Sys.init 0
|2,1,1621163878,63,"function Sys.init 0"
??sys
|2,1,1621163878,63,"sys"
??Sys.init
|2,1,1621163878,63,"Sys.init"
??argument
|2,1,1621163878,63,"argument"
??/#
|2,1,1621163878,63,"/#"
??push n
|2,1,1621163878,63,"push n"
??}
|2,1,1621163878,63,"}"
??{
|2,1,1621163878,63,"{"
??Sys
|2,1,1621163878,63,"Sys"
??n_var
|2,1,1621163878,63,"n_var"
??Branch
|2,1,1621163878,63,"Branch"
??convertReturn
|2,1,1621163878,63,"convertReturn"
??Return
|2,1,1621163878,63,"Return"
? \<return_address\>
|2,1,1621163878,,"\\<return_address\\>"
??ret
|2,1,1621163878,63,"ret"
??rect
|2,1,1621163878,63,"rect"
? \<convertGoto\>
|2,1,1621163878,,"\\<convertGoto\\>"
? \<convertIf\>
|2,1,1621163878,,"\\<convertIf\\>"
? \<convertLabel\>
|2,1,1621163878,,"\\<convertLabel\\>"
??convertLabel
|2,1,1621163878,63,"convertLabel"
? \<writeGoto\>
|2,1,1621163878,,"\\<writeGoto\\>"
??this.func
|2,1,1621163878,63,"this.func"
??temp
|2,1,1621163878,63,"temp"
??Arith
|2,1,1621163878,63,"Arith"
??function
|2,1,1621163878,63,"function"
? \<BasicLoop\>
|2,1,1621163878,,"\\<BasicLoop\\>"
??call
|2,1,1621163878,63,"call"
??add12
|2,1,1621163878,63,"add12"
??Ad12
|2,1,1621163878,63,"Ad12"
??foldmethod
|2,1,1621163878,63,"foldmethod"
??write
|2,1,1621163878,63,"write"
??writePush
|2,1,1621163878,63,"writePush"
??foo
|2,1,1621163878,63,"foo"
??classmethod
|2,1,1621163878,63,"classmethod"
??po
|2,1,1621163878,63,"po"
? \<commands\>
|2,1,1621163878,,"\\<commands\\>"
? \<full_file_path\>
|2,1,1621163878,,"\\<full_file_path\\>"
??tst
|2,1,1621163878,63,"tst"
??'r'
|2,1,1621163878,63,"'r'"
? \<cmd2type\>
|2,1,1621163878,,"\\<cmd2type\\>"
??self.full_directory
|2,1,1621163878,63,"self.full_directory"
??full_out_filename
|2,1,1621163878,63,"full_out_filename"
??path_is_file
|2,1,1621163878,63,"path_is_file"
??full_path
|2,1,1621163878,63,"full_path"
??full_directory_path
|2,1,1621163878,63,"full_directory_path"
??rsplit
|2,1,1621163878,63,"rsplit"
??full_directory_
|2,1,1621163878,63,"full_directory_"
??directory
|2,1,1621163878,63,"directory"
??Parse
|2,1,1621163878,63,"Parse"
??current_filename
|2,1,1621163878,63,"current_filename"
??cmd2type
|2,1,1621163878,63,"cmd2type"
??current_file_full
|2,1,1621163878,63,"current_file_full"
??self.parser
|2,1,1621163878,63,"self.parser"
? \<line\>
|2,1,1621163878,,"\\<line\\>"
? \<CommandPreprocessor\>
|2,1,1621163878,,"\\<CommandPreprocessor\\>"
??commands
|2,1,1621163878,63,"commands"
??parser\.
|2,1,1621163878,63,"parser\\."
??parser.
|2,1,1621163878,63,"parser."
??os
|2,1,1621163878,63,"os"
??input_file_name
|2,1,1621163878,63,"input_file_name"
??main
|2,1,1621163878,63,"main"
??push
|2,1,1621163878,63,"push"
?/temp
|2,1,1621163878,47,"temp"
??PopCon
|2,1,1621163878,63,"PopCon"
??Aritm
|2,1,1621163878,63,"Aritm"
??else if
|2,1,1621163878,63,"else if"
? \<write\>
|2,1,1621163878,,"\\<write\\>"
??__init__
|2,1,1621163878,63,"__init__"
? sp
|2,1,1621163878,,"sp"
??Command
|2,1,1621163878,63,"Command"
??getHash
|2,1,1621163878,63,"getHash"
? \<getPow\>
|2,1,1621163878,,"\\<getPow\\>"
??getPow
|2,1,1621163878,63,"getPow"
??x_l
|2,1,1621163878,63,"x_l"
??hash
|2,1,1621163878,63,"hash"
??Handle
|2,1,1621163878,63,"Handle"
??hack
|2,1,1621163878,63,"hack"
? \<file_name\>
|2,1,1621163878,,"\\<file_name\\>"
??[1]
|2,1,1621163878,63,"[1]"
??"M"
|2,1,1621163878,63,"\"M\""
? \<ConvertSymbols\>
|2,1,1621163878,,"\\<ConvertSymbols\\>"
??file_list
|2,1,1621163878,63,"file_list"
??ez-life
|2,1,1621163878,63,"ez-life"
??ez_l
|2,1,1621163878,63,"ez_l"
??precompute
|2,1,1621163878,63,"precompute"
? \<precompute\>
|2,1,1621163878,,"\\<precompute\\>"
??hash(
|2,1,1621163878,63,"hash("
??class Hash
|2,1,1621163878,63,"class Hash"
? \<HashTable\>
|2,1,1621163878,,"\\<HashTable\\>"
? \<hashtable\>
|2,1,1621163878,,"\\<hashtable\\>"
?/hash
|2,1,1621163878,47,"hash"
??s
|2,1,1621163878,63,"s"
??>=
|2,1,1621163878,63,">="
??<
|2,1,1621163878,63,"<"
? Hash
|2,1,1621163878,,"Hash"
??jtl
|2,1,1621163878,63,"jtl"
??loadD
|2,1,1621163878,63,"loadD"
??loadA
|2,1,1621163878,63,"loadA"
? \<PC\>
|2,1,1621163878,,"\\<PC\\>"
? \<pc\>
|2,1,1621163878,,"\\<pc\\>"
??extract
|2,1,1621163878,63,"extract"
??max
|2,1,1621163878,63,"max"
??de
|2,1,1621163878,63,"de"
??deb
|2,1,1621163878,63,"deb"
??debugg
|2,1,1621163878,63,"debugg"
? \<changePriority\>
|2,1,1621163878,,"\\<changePriority\\>"
? \<ChangePriority\>
|2,1,1621163878,,"\\<ChangePriority\\>"
? visited
|2,1,1621163878,,"visited"
??visited
|2,1,1621163878,63,"visited"
?/main
|2,1,1621163878,47,"main"
??ChangePr
|2,1,1621163878,63,"ChangePr"
??debugger
|2,1,1621163878,63,"debugger"
??siftup
|2,1,1621163878,63,"siftup"
??siftDown
|2,1,1621163878,63,"siftDown"
??sifDown
|2,1,1621163878,63,"sifDown"
??heap
|2,1,1621163878,63,"heap"
??heapn
|2,1,1621163878,63,"heapn"
??size
|2,1,1621163878,63,"size"
? SortedHeap
|2,1,1621163878,,"SortedHeap"
? size
|2,1,1621163878,,"size"
? \<verbose\>
|2,1,1621163878,,"\\<verbose\\>"
? \<getInput\>
|2,1,1621163878,,"\\<getInput\\>"
? \<heap\>
|2,1,1621163878,,"\\<heap\\>"
? \<Heap\>
|2,1,1621163878,,"\\<Heap\\>"
??size_t
|2,1,1621163878,63,"size_t"
? a.out: main.cpp
|2,1,1621163878,,"a.out: main.cpp"
? \<ng\>
|2,1,1621163878,,"\\<ng\\>"
??Add16
|2,1,1621163878,63,"Add16"
? zx
|2,1,1621163878,,"zx"
? x
|2,1,1621163878,,"x"
? And
|2,1,1621163878,,"And"
? sel
|2,1,1621163878,,"sel"
? s
|2,1,1621163878,,"s"
??export
|2,1,1621163878,63,"export"
? bfs
|2,1,1621163878,,"bfs"
??D2
|2,1,1621163878,63,"D2"
? \\
|2,1,1621163878,,"\\\\"
? \<clustering\>
|2,1,1621163878,,"\\<clustering\\>"
??std::cout
|2,1,1621163878,63,"std::cout"
??data
|2,1,1621163878,63,"data"
??swap
|2,1,1621163878,63,"swap"
??parti
|2,1,1621163878,63,"parti"
??counter
|2,1,1621163878,63,"counter"
??9
|2,1,1621163878,63,"9"
??loop
|2,1,1621163878,63,"loop"
??sort
|2,1,1621163878,63,"sort"
??yo
|2,1,1621163878,63,"yo"
??partition
|2,1,1621163878,63,"partition"
??std::cout 
|2,1,1621163878,63,"std::cout "
? \<swap\>
|2,1,1621163878,,"\\<swap\\>"
??assert
|2,1,1621163878,63,"assert"
? \<partition\>
|2,1,1621163878,,"\\<partition\\>"
??key
|2,1,1621163878,63,"key"
? \<sort\>
|2,1,1621163878,,"\\<sort\\>"
??const
|2,1,1621163878,63,"const"
? \<s\>
|2,1,1621163878,,"\\<s\\>"
??Enter
|2,1,1621163878,63,"Enter"
? \<tail\>
|2,1,1621163878,,"\\<tail\\>"
? \<back\>
|2,1,1621163878,,"\\<back\\>"
??new
|2,1,1621163878,63,"new"
??int
|2,1,1621163878,63,"int"
??back
|2,1,1621163878,63,"back"
? ;
|2,1,1621163878,,";"
? \<:next\>
|2,1,1621163878,,"\\<:next\\>"
? \<:Next\>
|2,1,1621163878,,"\\<:Next\\>"
?/incremen
|2,1,1621163878,47,"incremen"
?/h
|2,1,1621163878,47,"h"
??continue
|2,1,1621163878,63,"continue"
??std::pair
|2,1,1621163878,63,"std::pair"
? std::pair<long long, int>
|2,1,1621163878,,"std::pair<long long, int>"
? \<filter\>
|2,1,1621163878,,"\\<filter\\>"
??filter
|2,1,1621163878,63,"filter"
??push_back
|2,1,1621163878,63,"push_back"
??explore
|2,1,1621163878,63,"explore"
? vector<list
|2,1,1621163878,,"vector<list"
??vector<list
|2,1,1621163878,63,"vector<list"
? \<explore\>
|2,1,1621163878,,"\\<explore\\>"
??DFS
|2,1,1621163878,63,"DFS"
??delete this
|2,1,1621163878,63,"delete this"
??delete(this)
|2,1,1621163878,63,"delete(this)"
? \<split\>
|2,1,1621163878,,"\\<split\\>"
??split
|2,1,1621163878,63,"split"
??delete
|2,1,1621163878,63,"delete"
? \<SplayTree\>
|2,1,1621163878,,"\\<SplayTree\\>"
??fromString
|2,1,1621163878,63,"fromString"
??T
|2,1,1621163878,63,"T"
??orderStats
|2,1,1621163878,63,"orderStats"
??fn
|2,1,1621163878,63,"fn"
??splay
|2,1,1621163878,63,"splay"
??merge
|2,1,1621163878,63,"merge"
??end
|2,1,1621163878,63,"end"
??process
|2,1,1621163878,63,"process"
??merged
|2,1,1621163878,63,"merged"
??inOrder
|2,1,1621163878,63,"inOrder"
??SplayTree
|2,1,1621163878,63,"SplayTree"
??left->in
|2,1,1621163878,63,"left->in"
??left
|2,1,1621163878,63,"left"
? \<orderStats\>
|2,1,1621163878,,"\\<orderStats\\>"
??split19k
|2,1,1621163878,63,"split19k"
? \<cassert\>
|2,1,1621163878,,"\\<cassert\\>"
??fromSt
|2,1,1621163878,63,"fromSt"
? \<debugger\>
|2,1,1621163878,,"\\<debugger\\>"
??size()
|2,1,1621163878,63,"size()"
? \<fromString\>
|2,1,1621163878,,"\\<fromString\\>"
? v
|2,1,1621163878,,"v"
? \<new\>
|2,1,1621163878,,"\\<new\\>"
? R
|2,1,1621163878,,"R"
?/root
|2,1,1621163878,47,"root"
? \<Makes\>
|2,1,1621163878,,"\\<Makes\\>"
??printf
|2,1,1621163878,63,"printf"
? >
|2,1,1621163878,,">"
??Vertex
|2,1,1621163878,63,"Vertex"
? \<update\>
|2,1,1621163878,,"\\<update\\>"
? \<small_rotation\>
|2,1,1621163878,,"\\<small_rotation\\>"
??root
|2,1,1621163878,63,"root"
? MAX
|2,1,1621163878,,"MAX"
??ament_export_dependencies(rosidl_default_runtime)
|2,1,1621163878,63,"ament_export_dependencies(rosidl_default_runtime)"
??rosidl_generate_interfaces(${PROJECT_NAME}
|2,1,1621163878,63,"rosidl_generate_interfaces(${PROJECT_NAME}"
??"msg/AddressBook.msg
|2,1,1621163878,63,"\"msg/AddressBook.msg"
??set(msg_files
|2,1,1621163878,63,"set(msg_files"
??find_package(rosidl_default_generators R
|2,1,1621163878,63,"find_package(rosidl_default_generators R"
??shiftwidth
|2,1,1621163878,63,"shiftwidth"
??plugged
|2,1,1621163878,63,"plugged"
??family
|2,1,1621163878,63,"family"
? \<flags\>
|2,1,1621163878,,"\\<flags\\>"
??set
|2,1,1621163878,63,"set"
??setting
|2,1,1621163878,63,"setting"
??def Settings
|2,1,1621163878,63,"def Settings"
? \<add_newdoc_ufunc\>
|2,1,1621163878,,"\\<add_newdoc_ufunc\\>"
??std_
|2,1,1621163878,63,"std_"
??std_msgs
|2,1,1621163878,63,"std_msgs"
??std::m
|2,1,1621163878,63,"std::m"
??kkkk
|2,1,1621163878,63,"kkkk"
??tur
|2,1,1621163878,63,"tur"
??String
|2,1,1621163878,63,"String"
??private
|2,1,1621163878,63,"private"
??subscription
|2,1,1621163878,63,"subscription"
??turt
|2,1,1621163878,63,"turt"
??find_package
|2,1,1621163878,63,"find_package"
??timer_call
|2,1,1621163878,63,"timer_call"
??build_depend
|2,1,1621163878,63,"build_depend"
??install
|2,1,1621163878,63,"install"
??request
|2,1,1621163878,63,"request"
??add_executable
|2,1,1621163878,63,"add_executable"
??add_execu
|2,1,1621163878,63,"add_execu"
??Add
|2,1,1621163878,63,"Add"
??AddTwoInts
|2,1,1621163878,63,"AddTwoInts"
??memory
|2,1,1621163878,63,"memory"
??add_exe
|2,1,1621163878,63,"add_exe"
? \<w\>
|2,1,1621163878,,"\\<w\\>"
??plugin
|2,1,1621163878,63,"plugin"
??filetype
|2,1,1621163878,63,"filetype"
? hey
|2,1,1621163878,,"hey"
? \<ab\>
|2,1,1621163878,,"\\<ab\\>"
? \<cd\>
|2,1,1621163878,,"\\<cd\\>"
? \<b\>
|2,1,1621163878,,"\\<b\\>"
?/hello
|2,1,1621163878,47,"hello"
? hello
|2,1,1621163878,,"hello"
? \<main\>
|2,1,1621163878,,"\\<main\\>"
? \<j\>
|2,1,1621163878,,"\\<j\\>"

# Expression History (newest to oldest):
=p
|2,2,1621163878,,"p"
=10 * 20 + 5
|2,2,1621163878,,"10 * 20 + 5"
=100 * 50 + 20
|2,2,1621163878,,"100 * 50 + 20"
=100 * 50 + 10
|2,2,1621163878,,"100 * 50 + 10"

# Input Line History (newest to oldest):
@list
|2,3,1621163878,,"list"
@dict
|2,3,1621163878,,"dict"
@[{y(es)},n(o),a(ll),q(uit)] y
|2,3,1621163878,,"[{y(es)},n(o),a(ll),q(uit)] y"
@p>
|2,3,1621163878,,"p>"
@member_of_group>
|2,3,1621163878,,"member_of_group>"
@exec_depend>
|2,3,1621163878,,"exec_depend>"
@buildtool_depend>
|2,3,1621163878,,"buildtool_depend>"
@depend>
|2,3,1621163878,,"depend>"
@exev_depend>
|2,3,1621163878,,"exev_depend>"
@build_depend>
|2,3,1621163878,,"build_depend>"
@depend
|2,3,1621163878,,"depend"
@p class="hello world">
|2,3,1621163878,,"p class=\"hello world\">"
@print
|2,3,1621163878,,"print"
@p class = root>
|2,3,1621163878,,"p class = root>"
@printf
|2,3,1621163878,,"printf"

# Debug Line History (newest to oldest):

# Registers:
"0	CHAR	0
	main.py
|3,0,0,0,1,0,1621163883,"main.py"
"1	LINE	0
	# =====================================================
	#
	# File Name: main.py
	# Date of Creation: Sun 16 May 2021 10:43:58
	# Author: Josiah Tan
	# Description:
	#
	# =====================================================
	# =====================================================
	
	
	
	if __name__ == '__main__':
	    a = 10;
	    b = 5;
	
	    print(f"a = {a}");
	    print(f"b = {b}");
	
	    a, b = b, a;
	
	    print(f"a = {a}");
	    print(f"b = {b}");
|3,0,1,1,23,0,1621163882,"# =====================================================","#","# File Name: main.py","# Date of Creation: Sun 16 May 2021 10:43:58","# Author: Josiah Tan","# Description:","#","# =====================================================","# =====================================================","","","","if __name__ == '__main__':","    a = 10;","    b = 5;","","    print(f\"a = {a}\");","    print(f\"b = {b}\");","","    a, b = b, a;","",>26
|<"    print(f\"a = {a}\");","    print(f\"b = {b}\");"
"2	LINE	0
	:wv! ~/.vim/info/.pyinfo.vim
|3,0,2,1,1,0,1621147161,":wv! ~/.vim/info/.pyinfo.vim"
"3	LINE	0
	
|3,0,3,1,1,0,1621081530,""
"4	LINE	0
	print(f"hello = {hello}");
|3,0,4,1,1,0,1621081526,"print(f\"hello = {hello}\");"
"5	LINE	0
	print(f"this  = {this }");
|3,0,5,1,1,0,1621081525,"print(f\"this  = {this }\");"
"6	LINE	0
	print(f"very = {very}");
|3,0,6,1,1,0,1621081524,"print(f\"very = {very}\");"
"7	LINE	0
	^d$aprint(f"€ýapa = {€ýapf)i"€ýaA;€ýa
|3,0,7,1,1,0,1621081522,"^d$aprint(f\"€ýapa = {€ýapf)i\"€ýaA;€ýa"
"8	LINE	0
	print(f"hello world = {hello world}");
	print(f"hello world = {hello world}");
|3,0,8,1,2,0,1621081433,"print(f\"hello world = {hello world}\");","print(f\"hello world = {hello world}\");"
"9	LINE	0
	^d$aprint(f"€ýapa = {€ýapf)i"€ýaA;€ýaj
|3,0,9,1,1,0,1621081416,"^d$aprint(f\"€ýapa = {€ýapf)i\"€ýaA;€ýaj"
"a	CHAR	0
	i €ýak
|3,0,10,0,1,0,1612342066,"i €ýak"
"b	CHAR	0
	oif __name__ == '__main__':
|3,0,11,0,1,0,1621077500,"oif __name__ == '__main__':"
"c	LINE	0
	#include<stdio.h>
	#include<stdlib.h>
	#include<limits.h>
	
	
	int main(void){
		return 0;
	}
	
	
|3,0,12,1,10,0,1620963634,"#include<stdio.h>","#include<stdlib.h>","#include<limits.h>","","","int main(void){","	return 0;","}","",""
"d	CHAR	0
	@b€ýa@t
|3,0,13,0,1,0,1621078122,"@b€ýa@t"
"e	CHAR	0
	$i&&€ýa
|3,0,14,0,1,0,1614340553,"$i&&€ýa"
"f	CHAR	0
	ggO/*File AneName: €ýa:put = let @" = ep€kbxpand("%")poDate of Creation: €ýa:put = explore("strftime("€kb'%c')kJoAuthor: Josiah Tan€kb€kb€kb*/€ýa
|3,0,15,0,1,0,1620986375,"ggO/*File AneName: €ýa:put = let @\" = ep€kbxpand(\"%\")poDate of Creation: €ýa:put = explore(\"strftime(\"€kb'%c')kJoAuthor: Josiah Tan€kb€kb€kb*/€ýa"
"g	CHAR	0
	i#ifndef €ýa:let @" ex€kb€kb=expand("%")pF.r_viWUviwyo#define €ýapo€ýaG10o€ýao#endif€ýa9k
|3,0,16,0,1,0,1621079858,"i#ifndef €ýa:let @\" ex€kb€kb=expand(\"%\")pF.r_viWUviwyo#define €ýapo€ýaG10o€ýao#endif€ýa9k"
"h	LINE	0
	385
<ggO# ++€kb€kb=======================================================€kb€kb# File€ýaO€ýajki#€ýajA Name: €ýa:let %€kb@" = expand("%")po#d€kb Date of Creation: €ýa:put = defstrtimefstrtftimstrftime("€kb'%c')kJo# Author: Josiah Tan# Description:3€kb€kb## =====================================================# =====================================================€ýa
|3,0,17,1,1,0,1621079975,"ggO# ++€kb€kb=======================================================€kb€kb# File€ýaO€ýajki#€ýajA Name: €ýa:let %€kb@\" = expand(\"%\")po#d€kb Date of Creation: €ýa:put = defstrtimefstrtftimstrftime(\"€kb'%c')kJo# Author: Josiah Tan# Description:3€kb€kb## =====================================================# =====================================================€ýa"
"i	CHAR	0
	Sfor (int i=0;i<n;i++){€ýaO€ýa
|3,0,18,0,1,0,1620986139,"Sfor (int i=0;i<n;i++){€ýaO€ýa"
"j	CHAR	0
	Sfor (int j=0;j<m;j++){€ýaO€ýa
|3,0,19,0,1,0,1620986173,"Sfor (int j=0;j<m;j++){€ýaO€ýa"
"l	CHAR	0
	f,i: Ar€kb€ýal
|3,0,21,0,1,0,1613564205,"f,i: Ar€kb€ýal"
"m	CHAR	0
	:tabnew Mae€kbkei€kbfiletabnew Makefile:%diall: ./a.outcat 1.in | ./a.ou€kb€kbout./a.out: main.cpp€kb€kbg++ mainc€kb.cp€kb€ýa
|3,0,22,0,1,0,1620986862,":tabnew Mae€kbkei€kbfiletabnew Makefile:%diall: ./a.outcat 1.in | ./a.ou€kb€kbout./a.out: main.cpp€kb€kbg++ mainc€kb.cp€kb€ýa"
"n	LINE	0
	Josiah Tan
|3,0,23,1,1,0,1620984417,"Josiah Tan"
"p	LINE	0
	^d$aprint(f"€ýapa = {€ýapf)i"€ýaA;€ýa
|3,0,25,1,1,0,1621081520,"^d$aprint(f\"€ýapa = {€ýapf)i\"€ýaA;€ýa"
"q	CHAR	0
	ihello wol€kbrld€ýa
|3,0,26,0,1,0,1621046993,"ihello wol€kbrld€ýa"
"r	CHAR	0
	:!python3 %
|3,0,27,0,1,0,1621074930,":!python3 %"
"s	CHAR	0
	f,geysiw"f,
|3,0,28,0,1,0,1613478510,"f,geysiw\"f,"
"t	LINE	0
	385
<ggO# ++€kb€kb=======================================================€kb€kb# File€ýaO€ýajki#€ýajA Name: €ýa:let %€kb@" = expand("%")po#d€kb Date of Creation: €ýa:put = defstrtimefstrtftimstrftime("€kb'%c')kJo# Author: Josiah Tan# Description:3€kb€kb## =====================================================# =====================================================€ýa
|3,0,29,1,1,0,1621072651,"ggO# ++€kb€kb=======================================================€kb€kb# File€ýaO€ýajki#€ýajA Name: €ýa:let %€kb@\" = expand(\"%\")po#d€kb Date of Creation: €ýa:put = defstrtimefstrtftimstrftime(\"€kb'%c')kJo# Author: Josiah Tan# Description:3€kb€kb## =====================================================# =====================================================€ýa"
"u	CHAR	0
	^veUk
|3,0,30,0,1,0,1613212860,"^veUk"
"v@	LINE	0
	:wv! ~/.vim/info/.pyinfo.vim
|3,2,31,1,1,0,1621147158,":wv! ~/.vim/info/.pyinfo.vim"
"w	CHAR	0
	thii€kbti€kb€kbthis is a program that copies registtakprints what is in register w t€kb€kb€kbq twice€ýa@w@q@q
|3,0,32,0,1,0,1620987224,"thii€kbti€kb€kbthis is a program that copies registtakprints what is in register w t€kb€kb€kbq twice€ýa@w@q@q"
""-	CHAR	0
	,
|3,1,36,0,1,0,1621163929,","

# global variables:

# File marks:
'P  2  20  ~/Desktop/josiah_folder/nand2tetris/projects/07/StackArithmetic/SimpleAdd/SimpleAdd.asm
|4,80,2,20,1613618169,"~/Desktop/josiah_folder/nand2tetris/projects/07/StackArithmetic/SimpleAdd/SimpleAdd.asm"
'V  43  0  ~/.vimrc
|4,86,43,0,1612532244,"~/.vimrc"
'0  14  9  ~/Desktop/josiah_folder/vim/vimvscode/main.py
|4,48,14,9,1621163940,"~/Desktop/josiah_folder/vim/vimvscode/main.py"
'1  9  5  ~/Desktop/josiah_folder/vim/vimvscode/main.cpp
|4,49,9,5,1621163530,"~/Desktop/josiah_folder/vim/vimvscode/main.cpp"
'2  9  5  ~/Desktop/josiah_folder/vim/vimvscode/main.cpp
|4,50,9,5,1621163188,"~/Desktop/josiah_folder/vim/vimvscode/main.cpp"
'3  9  5  ~/Desktop/josiah_folder/vim/vimvscode/main.cpp
|4,51,9,5,1621163136,"~/Desktop/josiah_folder/vim/vimvscode/main.cpp"
'4  9  5  ~/Desktop/josiah_folder/vim/vimvscode/main.cpp
|4,52,9,5,1621163136,"~/Desktop/josiah_folder/vim/vimvscode/main.cpp"
'5  9  5  ~/Desktop/josiah_folder/vim/vimvscode/main.cpp
|4,53,9,5,1621163016,"~/Desktop/josiah_folder/vim/vimvscode/main.cpp"
'6  9  5  ~/Desktop/josiah_folder/vim/vimvscode/main.cpp
|4,54,9,5,1621163016,"~/Desktop/josiah_folder/vim/vimvscode/main.cpp"
'7  9  5  ~/Desktop/josiah_folder/vim/vimvscode/main.cpp
|4,55,9,5,1621163016,"~/Desktop/josiah_folder/vim/vimvscode/main.cpp"
'8  9  5  ~/Desktop/josiah_folder/vim/vimvscode/main.cpp
|4,56,9,5,1621163016,"~/Desktop/josiah_folder/vim/vimvscode/main.cpp"
'9  9  5  ~/Desktop/josiah_folder/vim/vimvscode/main.cpp
|4,57,9,5,1621162922,"~/Desktop/josiah_folder/vim/vimvscode/main.cpp"

# Jumplist (newest first):
-'  14  9  ~/Desktop/josiah_folder/vim/vimvscode/main.py
|4,39,14,9,1621163940,"~/Desktop/josiah_folder/vim/vimvscode/main.py"
-'  11  0  ~/Desktop/josiah_folder/vim/vimvscode/main.py
|4,39,11,0,1621163883,"~/Desktop/josiah_folder/vim/vimvscode/main.py"
-'  12  0  ~/Desktop/josiah_folder/vim/vimvscode/main.py
|4,39,12,0,1621163883,"~/Desktop/josiah_folder/vim/vimvscode/main.py"
-'  14  0  ~/Desktop/josiah_folder/vim/vimvscode/module.h
|4,39,14,0,1621163878,"~/Desktop/josiah_folder/vim/vimvscode/module.h"
-'  8  0  ~/Desktop/josiah_folder/vim/vimvscode/module.h
|4,39,8,0,1621163869,"~/Desktop/josiah_folder/vim/vimvscode/module.h"
-'  13  0  ~/Desktop/josiah_folder/vim/vimvscode/module.h
|4,39,13,0,1621163869,"~/Desktop/josiah_folder/vim/vimvscode/module.h"
-'  11  0  ~/Desktop/josiah_folder/vim/vimvscode/module.h
|4,39,11,0,1621163868,"~/Desktop/josiah_folder/vim/vimvscode/module.h"
-'  9  0  ~/Desktop/josiah_folder/vim/vimvscode/module.h
|4,39,9,0,1621163865,"~/Desktop/josiah_folder/vim/vimvscode/module.h"
-'  20  0  ~/Desktop/josiah_folder/vim/vimvscode/main.c
|4,39,20,0,1621163855,"~/Desktop/josiah_folder/vim/vimvscode/main.c"
-'  17  0  ~/Desktop/josiah_folder/vim/vimvscode/main.c
|4,39,17,0,1621163845,"~/Desktop/josiah_folder/vim/vimvscode/main.c"
-'  8  0  ~/Desktop/josiah_folder/vim/vimvscode/main.c
|4,39,8,0,1621163824,"~/Desktop/josiah_folder/vim/vimvscode/main.c"
-'  9  0  ~/Desktop/josiah_folder/vim/vimvscode/main.c
|4,39,9,0,1621163824,"~/Desktop/josiah_folder/vim/vimvscode/main.c"
-'  21  5  ~/Desktop/josiah_folder/vim/vimvscode/main.cpp
|4,39,21,5,1621163819,"~/Desktop/josiah_folder/vim/vimvscode/main.cpp"
-'  8  0  ~/Desktop/josiah_folder/vim/vimvscode/main.cpp
|4,39,8,0,1621163807,"~/Desktop/josiah_folder/vim/vimvscode/main.cpp"
-'  9  0  ~/Desktop/josiah_folder/vim/vimvscode/main.cpp
|4,39,9,0,1621163807,"~/Desktop/josiah_folder/vim/vimvscode/main.cpp"
-'  1  0  ~/.vim/.gitmodules
|4,39,1,0,1621162793,"~/.vim/.gitmodules"
-'  1  4  ~/.vim/.gitignore
|4,39,1,4,1621158883,"~/.vim/.gitignore"
-'  1  0  ~/Desktop/josiah_folder/vim/vimvscode/main.cpp
|4,39,1,0,1621147446,"~/Desktop/josiah_folder/vim/vimvscode/main.cpp"
-'  69  0  ~/.vim/vimrc
|4,39,69,0,1621147339,"~/.vim/vimrc"
-'  27  0  ~/Desktop/josiah_folder/vim/vimvscode/main.c
|4,39,27,0,1621147269,"~/Desktop/josiah_folder/vim/vimvscode/main.c"
-'  10  0  ~/Desktop/josiah_folder/vim/vimvscode/main.c
|4,39,10,0,1621147258,"~/Desktop/josiah_folder/vim/vimvscode/main.c"
-'  30  0  ~/Desktop/josiah_folder/vim/vimvscode/main.c
|4,39,30,0,1621147258,"~/Desktop/josiah_folder/vim/vimvscode/main.c"
-'  16  0  ~/Desktop/josiah_folder/vim/vimvscode/main.py
|4,39,16,0,1621147164,"~/Desktop/josiah_folder/vim/vimvscode/main.py"
-'  17  0  ~/Desktop/josiah_folder/vim/vimvscode/main.py
|4,39,17,0,1621147132,"~/Desktop/josiah_folder/vim/vimvscode/main.py"
-'  12  0  ~/Desktop/josiah_folder/vim/vimvscode/module.h
|4,39,12,0,1621147016,"~/Desktop/josiah_folder/vim/vimvscode/module.h"
-'  1  0  ~/Desktop/josiah_folder/vim/vimvscode/module.h
|4,39,1,0,1621146915,"~/Desktop/josiah_folder/vim/vimvscode/module.h"
-'  22  0  ~/Desktop/josiah_folder/vim/vimvscode/module.h
|4,39,22,0,1621146913,"~/Desktop/josiah_folder/vim/vimvscode/module.h"
-'  2  0  ~/Desktop/josiah_folder/vim/vimvscode/main.c
|4,39,2,0,1621146848,"~/Desktop/josiah_folder/vim/vimvscode/main.c"
-'  1  0  ~/Desktop/josiah_folder/vim/vimvscode/mian.c
|4,39,1,0,1621146831,"~/Desktop/josiah_folder/vim/vimvscode/mian.c"
-'  23  3  ~/Desktop/josiah_folder/vim/vimvscode/main.c
|4,39,23,3,1621146812,"~/Desktop/josiah_folder/vim/vimvscode/main.c"
-'  1  0  ~/Desktop/josiah_folder/vim/vimvscode/main.c
|4,39,1,0,1621146811,"~/Desktop/josiah_folder/vim/vimvscode/main.c"
-'  22  4  ~/Desktop/josiah_folder/vim/vimvscode/main.c
|4,39,22,4,1621146811,"~/Desktop/josiah_folder/vim/vimvscode/main.c"
-'  21  5  ~/Desktop/josiah_folder/vim/vimvscode/main.c
|4,39,21,5,1621146808,"~/Desktop/josiah_folder/vim/vimvscode/main.c"
-'  59  0  ~/.vim/vimrc
|4,39,59,0,1621146785,"~/.vim/vimrc"
-'  1  0  ~/.vim/vimrc
|4,39,1,0,1621146743,"~/.vim/vimrc"
-'  54  0  ~/Desktop/josiah_folder/py3/solve_sim/solve.py
|4,39,54,0,1621081543,"~/Desktop/josiah_folder/py3/solve_sim/solve.py"
-'  51  37  ~/Desktop/josiah_folder/py3/solve_sim/solve.py
|4,39,51,37,1621081430,"~/Desktop/josiah_folder/py3/solve_sim/solve.py"
-'  1  0  ~/Desktop/josiah_folder/py3/solve_sim/solve.py
|4,39,1,0,1621081352,"~/Desktop/josiah_folder/py3/solve_sim/solve.py"
-'  21  0  ~/Desktop/josiah_folder/py3/solve_sim/main.c
|4,39,21,0,1621081346,"~/Desktop/josiah_folder/py3/solve_sim/main.c"
-'  26  9  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,26,9,1621081331,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  25  1  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,25,1,1621081328,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"
-'  23  23  ~/Desktop/josiah_folder/py3/solve_sim/main.cpp
|4,39,23,23,1621081280,"~/Desktop/josiah_folder/py3/solve_sim/main.cpp"

# History of marks within files (newest to oldest):

> ~/Desktop/josiah_folder/vim/vimvscode/main.cpp
	*	1621147446	0
	"	21	5
	^	21	6
	.	2	0
	+	9	0
	+	9	1
	+	9	13
	+	9	0
	+	9	3
	+	9	0
	+	9	19
	+	12	5
	+	12	0
	+	11	0
	+	9	0
	+	9	19
	+	9	5
	+	9	0
	+	9	22
	+	9	0
	+	7	0
	+	11	19
	+	21	5
	+	2	0

> ~/Desktop/josiah_folder/vim/vimvscode/main.c
	*	1621147269	0
	"	20	0
	^	20	0
	.	31	0
	+	9	9
	+	9	0
	+	9	17
	+	9	23
	+	9	24
	+	9	25
	+	9	26
	+	9	0
	+	9	27
	+	9	0
	+	11	0
	+	9	9
	+	9	0
	+	9	17
	+	9	23
	+	9	24
	+	9	25
	+	9	26
	+	9	0
	+	9	27
	+	9	0
	+	11	0
	+	9	9
	+	9	0
	+	9	17
	+	9	23
	+	9	24
	+	9	25
	+	9	26
	+	9	0
	+	9	27
	+	9	0
	+	11	0
	+	9	9
	+	9	0
	+	9	17
	+	9	23
	+	9	24
	+	9	25
	+	9	26
	+	9	0
	+	9	27
	+	9	0
	+	11	0
	+	9	22
	+	9	0
	+	7	0
	+	24	9
	+	17	23
	+	18	24
	+	19	25
	+	20	0
	+	26	9
	+	16	0
	+	7	0
	+	16	17
	+	17	23
	+	18	24
	+	19	25
	+	20	26
	+	21	0
	+	20	0
	+	21	27
	+	1	0
	+	29	0
	+	31	0
	+	26	9
	+	16	0
	+	7	0
	+	16	17
	+	17	23
	+	18	24
	+	19	25
	+	20	26
	+	21	0
	+	20	0
	+	21	27
	+	1	0
	+	29	0
	+	31	0

> ~/Desktop/josiah_folder/vim/vimvscode/main.py
	*	1621163940	0
	"	14	9
	^	14	10
	.	14	9
	+	12	16
	+	12	0
	+	12	4
	+	12	21
	+	12	0
	+	14	0
	+	17	0
	+	12	0
	+	12	9
	+	12	10
	+	12	4
	+	12	21
	+	12	16
	+	12	0
	+	12	4
	+	12	21
	+	12	0
	+	14	0
	+	17	0
	+	12	0
	+	12	9
	+	12	10
	+	12	4
	+	12	21
	+	12	16
	+	12	0
	+	12	4
	+	12	21
	+	12	0
	+	14	0
	+	17	0
	+	12	0
	+	12	9
	+	12	10
	+	12	4
	+	12	21
	+	12	16
	+	12	0
	+	12	4
	+	12	21
	+	12	0
	+	14	0
	+	17	0
	+	12	0
	+	12	9
	+	12	10
	+	12	4
	+	12	21
	+	12	16
	+	12	0
	+	12	4
	+	12	21
	+	12	0
	+	14	0
	+	17	0
	+	12	0
	+	12	9
	+	12	10
	+	12	4
	+	12	21
	+	12	16
	+	12	0
	+	12	4
	+	12	21
	+	12	0
	+	14	0
	+	17	0
	+	12	0
	+	12	9
	+	12	10
	+	12	4
	+	12	21
	+	12	16
	+	12	0
	+	12	4
	+	12	21
	+	12	0
	+	14	0
	+	17	0
	+	12	0
	+	12	9
	+	12	10
	+	12	4
	+	12	21
	+	12	16
	+	12	0
	+	12	4
	+	12	21
	+	12	0
	+	14	0
	+	17	0
	+	12	0
	+	10	0
	+	18	4
	+	18	21
	+	20	15
	+	21	0
	+	23	4
	+	23	21
	+	14	9

> ~/Desktop/josiah_folder/vim/vimvscode/module.h
	*	1621147016	0
	"	14	0
	^	8	0
	.	13	0
	+	9	8
	+	9	5
	+	9	0
	+	9	8
	+	9	0
	+	9	8
	+	9	5
	+	9	0
	+	9	8
	+	9	0
	+	9	8
	+	9	5
	+	9	0
	+	9	8
	+	9	0
	+	9	8
	+	9	5
	+	9	0
	+	9	8
	+	9	0
	+	9	8
	+	22	5
	+	7	0
	+	1	8
	+	1	5
	+	1	0
	+	1	8
	+	1	0
	+	13	0
	+	1	8
	+	1	5
	+	1	0
	+	1	8
	+	1	0
	+	13	0
